---
title: "analysis_12_17"
author: "Trude"
date: "20-6-2021"
output: github_document:
  toc: true
  toc_depth: 3
  number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Lao PDR: MICS Data - mics4 and mics6






```{r options}

options(scipen = 999) # suppress scientific notion

```



```{r packages}

library(tidyverse)

# library(expss) # export

library(haven) 

library(sjPlot)

#library(sjlabelled)

#library(labelled)

#library(surveytoolbox) # install with #devtools::install_github("martinctc/surveytoolbox")

library(lubridate) # working with dates

library(survey)

#library(sjmisc)

#library(knitr)

library(janitor)

#library(survminer)

library(DataExplorer)

library(naniar)

library(jtools)

library(MASS)

library(lmtest)

library(scales)
```

# B1

## mics4_b1


```{r dataset mics4 ch}

mics4.ch <- read_sav("./data/mics4/ch.sav")

```


```{r dataset mics4 wm}

mics4.wm <- read_sav("./data/mics4/wm.sav")

```


```{r glimpse}

# look at lables 
sjPlot::view_df(mics4.ch)

```

```{r selecting variables children dataset}

mics4.ch_var <- subset(mics4.ch, select = c("HH1", "HH2", "UF4", "UF6", "UF8Y", "HH6", "HH7", "CAGE", "AG2", "CAGED", "IM1", "IM3H0D", "IM3H0M", "IM3H0Y", "IM3H1D", "IM3H1M", "IM3H1Y", "IM3H2D", "IM3H2M", "IM3H2Y", "IM3H3D", "IM3H3M", "IM3H3Y", "IM5", "IM6", "IM19A", "IM19B", "IM19C", "IM11", "IM12", "IM13", "IM14", "IM15", "AG1D", "AG1M", "AG1Y", "ethnicity", "melevel", "HH7R", "windex5", "HL4", "chweight", "UF11"))

```


### Merging women data to children data 

```{r merging}
# selecting subset of variables of women's dataset
mics4.wm_var <- subset(mics4.wm, select = c("HH1", "HH2", "LN", "MN1", "MN2A", "MN2B", "MN2C", "MN2F", "MN2G", "MN2X", "MN3", "MN18"))

# change variable name in women dataset in order to match with children's
mics4.wm_var$UF6 <- mics4.wm_var$LN
mics4.wm_var %>% count(UF6, LN)

# 11258 281
# 23937 12 


# Merge joining variables from dataset woman to dataset children_2012 using as key variable: UF6 (mothers or caretakers line number in ch.sav).
# Common variables used to merge are: HH1, HH2, UF6 in children, LN in women
mics4.ch_wm <- merge(mics4.ch_var, mics4.wm_var, by=c("HH1", "HH2", "UF6"), all.x = TRUE)

# Look if merging succeeded
sjPlot::view_df(mics4.ch_wm)


```

```{r date of birth}

# Date of birth 
mics4.ch_wm %>% count(AG1D)
mics4.ch_wm %>% count(AG1M)

class(mics4.ch_wm$UB1M)

mics4.ch_wm$AG1D_2 <- as.numeric(mics4.ch_wm$AG1D)

mics4.ch_wm$AG1M_2 <- as.numeric(mics4.ch_wm$AG1M)

mics4.ch_wm$AG1Y_2 <- as.numeric(mics4.ch_wm$AG1Y)

mics4.ch_wm %>%  mutate(dob_ch = make_date(AG1Y_2, AG1M_2, AG1D_2)) -> mics4.ch_wm
#mics4.ch_wm$dob_ch
class(mics4.ch_wm$AG1M_2)

```



```{r household and child id}


# Household ID
mics4.ch_wm %>% unite(HH_id, c(HH1, HH2), sep = "_", remove = FALSE, na.rm = FALSE) -> mics4.ch_wm


# households with more than one child
mics4.ch_wm %>% 
  filter(AG2 <3) %>% 
  group_by(HH_id) %>% filter(n()>1) %>% summarize(n=n())# 806

# unique id for each child
mics4.ch_wm %>% unite(ch_id, c(HH1, HH2, UF4), sep = "_", remove = FALSE, na.rm = FALSE) -> mics4.ch_wm

mics4.ch_wm %>% group_by(ch_id) %>% filter(n()>1) %>% summarize(n=n()) # none...
# identify each child


```




```{r strata}

mics4.ch_wm %>% 
  unite(strata, c(HH7, HH6), sep = "_", remove = FALSE, na.rm = FALSE) -> mics4.ch_wm
mics4.ch_wm %>% count(strata)


```



### Subset 4_b1

```{r mics4.ch_b1}

#subset children under 3
mics4.ch_wm %>% filter(AG2 < 3) -> mics4.ch_b1 
# 6591 when using CAGE, 
# 6573 using AG2, difference is because there are 19 children who are 3 years and 35 months, and 1 child 36 month and 2 years old. 


```



### New variables

```{r hepatitis B birth dose}


# Convert to numeric values: day/ month/ year

mics4.ch_b1$IM3H0D_2 <- as.numeric(mics4.ch_b1$IM3H0D)
mics4.ch_b1$IM3H0M_2 <- as.numeric(mics4.ch_b1$IM3H0M)
mics4.ch_b1$IM3H0Y_2 <- as.numeric(mics4.ch_b1$IM3H0Y)

# Now create the date
mics4.ch_b1 %>% mutate(IM3H0_date = make_date(IM3H0Y_2, IM3H0M_2, IM3H0D_2)) -> mics4.ch_b1
mics4.ch_b1 %>% count(IM3H0_date) # looks ok


# Time since vaccination

# I am using a command from R base here. There is probably a way to calculate it with a tidyverse command

mics4.ch_b1$IM3H0_time <- as.numeric(difftime(mics4.ch_b1$IM3H0_date, mics4.ch_b1$dob_ch, units = "days"))
summary(mics4.ch_b1$IM3H0_time)
# Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
# -365.00    0.00    0.00   17.44    6.50  688.00    5100 

# Comments on time since vaccination:
# min = -365 probably mistake in year. 
# Max = 688 days; could be a mistake in writing down the year?


# histogram
mics4.ch_b1 %>% ggplot(aes(x=IM3H0_time)) + geom_histogram(binwidth = 1)

# Card: vaccinated within 24 hours

mics4.ch_b1 %>% 
  mutate(hepb0_C24 = ifelse(IM3H0_time == 0, "The same day", ifelse(IM3H0_time == 1, "The next day", "Later"))) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C24) 

# some children can have NA because they have no date of birth instead of no date on vaccination!! They have no info on time since vaccination (IM3H0_time), but that doesn't mean that they are not vaccinated. Check by comparing info on dob and date of vaccination. 

mics4.ch_b1 %>% mutate(dov_1 = if_else(IM3H0D <= 31 & IM3H0D >=1, 1, 0)) -> mics4.ch_b1
mics4.ch_b1 %>% mutate(dob_1 = if_else(AG1D <= 31 & AG1D >=1, 1, 0)) -> mics4.ch_b1
mics4.ch_b1 %>% count(dov_1, dob_1, hepb0_C24)
#24 children have a date on vaccination but no date on birth, therefore the time difference can not be calculated. They are in the category NA, while they should be in the category 'later'. 
#2 children have dates on both vaccination and birth but have NA on hepb0_C24. Why? normally they should be categorized in "LAter". Maybe because the have a negative time??

#change date variables into categorical variables
mics4.ch_b1 %>% mutate(hepb0_C = if_else(IM3H0D <= 31 & IM3H0D >=1, 1,
                                        if_else(IM3H0D == 0, 0,
                                        if_else(IM3H0D == 44, 44, 
                                        if_else(IM3H0D == 66, 66,99))))) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C)

# Code variable hepb0_C
# if date is there = 1
# marked on card = 44
# mother reported = 66  # technically recall 
# missing = 99
# not given = 0


mics4.ch_b1 %>% count(hepb0_C, hepb0_C24) # There are 24 + 2 people for which the the categorization did not work - why? - because there is no date of birth or negative one. 

# combination of card within 24 hours and card date variable
mics4.ch_b1 %>% 
  unite(hepb0_C, c(hepb0_C, hepb0_C24), sep = "_", remove = FALSE, na.rm = FALSE) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C)


# NA_NA needs to be replaced with NA
mics4.ch_b1 %>% replace_with_na(replace = list(hepb0_C = "NA_NA")) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C)


# Recall variable IM14 hepb0 within 24 hours or later
# Recode IM14 into hepb0_R: recall variable

mics4.ch_b1 %>% count(IM14)
mics4.ch_b1$IM14_2 <- as.numeric(mics4.ch_b1$IM14)
mics4.ch_b1 %>% count(IM13)
mics4.ch_b1$IM13_2 <- as.numeric(mics4.ch_b1$IM13)
mics4.ch_b1 %>% 
  mutate(hepb0_R_14 = recode(IM14_2,
                           "1" = "R_Yes",
                           "2" = "R_Later",
                           "9" = "R_9")) -> mics4.ch_b1
mics4.ch_b1 %>% 
  mutate(hepb0_R_13 = recode(IM13_2,
                           "1" = "R_Yes",
                           "2" = "R_No",
                           "8" = "R_8",
                           "9" = "R_9")) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C, hepb0_R_13, hepb0_R_14)


mics4.ch_b1 %>% count(hepb0_C, hepb0_R_13, hepb0_R_14, IM6, IM5)

# It is not yet correct
# In IM6; if responses were No, DK or Missing; there was no probing for the recall of vaccinations
# Therefore; some of the NAs in the new variable need to be changed to "No" or "DK" or Missing

mics4.ch_b1 %>% 
  mutate(hepb0_R_13 = replace(hepb0_R_13, is.na(hepb0_R_13) & IM6 == 2, "R_No"))  %>%
  mutate(hepb0_R_13 = replace(hepb0_R_13, is.na(hepb0_R_13) & IM6 == 8, "R_8"))  %>%
  mutate(hepb0_R_13 = replace(hepb0_R_13, is.na(hepb0_R_13) & IM6 == 9, "R_9")) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_R_13)
mics4.ch_b1 %>% count(hepb0_C, hepb0_R_13, hepb0_R_14)

# Combine Recall variable 13 and 14 into one recall variable
mics4.ch_b1 %>% 
  unite(hepb0_R, c(hepb0_R_13, hepb0_R_14), sep = "_", remove = FALSE, na.rm = FALSE) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C)

mics4.ch_b1 %>% count(hepb0_C, hepb0_R)
mics4.ch_b1 %>% mutate(hepb0_RC = coalesce(hepb0_C, hepb0_R)) -> mics4.ch_b1 
mics4.ch_b1 %>% count(hepb0_RC)

# Now, all responses should be categorized correctly, at least all NA's. 
# Except for 44_NA -> 1_Later: Marked on card, not known whether within 24 hrs
# and 66_NA -> which should be categorized as recall, mother reported that there was a vaccination but not sure whether within 24 hours 

mics4.ch_b1 %>% 
  mutate(hepb0_RC = recode(hepb0_RC,
                           "0_NA" = "0",
                           "1_NA" = "1_Later", 
                           "44_NA" = "1_Later",
                           "66_NA" = "R_Later",
                           "99_NA" = "0",
                           "R_8_NA" = "R_8",
                           "R_9_NA" = "R_9",
                           "R_No_NA" = "R_No",
                           "R_Yes_R_9" = "R_Later",
                           "R_Yes_R_Later" = "R_Later",
                           "R_Yes_R_Yes" = "R_Yes" )) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_RC)

# hepatitis B birth dose (yes, no)
# DK will be grouped with no
# Missing will be grouped with no
# Within 24 hours or the next day: 1
# later: 2
# no vaccination: 0
mics4.ch_b1 %>% 
  mutate(hepb0_RC_1 = recode(hepb0_RC,
                           "0" = "0",
                           "1_Later" = "2",
                           "1_The next day" = "1",
                           "1_The same day" = "1",
                           "R_No" = "0",
                           "R_8" = "0",
                           "R_9" = "0",
                           "R_Later" = "2",
                           "R_Yes" = "1")) -> mics4.ch_b1

mics4.ch_b1 %>% count(hepb0_RC_1, hepb0_RC)


# create new variable within 24 hours: 1, not within 24 hours:0
mics4.ch_b1 %>% 
  mutate(hepb0_RC_24 = recode(hepb0_RC_1,
                           "0" = "0",
                           "2" = "0",
                           "1" = "1"
                          )) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_RC_24)

# create new variable hepb0 yes or no card and recall
mics4.ch_b1 %>% 
  mutate(hepb0_RC_2 = recode(hepb0_RC_1,
                           "0" = "0",
                           "2" = "1",
                           "1" = "1"
                          )) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_RC_2)

# only card
# 66_NA needs to be replaced with NA
mics4.ch_b1 %>% replace_with_na(replace = list(hepb0_C = "66_NA")) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C)

# only card variable hepb0 (yes/no)
mics4.ch_b1 %>% 
  mutate(hepb0_C_2 = recode(hepb0_C,
                           "0_NA" = "0",
                           "1_Later" = "1",
                           "1_NA" = "1",
                           "1_The next day" = "1",
                           "1_The same day" = "1",
                           "44_NA" = "1",
                           "99_NA" = "0")) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C_2)

# only card variable hepb0 (24hrs)
mics4.ch_b1 %>% 
  mutate(hepb0_C_24 = recode(hepb0_C,
                           "0_NA" = "0",
                           "1_Later" = "0",
                           "1_NA" = "0",
                           "1_The next day" = "1",
                           "1_The same day" = "1",
                           "44_NA" = "0",
                           "99_NA" = "0")) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C_24)

mics4.ch_b1$hepb0_R_1 <- mics4.ch_b1$hepb0_RC
mics4.ch_b1 %>% count(hepb0_R_1)

# all outcomes from Card need to be replaced with NA: hepb0_RC is now variable hepb0_R with recall from card variable outcome 66
mics4.ch_b1 %>% replace_with_na(replace = list(hepb0_R_1 = c("0", "1_Later", "1_The next day", "1_The same day"))) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_R_1)

# only recal hepbo within 24 hours (yes/no)
mics4.ch_b1 %>%
  mutate(hepb0_R_24 = recode(hepb0_R_1,
                           "R_No" = "0",
                           "R_8" = "0",
                           "R_9" = "0",
                           "R_Later" = "0",
                           "R_Yes" = "1")) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_R_24)

# only recall variable hepb0 (yes/no)
mics4.ch_b1 %>% 
  mutate(hepb0_R_2 = recode(hepb0_R_1,
                           "R_No" = "0",
                           "R_8" = "0",
                           "R_9" = "0",
                           "R_Later" = "1",
                           "R_Yes" = "1"
                          )) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_R_2)


# Needed dichotomous variables for analysis
mics4.ch_b1 %>% count(hepb0_RC_2) # 0: 3444 1: 3129
mics4.ch_b1 %>% count(hepb0_RC_24)# 0: 5287 1: 1286
mics4.ch_b1 %>% count(hepb0_C_2)  # 0: 1197 1: 1653
mics4.ch_b1 %>% count(hepb0_C_24) # 0: 1939 1: 911
mics4.ch_b1 %>% count(hepb0_R_2) # 0: 2247 1: 1476
mics4.ch_b1 %>% count(hepb0_R_24) # 0: 3348 1: 375



```

```{r recode independent variables}


mics4.ch_b1 %>% mutate(ethnicity_r = recode(ethnicity, "1" = 1, "2" = 2, "3" = 3, "4" = 4, "9" = 4)) -> mics4.ch_b1
mics4.ch_b1 %>% count(ethnicity_r)

mics4.ch_b1 %>% mutate(melevel = recode(melevel, "1" = 0, "2" = 1, "3" = 2, "4" = 3, "5" = 4, "6" = 5, "9" = 9)) -> mics4.ch_b1
mics4.ch_b1 %>% count(melevel)

mics4.ch_b1 %>% mutate(melevel_r = recode(melevel, "0" = 0, "1" = 1, "2" = 2, "3" = 2, "4" = 2, "5" = 2, "9" = 0)) -> mics4.ch_b1
mics4.ch_b1 %>% count(melevel, melevel_r)

mics4.ch_b1$hh7r <- mics4.ch_b1$HH7R
mics4.ch_b1$year <- mics4.ch_b1$UF8Y
mics4.ch_b1$AGE <- mics4.ch_b1$AG2

mics4.ch_b1 %>% mutate(year = recode(year, "2011" = 2012, "2012" = 2012)) -> mics4.ch_b1
mics4.ch_b1 %>% count(year)

```

```{r change anc variables}

mics4.ch_b1 %>% count(MN18)

mics4.ch_b1 %>% count(MN3)

mics4.ch_b1 %>% count(MN1)

mics4.ch_b1 %>% replace_with_na(replace = list(MN18 = "99")) -> mics4.ch_b1

mics4.ch_b1 %>% replace_with_na(replace = list(MN3 = "99")) -> mics4.ch_b1

mics4.ch_b1 %>% replace_with_na(replace = list(MN1 = "9")) -> mics4.ch_b1


mics4.ch_b1 %>% count(MN18)

mics4.ch_b1 %>% count(MN3)

mics4.ch_b1 %>% count(MN1)


mics4.ch_b1$ANC <- mics4.ch_b1$MN1

mics4.ch_b1 %>% mutate(ANC = recode(ANC,
                                     "1" = 1,
                                     "2" = 0
                                     )) -> mics4.ch_b1

# new variable place of delivery
mics4.ch_b1 %>% mutate(PoB = dplyr::recode(MN18,
                        "11" = "1",
                        "12" = "1",
                        "21" = "2",
                        "22" = "2",
                        "26" = "2",
                        "31" = "3",
                        "32" = "3",
                        "33" = "3",
                        "36" = "3",
                        "96" = "3"
                        )) -> mics4.ch_b1
mics4.ch_b1 %>% count(MN18, PoB)


mics4.ch_b1 %>% mutate(ANC_T = if_else(MN3 >= 1 & MN3 <=3 | MN3 == 98, 1,
                                        if_else(MN3 >= 4 & MN3 <= 6, 2, 3
                                       ))) -> mics4.ch_b1
mics4.ch_b1 %>% count(MN3, ANC_T)

mics4.ch_b1 %>% count(MN2A, MN2B, MN2C, MN2F, MN2G, MN2X)
mics4.ch_b1 %>% count(MN1, MN2A)


# changing variable MN2 into categories

mics4.ch_b1 %>% count(MN2A, MN2B, MN2C, MN2F, MN2G, MN2X)
mics4.ch_b1 %>% count(MN1, MN2A)

mics4.ch_b1 %>% 
  unite(ANC_W, c(MN1, MN2A, MN2B), sep = "_", remove = FALSE, na.rm = FALSE) -> mics4.ch_b1

mics4.ch_b1 %>% replace_with_na(replace = list(ANC_W = "NA_NA_NA")) -> mics4.ch_b1
mics4.ch_b1 %>% replace_with_na(replace = list(ANC_W = "NA__")) -> mics4.ch_b1


mics4.ch_b1 %>% mutate(ANC_W = recode(ANC_W,
                                     "1_?_?" = 3,
                                     "1__" = 3,
                                     "1__B" = 2,
                                     "1_A_" = 1,
                                     "1_A_B" = 1,
                                     "2__" = 0,
                                     "9__" = 0)) -> mics4.ch_b1
mics4.ch_b1 %>% count(ANC_W)
```



```{r changing to factor}
# changing variables into factors

# data b1
mics4.ch_b1$HH7R <- as.factor(mics4.ch_b1$HH7R)
mics4.ch_b1$hh7r <- as.factor(mics4.ch_b1$hh7r)
mics4.ch_b1$HH6 <- as.factor(mics4.ch_b1$HH6)
mics4.ch_b1$windex5 <- as.factor(mics4.ch_b1$windex5)
mics4.ch_b1$HL4 <- as.factor(mics4.ch_b1$HL4)
mics4.ch_b1$ethnicity <- as.factor(mics4.ch_b1$ethnicity)
mics4.ch_b1$melevel <- as.factor(mics4.ch_b1$melevel)
mics4.ch_b1$ethnicity_r <- as.factor(mics4.ch_b1$ethnicity_r)
mics4.ch_b1$melevel_r <- as.factor(mics4.ch_b1$melevel_r)
mics4.ch_b1$PoB <- as.factor(mics4.ch_b1$PoB)
mics4.ch_b1$ANC <- as.factor(mics4.ch_b1$ANC)
mics4.ch_b1$ANC_W <- as.factor(mics4.ch_b1$ANC_W)
mics4.ch_b1$ANC_T <- as.factor(mics4.ch_b1$ANC_T)
mics4.ch_b1$year <- as.factor(mics4.ch_b1$year)
mics4.ch_b1$AGE <- as.factor(mics4.ch_b1$AGE)

mics4.ch_b1$hepb0_RC_2 <- as.factor(mics4.ch_b1$hepb0_RC_2)
mics4.ch_b1$hepb0_RC_24 <- as.factor(mics4.ch_b1$hepb0_RC_24)
mics4.ch_b1$hepb0_C_2 <- as.factor(mics4.ch_b1$hepb0_C_2)
mics4.ch_b1$hepb0_C_24 <- as.factor(mics4.ch_b1$hepb0_C_24)
mics4.ch_b1$hepb0_R_2 <- as.factor(mics4.ch_b1$hepb0_R_2)
mics4.ch_b1$hepb0_R_24 <- as.factor(mics4.ch_b1$hepb0_R_24)



```




## mics6_b1


```{r dataset mics6 ch}

# package haven
mics6.ch <- read_sav("./data/mics6/ch.sav")

```


```{r dataset mics6 wm}

mics6.wm <- read_sav("./data/mics6/wm.sav")

```







```{r mics6.ch glimpse}

# Mothers or primary caretakers of children under five – ch.sav
dim(mics6.ch)
# [1] 11812   443
glimpse(mics6.ch) 

# look at lables 
sjPlot::view_df(mics6.ch)
mics6.ch %>% labelled::look_for("UF4")

# Mother / caretaker
mics6.ch %>% count(UF4) # range from 1-20

```

```{r selecting variables children dataset}

mics6.ch_var <- subset(mics6.ch, select = c("HH1", "HH2", "UF1", "UF2", "UF3", "UF4", "UB2", "CAGE", "CAGED", "HH6", "HH7", "hh7r", "UF7D", "UF7Y", "UF7M", "UB1D", "UB1M", "UB1Y", "IM12A", "IM12B", "IM12C", "IM2", "IM5", "IM11", "IM15", "IM20", "IM21", "IM6H0D", "IM6H0M", "IM6H0Y", "IM6PENTA1D", "IM6PENTA2D", "IM6PENTA3D", "ethnicity", "melevel", "windex5", "HL4", "chweight", "hh6a", "hh6b", "cdisability"))

```


### merging women data to children 

```{r merging}

# selecting subset of variables of women's dataset
mics6.wm_var <- subset(mics6.wm, select = c("HH1", "HH2", "LN", "MN2", "MN3A", "MN3B", "MN3C", "MN3F", "MN3G", "MN3X", "MN3NR", "MN5", "MN20"))

# change variable name in women dataset in order to match with children's

# change variable name in women dataset in order to match with children's
mics6.wm_var$UF4 <- mics6.wm_var$LN

mics6.wm_var %>% count(UF4, LN) # to check if same


# Merge joining variables from dataset woman to dataset children_2017 using as key variable: UF4 (mothers or caretakers line number in ch.sav).
# Common variables used to merge are: HH1, HH2, UF4 in children, LN in women
mics6.ch_wm <- merge(mics6.ch_var, mics6.wm_var, by=c("HH1", "HH2", "UF4"), all.x = TRUE)


```



```{r household and child id}

# Household ID
mics6.ch_wm %>% unite(HH_id, c(HH1, HH2), sep = "_", remove = FALSE, na.rm = FALSE) -> mics6.ch_wm


# Are there any duplicates?
mics6.ch_wm %>% group_by(HH_id) %>% filter(n()>1) %>% summarize(n=n())
  # many?? assigned to n_HH_id: 2467 observations
# Need to clarify what this means
# Same household ID would suggest children are from same household
# Is there anything in the questionnaire that would indicate that can be more than 1 child under 5 per household
# Does this have any implications for the analysis?

# Yes, it looks as if there is a question at the end, UF16, asking if there is any other child living in that household under 5
mics6.ch_wm %>% 
  filter(UB2 <3) %>% 
  group_by(HH_id) %>% filter(n()>1) %>% summarize(n=n()) # 839 obs
839/6887 # 12.2%


# Need a unique id for each child
# UF3 should be the individual number of each child (LN of child)
# UF1 = HH1
# UF2 = HH2
mics6.ch_wm %>% unite(ch_id, c(UF1, UF2, UF3), sep = "_", remove = FALSE, na.rm = FALSE) -> mics6.ch_wm

mics6.ch_wm %>% group_by(ch_id) %>% filter(n()>1) %>% summarize(n=n()) # none...
# identify each child


```



```{r strata}

# strata
# Do I need a new variable combining HH6 and HH7?
mics6.ch_wm %>% unite(strata, c(HH7, HH6), sep = "_", remove = FALSE, na.rm = FALSE) -> mics6.ch_wm
mics6.ch_wm %>% count(strata)

# This is a good example for the combination of two columns: As you can see, the entries of both columns are connected with "_". Later, you will see another example of merging two columns in which the entries do not overlap

```



```{r date of interview}

# Day of the interview

mics6.ch_wm$UF7D_2 <- as.numeric(as.character(mics6.ch_wm$UF7D))
mics6.ch_wm$UF7Y_2 <- as.numeric(as.character(mics6.ch_wm$UF7Y))
mics6.ch_wm$UF7M_2 <- as.numeric(as.character(mics6.ch_wm$UF7M))

# day of interview
mics6.ch_wm %>%  mutate(I_date = make_date(UF7Y_2, UF7M_2, UF7D_2)) -> mics6.ch_wm
# A function from lubridate package

```



```{r date of birth}

# Date of birth 
mics6.ch_wm %>% count(UB1D)
mics6.ch_wm %>% count(UB1M)

class(mics6.ch_wm$UB1M)

mics6.ch_wm$UB1D_2 <- as.numeric(mics6.ch_wm$UB1D)

mics6.ch_wm$UB1M_2 <- as.numeric(mics6.ch_wm$UB1M)

mics6.ch_wm$UB1Y_2 <- as.numeric(mics6.ch_wm$UB1Y)

mics6.ch_wm %>%  mutate(dob_ch = make_date(UB1Y_2, UB1M_2, UB1D_2)) -> mics6.ch_wm
#mics6.ch_wm$dob_ch
class(mics6.ch_wm$UB1M_2)

```



```{r recall or not}

# IM11
mics6.ch_wm %>% filter(UB2 < 3) %>% count(IM11)
# If vaccination card or any other documents are not available to be checked, IM11 was asked


mics6.ch_wm %>% count(IM11, IM12A, IM12B, IM12C)

# If response to IM11 and IM12 was always No or DK; child did not receive any vaccination!


# Variable: NO or DK

mics6.ch_wm %>% 
  mutate(IM11_IM12 = ifelse((IM11 == 2 | IM11 == 8) & 
                            (IM12A == 2 | IM12A == 8) &
                            (IM12B == 2 | IM12B == 8) &
                             (IM12C == 2 | IM12C == 8), 0, 1)) -> mics6.ch_wm
mics6.ch_wm %>% count(IM11_IM12, IM11, IM12A, IM12B, IM12C)

mics6.ch_wm %>% count(IM11, IM11_IM12)

mics6.ch_wm %>% 
  mutate(IM11_2 = ifelse((IM11_IM12 == 0 & IM11 == 2), 2,
                  ifelse((IM11_IM12 == 0 & IM11 == 8), 8, NA))) -> mics6.ch_wm

mics6.ch_wm %>% count(IM11,IM11_2)
# looks ok




# Table: is there vaccination card, vaccination document seen, recall
mics6.ch_wm %>% count(IM2, IM5, IM11) # all NAs in kids under 3 are recall; not NA


# New variable
# recall - 0: no; vaccination documents were there
# recall - 1: yes; no vaccination documents 
# Recode all entries into "1"
mics6.ch_wm %>% mutate(recall = recode(IM11, "1" = 1, "2" = 1, "8" = 1)) -> mics6.ch_wm
                                  
mics6.ch_wm %>% count(recall) # ok

# Replace all NA in children under 5 with "0"
mics6.ch_wm %>%  mutate(recall = replace(recall, is.na(recall), 0))  -> mics6.ch_wm
mics6.ch_wm %>% count(recall)

mics6.ch_wm %>%count(IM11, recall) # seems like it did work

# BUT: Sometimes for the IM6 responses, there was the option for mother´s report.... This is essentially recall!

# I would check that for each vaccination individually

```



```{r source of information} 

# Sometimes, it is nice to re-check where information is coming from. IM2 only asks if participants have any of the vaccination documents
# IM5 actually says which of them was AVAILABLE
# IM5 is only asked if participants respond that they have any of the documents
# All NA in IM5 responded they do not possess any vaccination document

mics6.ch_wm %>% filter(UB2 < 3) %>% count(IM2, IM5)
# First, need to convert NAs in IM5

mics6.ch_wm %>% mutate(IM5_2 = replace(IM5, is.na(IM5) & UB2 < 3, 5)) -> mics6.ch_wm
mics6.ch_wm %>% count(IM5, IM5_2, recall)


# Variable 2
# Info from any document 
mics6.ch_wm %>% mutate(IM5_3 = recode(IM5_2, "5" = 4)) -> mics6.ch_wm
mics6.ch_wm %>% count(IM5_2, IM5_3) # ok

# recall variable IM11 in combination with IM5_2
mics6.ch_wm %>% filter(UB2 < 3) %>% count(IM5_2, IM11)

```



### subset 6_b1

```{r mics6.ch_b1}

#subset children under 3
mics6.ch_wm %>% filter(UB2 < 3) -> mics6.ch_b1 


```

### New variables in mics6.ch_b1



```{r hepatitis B birth dose}

# Need to create variables; for having a date of vaccination
# marked on card

# First create the date of vaccination


# Date              
# NOT GIVEN         
# MARKED ON CARD    
# MOTHER REPORTED   
# Inconsistent      
# NO RESPONSE       


# hepatitis B birth dose



# Convert to numeric values: day/ month/ year

mics6.ch_b1$IM6H0D_2 <- as.numeric(mics6.ch_b1$IM6H0D)
mics6.ch_b1$IM6H0M_2 <- as.numeric(mics6.ch_b1$IM6H0M)
mics6.ch_b1$IM6H0Y_2 <- as.numeric(mics6.ch_b1$IM6H0Y)

# Now create the date
mics6.ch_b1 %>% mutate(IM6H0_date = make_date(IM6H0Y_2, IM6H0M_2, IM6H0D_2)) -> mics6.ch_b1
mics6.ch_b1 %>% count(IM6H0_date) # looks ok


# Time since vaccination

# I am using a command from R base here. There is probably a way to calculate it with a tidyverse command

mics6.ch_b1$IM6H0_time <- as.numeric(difftime(mics6.ch_b1$IM6H0_date, mics6.ch_b1$dob_ch, units = "days"))
summary(mics6.ch_b1$IM6H0_time)
# Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
#   0.00    0.00    0.00   15.69    1.00  731.00  4088

# Comments on time since vaccination:
# no negative values! negative values would indicate mistakes in dob or date of vaccination
# Max = 731 days; could be a mistake in writing down the year?


# histogram
mics6.ch_b1 %>% ggplot(aes(x=IM6H0_time)) + geom_histogram(binwidth = 1)

# Card: vaccinated within 24 hours

mics6.ch_b1 %>% 
  mutate(hepb0_C24 = ifelse(IM6H0_time == 0, "The same day", ifelse(IM6H0_time == 1, "The next day", "Later"))) -> mics6.ch_b1

mics6.ch_b1 %>% count(hepb0_C24)


#change date variables into categorical variables
mics6.ch_b1 %>% mutate(hepb0_C = if_else(IM6H0D <= 31 & IM6H0D >=1, 1,
                                        if_else(IM6H0D == 0, 0,
                                        if_else(IM6H0D == 44, 44, 66)))) -> mics6.ch_b1


mics6.ch_b1 %>% count(hepb0_C)

# Code variable hepb0_C
# if date is there = 1
# marked on card = 44
# mother reported = 66  # technically recall 
# not given = 0


mics6.ch_b1 %>% count(hepb0_C, hepb0_C24) # There are 4 people for which the the categorization did not work - why??

# combination of card within 24 hours and card date variable
mics6.ch_b1 %>% 
  unite(hepb0_C, c(hepb0_C, hepb0_C24), sep = "_", remove = FALSE, na.rm = FALSE) -> mics6.ch_b1
mics6.ch_b1 %>% count(hepb0_C)


# NA_NA needs to be replaced with NA
mics6.ch_b1 %>% replace_with_na(replace = list(hepb0_C = "NA_NA")) -> mics6.ch_b1
mics6.ch_b1 %>% count(hepb0_C)

# Now combine recall and info from card


# First recode IM15 into hepb0_R: recall variable

mics6.ch_b1 %>% count(IM15)
mics6.ch_b1 %>% 
  mutate(hepb0_R = recode(IM15,
                           "1" = "R_Yes",
                           "2" = "R_Later",
                           "3" = "R_0",
                           "8" = "R_8",
                           "9" = "R_9")) -> mics6.ch_b1
mics6.ch_b1 %>% count(IM15, hepb0_R)


mics6.ch_b1 %>% count(hepb0_R, IM11, IM11_2, IM11_IM12)

# It is not yet correct
# In IM11 & IM12; if all responses were "NO"; there was no probing for the recall of vaccinations
# Therefore; soome of the NAs in the new variable need to be changed to "No" or "DK" #810 no and #24 DK

mics6.ch_b1 %>% 
  mutate(hepb0_R = replace(hepb0_R, is.na(hepb0_R) & IM11 == 2, "R_0"))  %>%
  mutate(hepb0_R = replace(hepb0_R, is.na(hepb0_R) & 
                               IM11 == 8, "R_8")) -> mics6.ch_b1
mics6.ch_b1 %>% count(hepb0_R)

mics6.ch_b1 %>% mutate(hepb0_RC = coalesce(hepb0_R, hepb0_C)) -> mics6.ch_b1 
mics6.ch_b1 %>% count(hepb0_RC)

# Now, all responses should be categorized correctly !!!
# Except for 44_NA -> 1_Later: Marked on card, not known whether within 24 hrs
# and 66_NA -> which should be categorized as recall, mother reported that there was a vaccination but not sure whether within 24 hours 

mics6.ch_b1 %>% 
  mutate(hepb0_RC = recode(hepb0_RC,
                           "1_NA" = "1_Later", 
                           "44_NA" = "1_Later",
                           "66_NA" = "R_Later",
                           )) -> mics6.ch_b1
mics6.ch_b1 %>% count(hepb0_RC)

# hepatitis B birth dose (yes, no)
# DK will be grouped with no
# NO RESPONSE will be grouped with no
# Within 24 hours or the next day: 1
# later: 2
# no vaccination: 0
mics6.ch_b1 %>% 
  mutate(hepb0_RC_1 = recode(hepb0_RC,
                           "0_NA" = "0",
                           "1_Later" = "2",
                           "1_The next day" = "1",
                           "1_The same day" = "1",
                           "R_0" = "0",
                           "R_8" = "0",
                           "R_9" = "0",
                           "R_Later" = "2",
                           "R_Yes" = "1")) -> mics6.ch_b1

mics6.ch_b1 %>% count(hepb0_RC_1, hepb0_RC)


# create new variable within 24 hours: 1, not within 24 hours:0
mics6.ch_b1 %>% 
  mutate(hepb0_RC_24 = recode(hepb0_RC_1,
                           "0" = "0",
                           "2" = "0",
                           "1" = "1"
                          )) -> mics6.ch_b1
mics6.ch_b1 %>% count(hepb0_RC_24)

# create new variable hepb0 yes or no card and recall
mics6.ch_b1 %>% 
  mutate(hepb0_RC_2 = recode(hepb0_RC_1,
                           "0" = "0",
                           "2" = "1",
                           "1" = "1"
                          )) -> mics6.ch_b1
mics6.ch_b1 %>% count(hepb0_RC_2)


# 66_NA needs to be replaced with NA
mics6.ch_b1 %>% replace_with_na(replace = list(hepb0_C = "66_NA")) -> mics6.ch_b1
mics6.ch_b1 %>% count(hepb0_C)

# only card variable hepb0 (yes/no)
mics6.ch_b1 %>% 
  mutate(hepb0_C_2 = recode(hepb0_C,
                           "0_NA" = "0",
                           "1_Later" = "1",
                           "1_NA" = "1",
                           "1_The next day" = "1",
                           "1_The same day" = "1",
                           "44_NA" = "1")) -> mics6.ch_b1
mics6.ch_b1 %>% count(hepb0_C_2)

# only card variable hepb0 (24hrs)
mics6.ch_b1 %>% 
  mutate(hepb0_C_24 = recode(hepb0_C,
                           "0_NA" = "0",
                           "1_Later" = "0",
                           "1_NA" = "0",
                           "1_The next day" = "1",
                           "1_The same day" = "1",
                           "44_NA" = "0")) -> mics6.ch_b1
mics6.ch_b1 %>% count(hepb0_C_24)

mics6.ch_b1$hepb0_R_1 <- mics6.ch_b1$hepb0_RC

# all outcomes from Card need to be replaced with NA: hepb0_RC is now variable hepb0_R with recall from card variable outcome 66
mics6.ch_b1 %>% replace_with_na(replace = list(hepb0_R_1 = c("0_NA", "1_Later", "1_The next day", "1_The same day"))) -> mics6.ch_b1
mics6.ch_b1 %>% count(hepb0_R_1)

# only recal hepbo within 24 hours (yes/no)
mics6.ch_b1 %>%
  mutate(hepb0_R_24 = recode(hepb0_R_1,
                           "R_0" = "0",
                           "R_8" = "0",
                           "R_9" = "0",
                           "R_Later" = "0",
                           "R_Yes" = "1")) -> mics6.ch_b1
mics6.ch_b1 %>% count(hepb0_R_24)

# only recall variable hepb0 (yes/no)
mics6.ch_b1 %>% 
  mutate(hepb0_R_2 = recode(hepb0_R_1,
                           "R_0" = "0",
                           "R_8" = "0",
                           "R_9" = "0",
                           "R_Later" = "1",
                           "R_Yes" = "1"
                          )) -> mics6.ch_b1
mics6.ch_b1 %>% count(hepb0_R_2)

# only recall variable hepb0 (within 24 hrs: yes/no)
mics6.ch_b1 %>% 
  mutate(hepb0_R_24 = recode(hepb0_R_1,
                           "R_0" = "0",
                           "R_8" = "0",
                           "R_9" = "0",
                           "R_Later" = "0",
                           "R_Yes" = "1"
                          )) -> mics6.ch_b1
mics6.ch_b1 %>% count(hepb0_R_24)

# Needed dichotomous variables for analysis
mics6.ch_b1 %>% count(hepb0_RC_2) # 0: 2159 1: 4728
mics6.ch_b1 %>% count(hepb0_RC_24)# 0: 3682 1: 3205
mics6.ch_b1 %>% count(hepb0_C_2)  # 0: 807 1: 2903
mics6.ch_b1 %>% count(hepb0_C_24) # 0: 1543 1: 2167
mics6.ch_b1 %>% count(hepb0_R_2) # 0: 1352 1: 1825
mics6.ch_b1 %>% count(hepb0_R_24) # 0: 2139 1: 1038



```

```{r recode independent variables}

mics6.ch_b1 %>% mutate(ethnicity_r = recode(ethnicity, "1" = 1, "2" = 2, "3" = 3, "4" = 4, "9" = 4)) -> mics6.ch_b1
mics6.ch_b1 %>% count(ethnicity_r)

mics6.ch_b1 %>% mutate(melevel_r = recode(melevel, "0" = 0, "1" = 1, "2" = 2, "3" = 2, "4" = 2, "5" = 2, "6" = 2, "9" = 0)) -> mics6.ch_b1
mics6.ch_b1 %>% count(melevel, melevel_r)

mics6.ch_b1$HH7R <- mics6.ch_b1$hh7r
mics6.ch_b1$year <- mics6.ch_b1$UF7Y
mics6.ch_b1$AGE <- mics6.ch_b1$UB2

```

```{r change anc variables}
mics6.ch_b1 %>% count(MN20)

mics6.ch_b1 %>% count(MN5)

mics6.ch_b1 %>% count(MN2)

mics6.ch_b1 %>% replace_with_na(replace = list(MN20 = "99")) -> mics6.ch_b1

mics6.ch_b1 %>% replace_with_na(replace = list(MN5 = "99")) -> mics6.ch_b1

mics6.ch_b1 %>% replace_with_na(replace = list(MN2 = "9")) -> mics6.ch_b1


mics6.ch_b1 %>% count(MN20)

mics6.ch_b1 %>% count(MN5)

mics6.ch_b1 %>% count(MN2)

mics6.ch_b1$ANC <- mics6.ch_b1$MN2


mics6.ch_b1 %>% mutate(ANC = recode(ANC,
                                     "1" = 1,
                                     "2" = 0)) -> mics6.ch_b1

# new variable place of delivery
mics6.ch_b1 %>% mutate(PoB = dplyr::recode(MN20,
                        "11" = "1",
                        "12" = "1",
                        "21" = "2",
                        "22" = "2",
                        "26" = "2",
                        "31" = "3",
                        "32" = "3",
                        "33" = "3",
                        "36" = "3",
                        "96" = "3")) -> mics6.ch_b1
mics6.ch_b1 %>% count(MN20, PoB)


mics6.ch_b1 %>% mutate(ANC_T = if_else(MN5 >= 1 & MN5 <=3, 1,
                                        if_else(MN5 >= 4 & MN5 <= 6, 2, 3))) -> mics6.ch_b1
mics6.ch_b1 %>% count(MN5, ANC_T)



# changing variable MN3 into categories

mics6.ch_b1 %>% count(MN3A, MN3B, MN3C, MN3F, MN3G, MN3X, MN3NR)
mics6.ch_b1 %>% count(MN2, MN3A)

mics6.ch_b1 %>% 
  unite(ANC_W, c(MN2, MN3A, MN3B), sep = "_", remove = FALSE, na.rm = FALSE) -> mics6.ch_b1

mics6.ch_b1 %>% replace_with_na(replace = list(ANC_W = "NA_NA_NA")) -> mics6.ch_b1
mics6.ch_b1 %>% replace_with_na(replace = list(ANC_W = "NA__")) -> mics6.ch_b1


mics6.ch_b1 %>% mutate(ANC_W = recode(ANC_W,
                                     "1_?_?" = 3,
                                     "1__" = 3,
                                     "1__B" = 2,
                                     "1_A_" = 1,
                                     "1_A_B" = 1,
                                     "2__" = 0,
                                     "9__" = 0)) -> mics6.ch_b1
mics6.ch_b1 %>% count(ANC_W)


```


```{r changing to factor}
# changing variables into factors


# data b1
mics6.ch_b1$hh7r <- as.factor(mics6.ch_b1$hh7r)
mics6.ch_b1$HH7R <- as.factor(mics6.ch_b1$HH7R)
mics6.ch_b1$HH6 <- as.factor(mics6.ch_b1$HH6)
mics6.ch_b1$windex5 <- as.factor(mics6.ch_b1$windex5)
mics6.ch_b1$HL4 <- as.factor(mics6.ch_b1$HL4)
mics6.ch_b1$ethnicity <- as.factor(mics6.ch_b1$ethnicity)
mics6.ch_b1$melevel <- as.factor(mics6.ch_b1$melevel)
mics6.ch_b1$ethnicity_r <- as.factor(mics6.ch_b1$ethnicity_r)
mics6.ch_b1$melevel_r <- as.factor(mics6.ch_b1$melevel_r)
mics6.ch_b1$PoB <- as.factor(mics6.ch_b1$PoB)
mics6.ch_b1$ANC <- as.factor(mics6.ch_b1$ANC)
mics6.ch_b1$ANC_W <- as.factor(mics6.ch_b1$ANC_W)
mics6.ch_b1$ANC_T <- as.factor(mics6.ch_b1$ANC_T)
mics6.ch_b1$year <- as.factor(mics6.ch_b1$year)
mics6.ch_b1$AGE <- as.factor(mics6.ch_b1$AGE)

mics6.ch_b1$hepb0_RC_2 <- as.factor(mics6.ch_b1$hepb0_RC_2)
mics6.ch_b1$hepb0_RC_24 <- as.factor(mics6.ch_b1$hepb0_RC_24)
mics6.ch_b1$hepb0_C_2 <- as.factor(mics6.ch_b1$hepb0_C_2)
mics6.ch_b1$hepb0_C_24 <- as.factor(mics6.ch_b1$hepb0_C_24)
mics6.ch_b1$hepb0_R_2 <- as.factor(mics6.ch_b1$hepb0_R_2)
mics6.ch_b1$hepb0_R_24 <- as.factor(mics6.ch_b1$hepb0_R_24)
```


## mics4_6_b1
```{r bind rows b1}

mics4_6_b1 <- bind_rows(mics4.ch_b1, mics6.ch_b1)

sjPlot::view_df(mics4_6_b1)


mics4_6_b1 %>% count(UF8Y, UF7Y)
mics4_6_b1 %>% count(HH7R, hh7r)
mics4_6_b1 %>% count(HH6)
mics4_6_b1 %>% count(ethnicity)
mics4_6_b1 %>% count(melevel)
mics4_6_b1 %>% count(windex5)
mics4_6_b1 %>% count(HL4)
mics4_6_b1 %>% count(AGE)
mics4_6_b1 %>% count(year)
mics4_6_b1 %>% count(HH_id)

mics4_6_b1 %>% count(PoB)
mics4_6_b1 %>% count(ANC)
mics4_6_b1 %>% count(ANC_W)
mics4_6_b1 %>% count(ANC_T)

mics4_6_b1 %>% count(hepb0_RC_2)
mics4_6_b1 %>% count(hepb0_RC_24)
mics4_6_b1 %>% count(hepb0_R_2)
mics4_6_b1 %>% count(hepb0_R_24)
mics4_6_b1 %>% count(hepb0_C_2)
mics4_6_b1 %>% count(hepb0_C_24)




```


### Survey design b1


```{r survey design}
# Make design for hepb0 with selected children aged under 3: n = 13460

mics_design_4_6_b1 <- svydesign(data = mics4_6_b1, 
                         weights = ~chweight, 
                         id = ~strata+HH1)


```

# Analysis over time B1


```{r dependent over time}

summ(svyglm(hepb0_RC_2 ~year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)

svytable(~ethnicity + HH7R, design = mics_design_4_6_b1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=ethnicity, y=Freq, fill = HH7R)) +
  geom_col(position = "fill") 

svytable(~year + hepb0_RC_1, design = mics_design_4_6_b1) -> tab
tab <- as.data.frame(tab)
plot <- ggplot(data = tab, mapping = aes(x=year, y=Freq, fill = hepb0_RC_1)) +
  geom_col(position = "fill") +
  labs(y= "Percentage", x = "Year") +
  labs(title = "Vaccination coverage rate") +
  labs(fill = "BD") +
  scale_fill_discrete(labels = c("No", "Yes, within 24 hrs", "Yes, later")) +
  scale_y_continuous(labels=percent)
print(plot)
ggsave("plot.png", width = 8, height = 8, units = "cm")


```

```{r plot independent over years}

plot <- ggplot(data = tab, mapping = aes(x=year, y=hepb0_RC_2, group = melevel_r, color = melevel_r)) +
  geom_point() + geom_line()
print(plot)

  labs(y= "Percentage", x = "Year") +
  labs(title = "Vaccination covarage rate") +
  labs(fill = "BD") +
  scale_fill_discrete(labels = c("No", "Yes")) +
  scale_y_continuous(labels=percent)



ggsave("plot.png")
ggsave("plot2.png", width = 8, height = 8, units = "cm")

```



```{r hepb0 independent over years}



summ(svyglm(hepb0_RC_2 ~HH6, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_2 ~HH7R, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_2 ~windex5, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_2 ~HL4, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_2 ~ethnicity, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_2 ~melevel, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_2 ~ethnicity_r, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_2 ~melevel_r, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_2 ~PoB, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_2 ~ANC, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_2 ~ANC_W, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_2 ~ANC_T, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)


# with year as factor and interaction

summ(svyglm(hepb0_RC_2 ~HH6 + year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_2 ~HH6 + year + HH6*year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(hepb0_RC_2 ~HH7R + year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_2 ~HH7R + year + HH7R*year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(hepb0_RC_2 ~windex5 + year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_2 ~windex5 + year + windex5*year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(hepb0_RC_2 ~HL4 + year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_2 ~HL4 + year + HL4*year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(hepb0_RC_2 ~melevel + year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_2 ~melevel + year +melevel*year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(hepb0_RC_2 ~ethnicity_r + year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_2 ~ethnicity_r + year + ethnicity_r*year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(hepb0_RC_2 ~melevel_r + year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_2 ~melevel_r + year + melevel_r*year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(hepb0_RC_2 ~PoB  + year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_2 ~PoB + year + PoB*year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(hepb0_RC_2 ~ANC  + year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_2 ~ANC + year + ANC*year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(hepb0_RC_2 ~ANC_W + year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_2 ~ANC_W + year + ANC_W*year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(hepb0_RC_2 ~ANC_T + year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_2 ~ANC_T + year + ANC_T*year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)



```

```{r hepbo within 24 hours over years}

#hep0 within 24 hours
summ(svyglm(hepb0_RC_24 ~year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)

# hepb0 within 24 hours

#hep0 within 24 hours
summ(svyglm(hepb0_RC_24 ~HH6, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_24 ~HH7R, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_24 ~windex5, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_24 ~HL4, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_24 ~ethnicity, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_24 ~melevel, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_24 ~ethnicity_r, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_24 ~melevel_r, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_24 ~PoB, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_24 ~ANC, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_24 ~ANC_W, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

# with year as factor and interaction

summ(svyglm(hepb0_RC_24 ~HH6 + year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_24 ~HH6 + year + HH6*year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(hepb0_RC_24 ~HH7R + year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_24 ~HH7R + year + HH7R*year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(hepb0_RC_24 ~windex5 + year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_24 ~windex5 + year + windex5*year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(hepb0_RC_24 ~HL4 + year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_24 ~HL4 + year + HL4*year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(hepb0_RC_24 ~melevel + year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_24 ~melevel + year +melevel*year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(hepb0_RC_24 ~ethnicity_r + year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_24 ~ethnicity_r + year + ethnicity_r*year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(hepb0_RC_24 ~melevel_r + year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_24 ~melevel_r + year + melevel_r*year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(hepb0_RC_24 ~PoB  + year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_24 ~PoB + year + PoB*year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(hepb0_RC_24 ~ANC  + year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_24 ~ANC + year + ANC*year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(hepb0_RC_24 ~ANC_W + year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_24 ~ANC_W + year + ANC_W*year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(hepb0_RC_24 ~ANC_T + year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(hepb0_RC_24 ~ANC_T + year + ANC_T*year, design = mics_design_4_6_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

```


```{r plot interactions hepb0}


A <- svyglm(hepb0_RC_2 ~melevel_r + year + melevel_r*year, design = mics_design_4_6_b1, family = quasibinomial())
summ(A,  exp = TRUE, confint = TRUE, digits = 2)

B <-  svyglm(hepb0_RC_2 ~HH6 + year + HH6*year, design = mics_design_4_6_b1, family = quasibinomial())
summ(B,  exp = TRUE, confint = TRUE, digits = 2)

C <- svyglm(hepb0_RC_2 ~windex5 + year + windex5*year, design = mics_design_4_6_b1, family = quasibinomial())
summ(C,  exp = TRUE, confint = TRUE, digits = 2)

D <- svyglm(hepb0_RC_2 ~melevel + year +melevel*year, design = mics_design_4_6_b1, family = quasibinomial())
summ(D,  exp = TRUE, confint = TRUE, digits = 2)

E <- svyglm(hepb0_RC_2 ~ethnicity_r + year + ethnicity_r*year, design = mics_design_4_6_b1, family = quasibinomial())
summ(E,  exp = TRUE, confint = TRUE, digits = 2)

F <- svyglm(hepb0_RC_2 ~PoB + year + PoB*year, design = mics_design_4_6_b1, family = quasibinomial())
summ(E,  exp = TRUE, confint = TRUE, digits = 2)

G <- svyglm(hepb0_RC_2 ~ANC + year + ANC*year, design = mics_design_4_6_b1, family = quasibinomial())
summ(E,  exp = TRUE, confint = TRUE, digits = 2)

H <- svyglm(hepb0_RC_2 ~ANC_W + year + ANC_W*year, design = mics_design_4_6_b1, family = quasibinomial())
summ(E,  exp = TRUE, confint = TRUE, digits = 2)

I <- svyglm(hepb0_RC_2 ~ANC_T + year + ANC_T*year, design = mics_design_4_6_b1, family = quasibinomial())
summ(E,  exp = TRUE, confint = TRUE, digits = 2)



plotA <- plot_model(A, type = "pred", terms = c("year", "melevel_r"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate BD", x = "year") +
  labs(title = "mother's education level * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("none", "primary", "secundary or higher")) +
  theme(legend.position="bottom")
print(plotA)
ggsave("plotA.png")


plotB <- plot_model(B, type = "pred", terms = c("year", "HH6"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate BD", x = "year") +
  labs(title = "area * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("urban", "rural with road", "rural without road")) +
  theme(legend.position="bottom")
print(plotB)
ggsave("plotB.png")

plotC <- plot_model(C, type = "pred", terms = c("year", "windex5"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate BD", x = "year") +
  labs(title = "wealth index quintile * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("poorest", "second", "third", "fourth", "richest")) +
  theme(legend.position="bottom")
print(plotC)
ggsave("plotC.png")

plotD <- plot_model(D, type = "pred", terms = c("year", "melevel"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate BD", x = "year") +
  labs(title = "mother's education level * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("none", "primary", "lower secondary",  "upper secondary", "post-secondary", "higher")) +
  theme(legend.position="bottom")
print(plotD)
ggsave("plotD.png")

plotE <- plot_model(E, type = "pred", terms = c("year", "ethnicity_r"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate BD", x = "year") +
  labs(title = "ethnicity * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("Lao-Thai", "Mon-Khmer", "Hmong-Mien", "other")) +
  theme(legend.position="bottom")
print(plotE)
ggsave("plotE.png")


plotF <- plot_model(F, type = "pred", terms = c("year", "PoB"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate BD", x = "year") +
  labs(title = "place of birth * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("home", "public hospital", "other")) +
  theme(legend.position="bottom")
print(plotF)
ggsave("plotF.png")

plotG <- plot_model(G, type = "pred", terms = c("year", "ANC"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate BD", x = "year") +
  labs(title = "antenatal care * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("no", "yes")) +
  theme(legend.position="bottom")
print(plotG)
ggsave("plotG.png")


plotH <- plot_model(H, type = "pred", terms = c("year", "ANC_W"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate BD", x = "year") +
  labs(title = "antenatal care giver * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("no one", "doctor", "nurse/midwife", "other")) +
  theme(legend.position="bottom")
print(plotH)
ggsave("plotH.png")


plotI <- plot_model(I, type = "pred", terms = c("year", "ANC_T"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate BD", x = "year") +
  labs(title = "ANC times * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("1-3", "4-6", "7 or more")) +
  theme(legend.position="bottom")
print(plotI)
ggsave("plotI.png")




```

```{r plot interactions hepb0 within 24 hours}


A <- svyglm(hepb0_RC_24 ~melevel_r + year + melevel_r*year, design = mics_design_4_6_b1, family = quasibinomial())
summ(A,  exp = TRUE, confint = TRUE, digits = 2)

B <- svyglm(hepb0_RC_24 ~HH6 + year + HH6*year, design = mics_design_4_6_b1, family = quasibinomial())
summ(B,  exp = TRUE, confint = TRUE, digits = 2)

C <- svyglm(hepb0_RC_24 ~windex5 + year + windex5*year, design = mics_design_4_6_b1, family = quasibinomial())
summ(C,  exp = TRUE, confint = TRUE, digits = 2)

D <- svyglm(hepb0_RC_24 ~melevel + year +melevel*year, design = mics_design_4_6_b1, family = quasibinomial())
summ(D,  exp = TRUE, confint = TRUE, digits = 2)

E <- svyglm(hepb0_RC_24 ~ethnicity_r + year + ethnicity_r*year, design = mics_design_4_6_b1, family = quasibinomial())
summ(E,  exp = TRUE, confint = TRUE, digits = 2)

F <- svyglm(hepb0_RC_24 ~PoB + year + PoB*year, design = mics_design_4_6_b1, family = quasibinomial())
summ(E,  exp = TRUE, confint = TRUE, digits = 2)

G <- svyglm(hepb0_RC_24 ~ANC + year + ANC*year, design = mics_design_4_6_b1, family = quasibinomial())
summ(E,  exp = TRUE, confint = TRUE, digits = 2)

H <- svyglm(hepb0_RC_24 ~ANC_W + year + ANC_W*year, design = mics_design_4_6_b1, family = quasibinomial())
summ(E,  exp = TRUE, confint = TRUE, digits = 2)

I <- svyglm(hepb0_RC_24 ~ANC_T + year + ANC_T*year, design = mics_design_4_6_b1, family = quasibinomial())
summ(E,  exp = TRUE, confint = TRUE, digits = 2)

plot24A <- plot_model(A, type = "pred", terms = c("year", "melevel_r"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate BD", x = "year") +
  labs(title = "mother's education level * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("none", "primary", "secundary or higher")) +
  theme(legend.position="bottom")
print(plot24A)
ggsave("plot24A.png")


plot24B <- plot_model(B, type = "pred", terms = c("year", "HH6"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate BD", x = "year") +
  labs(title = "area * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("urban", "rural with road", "rural without road")) +
  theme(legend.position="bottom")
print(plot24B)
ggsave("plot24B.png")

plot24C <- plot_model(C, type = "pred", terms = c("year", "windex5"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate BD", x = "year") +
  labs(title = "wealth index quintile * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("poorest", "second", "third", "fourth", "richest")) +
  theme(legend.position="bottom")
print(plot24C)
ggsave("plot24C.png")

plot24D <- plot_model(D, type = "pred", terms = c("year", "melevel"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate BD", x = "year") +
  labs(title = "mother's education level * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("none", "primary", "lower secondary",  "upper secondary", "post-secondary", "higher")) +
  theme(legend.position="bottom")
print(plot24D)
ggsave("plot24D.png")

plot24E <- plot_model(E, type = "pred", terms = c("year", "ethnicity_r"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate BD", x = "year") +
  labs(title = "ethnicity * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("Lao-Thai", "Mon-Khmer", "Hmong-Mien", "other")) +
  theme(legend.position="bottom")
print(plot24E)
ggsave("plot24E.png")


plot24F <- plot_model(F, type = "pred", terms = c("year", "PoB"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate BD", x = "year") +
  labs(title = "place of birth * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("home", "public hospital", "other")) +
  theme(legend.position="bottom")
print(plot24F)
ggsave("plot24F.png")

plot24G <- plot_model(G, type = "pred", terms = c("year", "ANC"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate BD", x = "year") +
  labs(title = "antenatal care * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("no", "yes")) +
  theme(legend.position="bottom")
print(plot24G)
ggsave("plot24G.png")


plot24H <- plot_model(H, type = "pred", terms = c("year", "ANC_W"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate BD", x = "year") +
  labs(title = "antenatal care giver * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("no one", "doctor", "nurse/midwife", "other")) +
  theme(legend.position="bottom")
print(plot24H)
ggsave("plot24H.png")


plot24I <- plot_model(I, type = "pred", terms = c("year", "ANC_T"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate BD", x = "year") +
  labs(title = "ANC times * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("1-3", "4-6", "7 or more")) +
  theme(legend.position="bottom")
print(plot24I)
ggsave("plot24I.png")


```

# P1

## subset 4 p1

```{r mics4.ch_p1}

mics4.ch_b1 %>% filter(CAGED > 365) -> mics4.ch_p1


```

### New variables

```{r pentavalent 1}



# Penta 1 Only Card

mics4.ch_p1 %>% count(IM3H1D)

#change date variables into categorical variables
mics4.ch_p1 %>% mutate(penta1_C = if_else(IM3H1D <= 31 & IM3H1D >=1, 1,
                                        if_else(IM3H1D == 0, 0,
                                        if_else(IM3H1D == 44, 44,
                                        if_else(IM3H1D == 99, 99, 66))))) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_C)

mics4.ch_p1 %>% 
  mutate(penta1_C = recode(penta1_C,
                           "44" = "1",
                           "66" = "66",
                           "99" = "0",
                           "1" = "1",
                           "0" = "0"
                           )) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_C)

# 66 needs to be replaced with NA because this is recall info and not card info
# penta1_C_1: only card variable
mics4.ch_p1$penta1_C_1 <- mics4.ch_p1$penta1_C
mics4.ch_p1 %>% replace_with_na(replace = list(penta1_C_1 = "66")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_C_1)


# Penta 1 only recall



# First recode IM11 into penta1_R: recall variable

mics4.ch_p1 %>% count(IM11)
mics4.ch_p1$IM11_2 <- as.factor(mics4.ch_p1$IM11)

mics4.ch_p1 %>% 
  mutate(penta1_R = recode(IM11_2,
                           "1" = "R_1",
                           "2" = "R_0",
                           "8" = "R_8")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_R)

mics4.ch_p1 %>% count(penta1_R, IM5, IM6, penta1_C)
mics4.ch_p1 %>% count(IM6, penta1_C)


# It is not yet correct
# In IM6; if all responses were "NO"; there was no probing for the recall of vaccinations
# Therefore; some of the NAs in the new variable need to be changed to "No" or "DK" #564 no and #11 DK and 3 missing


mics4.ch_p1 %>% 
  mutate(penta1_R = replace(penta1_R, is.na(penta1_R) & IM6 == 2, "R_0"))  %>%
  mutate(penta1_R = replace(penta1_R, is.na(penta1_R) & IM6 == 8, "R_8")) %>%
  mutate(penta1_R = replace(penta1_R, is.na(penta1_R) & IM6 == 9, "R_0")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_R)


# combine Recall and Card

mics4.ch_p1 %>% count(penta1_R, penta1_C)
mics4.ch_p1 %>% mutate(penta1_RC = coalesce(penta1_R, penta1_C)) -> mics4.ch_p1 
mics4.ch_p1 %>% count(penta1_RC)

# Now, all responses should be categorized correctly !!!
# Except for R_8 -> R_0 # and 66 -> which should be categorized as recall, mother reported that there was a vaccination but not sure whether within 24 hours 

mics4.ch_p1 %>% 
  mutate(penta1_R_1 = recode(penta1_RC,
                            "66" = "R_1",
                           "R_0" = "R_0",
                           "R_1" = "R_1",
                           "R_8" = "R_0"
                           )) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_R_1)

# all outcomes from card RC need to be replaced with NA to only retain recall
mics4.ch_p1 %>% replace_with_na(replace = list(penta1_R_1 = c("0", "1"))) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_R_1)

# combination recall and card
mics4.ch_p1 %>%
  mutate(penta1_RC_1 = recode(penta1_RC,
                              "0" = 0,
                              "1" = 1,
                              "66" = 1,
                              "R_0" = 0,
                              "R_1" = 1,
                              "R_8" = 0
                              )) -> mics4.ch_p1

mics4.ch_p1 %>% count(penta1_RC_1) # 0: 940 1: 3374
mics4.ch_p1 %>% count(penta1_R_1) # 0: 867 1: 1605
mics4.ch_p1 %>% count(penta1_C_1) # 0: 73 1: 1769

# new variables



```

```{r pentavalent 2}


# Penta 2 Only Card

mics4.ch_p1 %>% count(IM3H2D)

#change date variables into categorical variables
mics4.ch_p1 %>% mutate(penta2_C = if_else(IM3H2D <= 31 & IM3H2D >=1, 1,
                                        if_else(IM3H2D == 0, 0,
                                        if_else(IM3H2D == 44, 44,
                                        if_else(IM3H2D == 99, 99, 66))))) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_C)

mics4.ch_p1 %>% 
  mutate(penta2_C = recode(penta2_C,
                           "44" = "1",
                           "66" = "66",
                           "99" = "0",
                           "1" = "1",
                           "0" = "0"
                           )) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_C)

# 66 needs to be replaced with NA because this is recall info and not card info
# penta2_C_1: only card variable
mics4.ch_p1$penta2_C_1 <- mics4.ch_p1$penta2_C
mics4.ch_p1 %>% replace_with_na(replace = list(penta2_C_1 = "66")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_C_1)


# Penta 2 only recall



# First recode IM11 into penta2_R: recall variable

mics4.ch_p1 %>% count(IM12)
mics4.ch_p1$IM12_2 <- as.numeric(mics4.ch_p1$IM12)

mics4.ch_p1 %>% 
  mutate(penta2_R = recode(IM12_2,
                           "1" = "R_1",
                           "2" = "R_2",
                           "3" = "R_3",
                           "4" = "R_4",
                           "5" = "R_5",
                           "6" = "R_6",
                           "7" = "R_7",
                           "8" = "R_8",
                           "9" = "R_9")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_R)

# mics4.ch_p1 %>% count(penta2_R, IM5, IM6, penta2_C)
# mics4.ch_p1 %>% count(IM6, penta2_C)

# It is not yet correct
# In IM6; if all responses were "NO"; there was no probing for the recall of vaccinations
# Therefore; some of the NAs in the new variable need to be changed to "No" or "DK" #564 no and #11 DK and 3 missing


mics4.ch_p1 %>% 
  mutate(penta2_R = replace(penta2_R, is.na(penta2_R) & IM6 == 2, "R_0"))  %>%
  mutate(penta2_R = replace(penta2_R, is.na(penta2_R) & IM6 == 8, "R_8")) %>%
  mutate(penta2_R = replace(penta2_R, is.na(penta2_R) & IM6 == 9, "R_9")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_R) 
mics4.ch_p1 %>% count(penta1_R)


# make a new variable combining IM20 and IM21. 
# IM 21: 2,3,4,5,6 of 7 means having the second pentavalent vaccine, IM21: 1,8 or 9 had only one or dont know whether they had one pentavalent vaccine or more, therefore do not include them assign to 0 together with IM20 No and DK = penta1_R.

mics4.ch_p1 %>% count(penta2_R, penta1_R)
mics4.ch_p1 %>% mutate(penta2_R_3 = coalesce(penta2_R, penta1_R)) -> mics4.ch_p1 
mics4.ch_p1 %>% count(penta2_R_3)

# Recode recall variable penta 2 into yes or no

mics4.ch_p1 %>% 
  mutate(penta2_R_2 = recode(penta2_R_3,
                           "R_0" = "R_0",
                           "R_1" = "R_0",
                           "R_2" = "R_1",
                           "R_3" = "R_1",
                           "R_4" = "R_1",
                           "R_5" = "R_1",
                           "R_6" = "R_1",
                           "R_7" = "R_1",
                           "R_8" = "R_0",
                           "R_9" = "R_0"
                           )) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_R_2)

# combine Recall and Card

mics4.ch_p1 %>% mutate(penta2_RC = coalesce(penta2_R_2, penta2_C)) -> mics4.ch_p1 
mics4.ch_p1 %>% count(penta2_RC)

# Now, all responses should be categorized correctly !!!
# Except for R_8 -> R_0 # and 66 -> which should be categorized as recall, mother reported that there was a vaccination but not sure whether within 24 hours 

mics4.ch_p1 %>% 
  mutate(penta2_R_1 = recode(penta2_RC,
                            "66" = "R_1",
                           "R_0" = "R_0",
                           "R_1" = "R_1")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_R_1)

# all outcomes from card RC need to be replaced with NA to only retain recall
mics4.ch_p1 %>% replace_with_na(replace = list(penta2_R_1 = c("0", "1"))) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_R_1)

# combination recall and card
mics4.ch_p1 %>%
  mutate(penta2_RC_1 = recode(penta2_RC,
                              "0" = 0,
                              "1" = 1,
                              "66" = 1,
                              "R_0" = 0,
                              "R_1" = 1)) -> mics4.ch_p1

mics4.ch_p1 %>% count(penta2_RC_1) # 0: 1360 1: 2954
mics4.ch_p1 %>% count(penta2_R_1) # 0: 1186 1: 1298
mics4.ch_p1 %>% count(penta2_C_1) # 0: 174 1: 1656


```

```{r pentavalent 3}


# Penta 3 Only Card

mics4.ch_p1 %>% count(IM3H3D)

#change date variables into categorical variables
mics4.ch_p1 %>% mutate(penta3_C = if_else(IM3H3D <= 31 & IM3H3D >=1, 1,
                                        if_else(IM3H3D == 0, 0,
                                        if_else(IM3H3D == 44, 44,   
                                        if_else(IM3H3D == 66, 66, 99))))) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta3_C)

mics4.ch_p1 %>% 
  mutate(penta3_C = recode(penta3_C,
                           "44" = "1",
                           "66" = "66",
                           "99" = "0",
                           "1" = "1",
                           "0" = "0"
                           )) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta3_C)

# 66 needs to be replaced with NA because this is recall info and not card info

mics4.ch_p1$penta3_C_1 <- mics4.ch_p1$penta3_C
mics4.ch_p1 %>% replace_with_na(replace = list(penta3_C_1 = "66")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta3_C_1)


# Penta 2 only recall

mics4.ch_p1 %>% count(IM11, IM12, IM5, IM6)
mics4.ch_p1 %>% count(IM11, IM12, IM6)




# First recode IM12 into penta3_R: recall variable

mics4.ch_p1 %>% count(IM12)
mics4.ch_p1 %>% 
  mutate(penta3_R = recode(IM12,
                           "1" = "R_1",
                           "2" = "R_2",
                           "3" = "R_3",
                           "4" = "R_4",
                           "5" = "R_5",
                           "6" = "R_6",
                           "7" = "R_7",
                           "8" = "R_8",
                           "9" = "R_9")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta3_R)


mics4.ch_p1 %>% count(penta3_R, IM11, IM5, IM6)

# It is not yet correct
# In IM11 & IM12; if all responses were "NO"; there was no probing for the recall of vaccinations
# Therefore; some of the NAs in the new variable need to be changed to "No" or "DK" #564 no and #11 DK and # 3 missing values. 

mics4.ch_p1 %>% 
  mutate(penta3_R = replace(penta3_R, is.na(penta3_R) & IM6 == 2, "R_0"))  %>%
  mutate(penta3_R = replace(penta3_R, is.na(penta3_R) & IM6 == 8, "R_8")) %>%
  mutate(penta3_R = replace(penta3_R, is.na(penta3_R) & IM6 == 9, "R_9"))-> mics4.ch_p1
 mics4.ch_p1 %>% count(penta3_R)


# make a new variable combining IM11 and IM12. 
# IM 21: 2,3,4,5,6 of 7 means having the second pentavalent vaccine, IM21: 1,8 or 9 had only one or dont know whether they had one pentavalent vaccine or more, therefore do not include them assign to 0 together with IM20 No and DK.
mics4.ch_p1 %>% count(penta3_R, penta1_R)
mics4.ch_p1 %>% mutate(penta3_R_3 = coalesce(penta3_R, penta1_R)) -> mics4.ch_p1 
mics4.ch_p1 %>% count(penta3_R_3)

# Recode recall variable penta3 into yes or no

mics4.ch_p1 %>% 
  mutate(penta3_R_2 = recode(penta3_R_3,
                           "R_0" = "R_0",
                           "R_1" = "R_0",
                           "R_2" = "R_0",
                           "R_3" = "R_1",
                           "R_4" = "R_1",
                           "R_5" = "R_1",
                           "R_6" = "R_1",
                           "R_7" = "R_1",
                           "R_8" = "R_0",
                           "R_9" = "R_0"
                           )) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta3_R_2)


# combine Recall and Card

mics4.ch_p1 %>% mutate(penta3_RC = coalesce(penta3_R_2, penta3_C)) -> mics4.ch_p1 
mics4.ch_p1 %>% count(penta3_RC)

# Now, all responses should be categorized correctly!
# Except for 66 -> which should be categorized as recall (R_1), mother reported that there was a vaccination 

mics4.ch_p1 %>% 
  mutate(penta3_R_1 = recode(penta3_RC,
                            "66" = "R_1",
                           "R_0" = "R_0",
                           "R_1" = "R_1"                                                       )) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta3_R_1)

# all outcomes from card RC need to be replaced with NA to only retain recall
mics4.ch_p1 %>% replace_with_na(replace = list(penta3_R_1 = c("0", "1"))) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta3_R_1)



# categorize combination recall and card into dichotomous variable
mics4.ch_p1 %>%
  mutate(penta3_RC_1 = recode(penta3_RC,
                              "0" = 0,
                              "1" = 1,
                              "66" = 1,
                              "R_0" = 0,
                              "R_1" = 1
                                       )) -> mics4.ch_p1

mics4.ch_p1 %>% count(penta3_RC_1) # 0: 1893 1: 2421
mics4.ch_p1 %>% count(penta3_R_1) # 0: 1552 1: 955
mics4.ch_p1 %>% count(penta3_C_1) # 0: 341  1: 1466





```

```{r penta 123}

# check if they got all 3 vaccinations, not only second or third. 

mics4.ch_p1 %>% count(penta1_R_1, penta2_R_1, penta3_R_1)
mics4.ch_p1 %>% count(penta1_C_1, penta2_C_1, penta3_C_1, penta1_C)
mics4.ch_p1 %>% count(penta1_RC_1, penta2_RC_1, penta3_RC_1)
mics4.ch_p1 %>% count(penta1_R_1, penta2_R_1, penta3_R_1, penta2_RC, penta3_RC)



# new variables at least one vaccine

# new variable penta1 got at least one vaccinations according to card
mics4.ch_p1 %>% mutate(penta1_C = if_else(penta1_C_1 == 1 | penta2_C_1 == 1 | penta3_C_1 == 1, 1, 0)) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_C)

# new variable penta1 got at least one vaccinations according to card or recall
mics4.ch_p1 %>% mutate(penta1_RC = if_else(penta1_RC_1 == 1 | penta2_RC_1 == 1 | penta3_RC_1 == 1, 1, 0)) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_RC)


mics4.ch_p1$penta1_R <- mics4.ch_p1$penta1_R_1


mics4.ch_p1 %>% count(penta1_RC)
mics4.ch_p1 %>% count(penta1_R) 
mics4.ch_p1 %>% count(penta1_C)

# new variable penta12 got at least two vaccinations according to card
mics4.ch_p1 %>% mutate(penta12_C = if_else(penta1_C_1 == 1 & penta2_C_1 == 1, 1,
                                   if_else(penta1_C_1 == 1 & penta3_C_1 == 1, 1,
                                   if_else(penta2_C_1 == 1 & penta3_C_1 == 1, 1, 0)))) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta12_C)

# new variable penta12 got at least two vaccinations according to card or recall
mics4.ch_p1 %>% mutate(penta12_RC = if_else(penta1_RC_1 == 1 & penta2_RC_1 == 1, 1,
                                    if_else(penta1_RC_1 == 1 & penta3_RC_1 == 1, 1,
                                    if_else(penta2_RC_1 == 1 & penta3_RC_1 == 1, 1, 0)))) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta12_RC)

# change name recall at least two 
mics4.ch_p1$penta12_R <- mics4.ch_p1$penta2_R_1


mics4.ch_p1 %>% count(penta12_RC)
mics4.ch_p1 %>% count(penta12_R) 
mics4.ch_p1 %>% count(penta12_C)

# new variable penta123 got at least three vaccinations according to card
mics4.ch_p1 %>% mutate(penta123_C = if_else(penta1_C_1 == 1 & penta2_C_1 == 1 & penta3_C_1 == 1, 1, 0)) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta123_C)

# new variable penta123 got at least three vaccinations according to card or recall
mics4.ch_p1 %>% mutate(penta123_RC = if_else(penta1_RC_1 == 1 & penta2_RC_1 == 1 & penta3_RC_1 == 1, 1, 0)) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta123_RC)

# change names
mics4.ch_p1$penta123_R <- mics4.ch_p1$penta3_R_1

mics4.ch_p1 %>% count(penta123_RC)
mics4.ch_p1 %>% count(penta123_R) 
mics4.ch_p1 %>% count(penta123_C)

```

```{r changing to factor}
# changing variables into factors


mics4.ch_p1$penta1_RC <- as.factor(mics4.ch_p1$penta1_RC)
mics4.ch_p1$penta12_RC <- as.factor(mics4.ch_p1$penta12_RC)
mics4.ch_p1$penta123_RC <- as.factor(mics4.ch_p1$penta123_RC)

mics4.ch_p1$penta1_C <- as.factor(mics4.ch_p1$penta1_C)
mics4.ch_p1$penta12_C <- as.factor(mics4.ch_p1$penta12_C)
mics4.ch_p1$penta123_C <- as.factor(mics4.ch_p1$penta123_C)

mics4.ch_p1$penta1_R <- as.factor(mics4.ch_p1$penta1_R)
mics4.ch_p1$penta12_R <- as.factor(mics4.ch_p1$penta12_R)
mics4.ch_p1$penta123_R <- as.factor(mics4.ch_p1$penta123_R)


```

## subset 6 p1

```{r mics6.ch_p1}

mics6.ch_b1 %>% filter(UB2 >= 1) -> mics6.ch_p1

```

### new variables



```{r pentavalent 1}



# penta 1 Only Card

mics6.ch_p1 %>% count(IM6PENTA1D)

#change date variables into categorical variables
mics6.ch_p1 %>% mutate(penta1_C = if_else(IM6PENTA1D <= 31 & IM6PENTA1D >=1, 1,
                                        if_else(IM6PENTA1D == 0, 0,
                                        if_else(IM6PENTA1D == 44, 44, 66)))) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta1_C)

mics6.ch_p1 %>% 
  mutate(penta1_C = recode(penta1_C,
                           "44" = "1",
                           "66" = "66",
                           "1" = "1",
                           "0" = "0"
                           )) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta1_C)

# 66 needs to be replaced with NA because this is recall info and not card info

mics6.ch_p1$penta1_C_1 <- mics6.ch_p1$penta1_C
mics6.ch_p1 %>% replace_with_na(replace = list(penta1_C_1 = "66")) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta1_C_1)


# penta 1 only recall



mics6.ch_p1 %>% count(IM20, IM11, IM11_2, IM11_IM12)




# First recode IM20 into penta1_R: recall variable

mics6.ch_p1 %>% count(IM20)
mics6.ch_p1 %>% 
  mutate(penta1_R = recode(IM20,
                           "1" = "R_1",
                           "2" = "R_0",
                           "8" = "R_8",
                           "9" = "R_9")) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta1_R)


# mics6.ch_p1 %>% count(penta1_R, IM11, IM11_2, IM11_IM12)

# It is not yet correct
# In IM11 & IM12; if all responses were "NO"; there was no probing for the recall of vaccinations
# Therefore; soome of the NAs in the new variable need to be changed to "No" or "DK" #810 no and #24 DK

mics6.ch_p1 %>% 
  mutate(penta1_R = replace(penta1_R, is.na(penta1_R) & IM11 == 2, "R_0"))  %>%
  mutate(penta1_R = replace(penta1_R, is.na(penta1_R) & 
                               IM11 == 8, "R_8")) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta1_R)


# combine Recall and Card

mics6.ch_p1 %>% count(penta1_R, penta1_C)
mics6.ch_p1 %>% mutate(penta1_RC = coalesce(penta1_R, penta1_C)) -> mics6.ch_p1 
mics6.ch_p1 %>% count(penta1_RC)

# Now, all responses should be categorized correctly !!!
# Except for 44_NA -> 1_Later: Marked on card, not known whether within 24 hrs
# and 66_NA -> which should be categorized as recall, mother reported that there was a vaccination but not sure whether within 24 hours 

mics6.ch_p1 %>% 
  mutate(penta1_R_1 = recode(penta1_RC,
                            "66" = "R_1",
                           "R_0" = "R_0",
                           "R_1" = "R_1",
                           "R_8" = "R_0"
                           )) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta1_R_1)

# all outcomes from card RC need to be replaced with NA to only retain recall
mics6.ch_p1 %>% replace_with_na(replace = list(penta1_R_1 = c("0", "1"))) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta1_R_1)

# combination recall and card
mics6.ch_p1 %>%
  mutate(penta1_RC_1 = recode(penta1_RC,
                              "0" = 0,
                              "1" = 1,
                              "66" = 1,
                              "R_0" = 0,
                              "R_1" = 1,
                              "R_8" = 0
                              )) -> mics6.ch_p1

mics6.ch_p1 %>% count(penta1_RC_1)
mics6.ch_p1 %>% count(penta1_R_1)
mics6.ch_p1 %>% count(penta1_C_1)


```



```{r pentavalent 2}

# penta 2 Only Card

mics6.ch_p1 %>% count(IM6PENTA2D)

#change date variables into categorical variables
mics6.ch_p1 %>% mutate(penta2_C = if_else(IM6PENTA2D <= 31 & IM6PENTA2D >=1, 1,
                                        if_else(IM6PENTA2D == 0, 0,
                                        if_else(IM6PENTA2D == 44, 44, 66)))) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta2_C)

mics6.ch_p1 %>% 
  mutate(penta2_C = recode(penta2_C,
                           "44" = "1",
                           "66" = "66",
                           "1" = "1",
                           "0" = "0"
                           )) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta2_C)

# 66 needs to be replaced with NA because this is recall info and not card info

mics6.ch_p1$penta2_C_1 <- mics6.ch_p1$penta2_C
mics6.ch_p1 %>% replace_with_na(replace = list(penta2_C_1 = "66")) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta2_C_1)


# penta 2 only recall

mics6.ch_p1 %>% count(IM20, IM11, IM11_2, IM11_IM12)




# First recode IM21 into penta2_R: recall variable

mics6.ch_p1 %>% count(IM21)
mics6.ch_p1 %>% 
  mutate(penta2_R = recode(IM21,
                           "1" = "R_1",
                           "2" = "R_2",
                           "3" = "R_3",
                           "4" = "R_4",
                           "5" = "R_5",
                           "6" = "R_6",
                           "7" = "R_7",
                           "8" = "R_8",
                           "9" = "R_9")) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta2_R)


# mics6.ch_p1 %>% count(penta2_R, IM20, IM11, IM11_IM12)

# It is not yet correct
# In IM11 & IM12; if all responses were "NO"; there was no probing for the recall of vaccinations
# Therefore; some of the NAs in the new variable need to be changed to "No" or "DK" #631 no and #38 DK

mics6.ch_p1 %>% 
  mutate(penta2_R = replace(penta2_R, is.na(penta2_R) & IM11 == 2, "R_0"))  %>%
  mutate(penta2_R = replace(penta2_R, is.na(penta2_R) & 
                               IM11 == 8, "R_8")) -> mics6.ch_p1
 mics6.ch_p1 %>% count(penta2_R)


# make a new variable combining IM20 and IM21. 
# IM 21: 2,3,4,5,6 or 7 means having the second pentavalent vaccine, IM21: 1,8 or 9 had only one or dont know whether they had one pentavalent vaccine or more, therefore do not include them assign to 0 together with IM20 No and DK.
 
mics6.ch_p1 %>% count(penta2_R, penta1_R)
mics6.ch_p1 %>% mutate(penta2_R_3 = coalesce(penta2_R, penta1_R)) -> mics6.ch_p1 
mics6.ch_p1 %>% count(penta2_R_3)

# Recode recall variable penta2 into yes or no

mics6.ch_p1 %>% 
  mutate(penta2_R_2 = recode(penta2_R_3,
                           "R_0" = "R_0",
                           "R_1" = "R_0",
                           "R_2" = "R_1",
                           "R_3" = "R_1",
                           "R_4" = "R_1",
                           "R_5" = "R_1",
                           "R_6" = "R_1",
                           "R_7" = "R_1",
                           "R_8" = "R_0",
                           "R_9" = "R_0"
                           )) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta2_R_2)


# combine Recall and Card

mics6.ch_p1 %>% mutate(penta2_RC = coalesce(penta2_R_2, penta2_C)) -> mics6.ch_p1 
mics6.ch_p1 %>% count(penta2_RC)

# Now, all responses should be categorized correctly!
# Except for 66 -> which should be categorized as recall (R_1), mother reported that there was a vaccination 

mics6.ch_p1 %>% 
  mutate(penta2_R_1 = recode(penta2_RC,
                            "66" = "R_1",
                           "R_0" = "R_0",
                           "R_1" = "R_1"                                                       )) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta2_R_1)

# all outcomes from card RC need to be replaced with NA to only retain recall
mics6.ch_p1 %>% replace_with_na(replace = list(penta2_R_1 = c("0", "1"))) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta2_R_1)



# categorize combination recall and card into dichotomous variable
mics6.ch_p1 %>%
  mutate(penta2_RC_1 = recode(penta2_RC,
                              "0" = 0,
                              "1" = 1,
                              "66" = 1,
                              "R_0" = 0,
                              "R_1" = 1
                                       )) -> mics6.ch_p1

mics6.ch_p1 %>% count(penta2_RC_1) # 0: 1734 1: 2806
mics6.ch_p1 %>% count(penta2_R_1) # 0: 1348 1: 1085
mics6.ch_p1 %>% count(penta2_C_1) # 0: 386 1: 1721



```



```{r pentavalent 3}


# penta 3 Only Card

mics6.ch_p1 %>% count(IM6PENTA3D)

#change date variables into categorical variables
mics6.ch_p1 %>% mutate(penta3_C = if_else(IM6PENTA3D <= 31 & IM6PENTA3D >=1, 1,
                                        if_else(IM6PENTA3D == 0, 0,
                                        if_else(IM6PENTA3D == 44, 44, 66)))) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta3_C)

mics6.ch_p1 %>% 
  mutate(penta3_C = recode(penta3_C,
                           "44" = "1",
                           "66" = "66",
                           "1" = "1",
                           "0" = "0"
                           )) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta3_C)

# 66 needs to be replaced with NA because this is recall info and not card info

mics6.ch_p1$penta3_C_1 <- mics6.ch_p1$penta3_C
mics6.ch_p1 %>% replace_with_na(replace = list(penta3_C_1 = "66")) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta3_C_1)


# penta 2 only recall

mics6.ch_p1 %>% count(IM20, IM11, IM11_2, IM11_IM12)




# First recode IM21 into penta3_R: recall variable

mics6.ch_p1 %>% count(IM21)
mics6.ch_p1 %>% 
  mutate(penta3_R = recode(IM21,
                           "1" = "R_1",
                           "2" = "R_2",
                           "3" = "R_3",
                           "4" = "R_4",
                           "5" = "R_5",
                           "6" = "R_6",
                           "7" = "R_7",
                           "8" = "R_8",
                           "9" = "R_9")) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta3_R)


# mics6.ch_p1 %>% count(penta3_R, IM20, IM11, IM11_IM12)

# It is not yet correct
# In IM11 & IM12; if all responses were "NO"; there was no probing for the recall of vaccinations
# Therefore; some of the NAs in the new variable need to be changed to "No" or "DK" #631 no and #38 DK

mics6.ch_p1 %>% 
  mutate(penta3_R = replace(penta3_R, is.na(penta3_R) & IM11 == 2, "R_0"))  %>%
  mutate(penta3_R = replace(penta3_R, is.na(penta3_R) & 
                               IM11 == 8, "R_8")) -> mics6.ch_p1
 mics6.ch_p1 %>% count(penta3_R)


# make a new variable combining IM20 and IM21. 
# IM 21: 2,3,4,5,6 of 7 means having the second pentavalent vaccine, IM21: 1,8 or 9 had only one or dont know whether they had one pentavalent vaccine or more, therefore do not include them assign to 0 together with IM20 No and DK.
mics6.ch_p1 %>% count(penta3_R, penta1_R)
mics6.ch_p1 %>% mutate(penta3_R_3 = coalesce(penta3_R, penta1_R)) -> mics6.ch_p1 
mics6.ch_p1 %>% count(penta3_R_3)

# Recode recall variable penta3 into yes or no

mics6.ch_p1 %>% 
  mutate(penta3_R_2 = recode(penta3_R_3,
                           "R_0" = "R_0",
                           "R_1" = "R_0",
                           "R_2" = "R_0",
                           "R_3" = "R_1",
                           "R_4" = "R_1",
                           "R_5" = "R_1",
                           "R_6" = "R_1",
                           "R_7" = "R_1",
                           "R_8" = "R_0",
                           "R_9" = "R_0"
                           )) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta3_R_2)


# combine Recall and Card

mics6.ch_p1 %>% mutate(penta3_RC = coalesce(penta3_R_2, penta3_C)) -> mics6.ch_p1 
mics6.ch_p1 %>% count(penta3_RC)

# Now, all responses should be categorized correctly!
# Except for 66 -> which should be categorized as recall (R_1), mother reported that there was a vaccination 

mics6.ch_p1 %>% 
  mutate(penta3_R_1 = recode(penta3_RC,
                            "66" = "R_1",
                           "R_0" = "R_0",
                           "R_1" = "R_1"                                                       )) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta3_R_1)

# all outcomes from card RC need to be replaced with NA to only retain recall
mics6.ch_p1 %>% replace_with_na(replace = list(penta3_R_1 = c("0", "1"))) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta3_R_1)



# categorize combination recall and card into dichotomous variable
mics6.ch_p1 %>%
  mutate(penta3_RC_1 = recode(penta3_RC,
                              "0" = 0,
                              "1" = 1,
                              "66" = 1,
                              "R_0" = 0,
                              "R_1" = 1
                                       )) -> mics6.ch_p1

mics6.ch_p1 %>% count(penta3_RC_1) # 0: 2014 1: 2526
mics6.ch_p1 %>% count(penta3_R_1) # 0: 1571 1: 864
mics6.ch_p1 %>% count(penta3_C_1) # 0: 443  1: 1662




```

```{r at least penta 1 2 3}

# check if they got all 3 vaccinations, not only second or third. 


mics6.ch_p1 %>% count(penta1_R_1, penta2_R_1, penta3_R_1)
mics6.ch_p1 %>% count(penta1_C_1, penta2_C_1, penta3_C_1)
mics6.ch_p1 %>% count(penta1_RC_1, penta2_RC_1, penta3_RC_1)
mics6.ch_p1 %>% count(penta1_R_1, penta2_R_1, penta3_R_1, penta2_RC, penta3_RC)


# new variable penta1 got at least one vaccinations according to card
mics6.ch_p1 %>% mutate(penta1_C = if_else(penta1_C_1 == 1 | penta2_C_1 == 1 | penta3_C_1 == 1, 1, 0)) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta1_C)

# new variable penta1 got at least one vaccinations according to card or recall
mics6.ch_p1 %>% mutate(penta1_RC = if_else(penta1_RC_1 == 1 | penta2_RC_1 == 1 | penta3_RC_1 == 1, 1, 0)) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta1_RC)

# change names

mics6.ch_p1$penta1_R <- mics6.ch_p1$penta1_R_1

mics6.ch_p1 %>% count(penta1_RC)
mics6.ch_p1 %>% count(penta1_R) 
mics6.ch_p1 %>% count(penta1_C) 

# new variable penta12 got at least two vaccinations according to card
mics6.ch_p1 %>% mutate(penta12_C = if_else(penta1_C_1 == 1 & penta2_C_1 == 1, 1, 0)) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta12_C)

# new variable penta12 got at least two vaccinations according to card or recall
mics6.ch_p1 %>% mutate(penta12_RC = if_else(penta1_RC_1 == 1 & penta2_RC_1 == 1, 1, 0)) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta12_RC)

# change names
mics6.ch_p1$penta12_R <- mics6.ch_p1$penta2_R_1


mics6.ch_p1 %>% count(penta12_RC)
mics6.ch_p1 %>% count(penta12_R) 
mics6.ch_p1 %>% count(penta12_C) 

# new variable penta123 got at least three vaccinations according to card
mics6.ch_p1 %>% mutate(penta123_C = if_else(penta1_C_1 == 1 & penta2_C_1 == 1 & penta3_C_1 == 1, 1, 0)) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta123_C)

# new variable penta123 got at least three vaccinations according to card or recall
mics6.ch_p1 %>% mutate(penta123_RC = if_else(penta1_RC_1 == 1 & penta2_RC_1 == 1 & penta3_RC_1 == 1, 1, 0)) -> mics6.ch_p1
mics6.ch_p1 %>% count(penta123_RC)

# change names
mics6.ch_p1$penta123_R <- mics6.ch_p1$penta3_R_1

mics6.ch_p1 %>% count(penta123_RC)
mics6.ch_p1 %>% count(penta123_R) 
mics6.ch_p1 %>% count(penta123_C) 


# card + recall
mics6.ch_p1 %>% count(penta1_RC) 
mics6.ch_p1 %>% count(penta12_RC) 
mics6.ch_p1 %>% count(penta123_RC)
# card
mics6.ch_p1 %>% count(penta1_C) 
mics6.ch_p1 %>% count(penta12_C) 
mics6.ch_p1 %>% count(penta123_C)
#recall
mics6.ch_p1 %>% count(penta1_R) 
mics6.ch_p1 %>% count(penta12_R) 
mics6.ch_p1 %>% count(penta123_R)


```


```{r changing to factor }
# changing variables into factors

# data p1

mics6.ch_p1$penta1_RC <- as.factor(mics6.ch_p1$penta1_RC)
mics6.ch_p1$penta12_RC <- as.factor(mics6.ch_p1$penta12_RC)
mics6.ch_p1$penta123_RC <- as.factor(mics6.ch_p1$penta123_RC)

mics6.ch_p1$penta1_C <- as.factor(mics6.ch_p1$penta1_C)
mics6.ch_p1$penta12_C <- as.factor(mics6.ch_p1$penta12_C)
mics6.ch_p1$penta123_C <- as.factor(mics6.ch_p1$penta123_C)

mics6.ch_p1$penta1_R <- as.factor(mics6.ch_p1$penta1_R)
mics6.ch_p1$penta12_R <- as.factor(mics6.ch_p1$penta12_R)
mics6.ch_p1$penta123_R <- as.factor(mics6.ch_p1$penta123_R)

mics6.ch_p1$IM11_2 <- as.factor(mics6.ch_p1$IM11_2)
```


## MICS 4 en 6 - p1

```{r bind rows p1}

mics4_6_p1 <- bind_rows(mics4.ch_p1, mics6.ch_p1)

sjPlot::view_df(mics4_6_p1)


mics4_6_p1 %>% count(UF8Y, UF7Y)
mics4_6_p1 %>% count(HH7R, hh7r)
mics4_6_p1 %>% count(HH6)
mics4_6_p1 %>% count(ethnicity)
mics4_6_p1 %>% count(melevel)
mics4_6_p1 %>% count(ethnicity_r)
mics4_6_p1 %>% count(melevel_r)
mics4_6_p1 %>% count(windex5)
mics4_6_p1 %>% count(HL4)
mics4_6_p1 %>% count(AGE)
mics4_6_p1 %>% count(year)

mics4_6_p1 %>% count(penta1_RC)
mics4_6_p1 %>% count(penta12_RC)
mics4_6_p1 %>% count(penta123_RC)
mics4_6_p1 %>% count(penta1_C)
mics4_6_p1 %>% count(penta12_C)
mics4_6_p1 %>% count(penta123_C)
mics4_6_p1 %>% count(penta1_R)
mics4_6_p1 %>% count(penta12_R)
mics4_6_p1 %>% count(penta123_R)


```
### Survey design P1

```{r survey design p1}

# Make design for pentavalent with selected children aged under 3 and older than 1 year: n = 8922

mics_design_4_6_p1 <- svydesign(data = mics4_6_p1, 
                         weights = ~chweight, 
                         id = ~strata+HH1)
mics_design_4_6_p1



```

```{r dependent over time}

svytable(~year + penta1_RC, design = mics_design_4_6_p1) 
svytable(~year + penta12_RC, design = mics_design_4_6_p1) 
svytable(~year + penta123_RC, design = mics_design_4_6_p1) 

svytable(~year + penta1_RC, design = mics_design_4_6_p1) -> tab
tab <- as.data.frame(tab)
plot <- ggplot(data = tab, mapping = aes(x=year, y=Freq, fill = penta1_RC)) +
  geom_col(position = "fill") +
  labs(y= "Percentage", x = "Year") +
  labs(title = "Pentavalent 1") +
  labs(fill = "Pentavalent") +
  scale_fill_discrete(labels = c("No", "Yes")) +
  scale_y_continuous(labels=percent)
print(plot)
ggsave("plotP1.png", width = 8, height = 8, units = "cm")

svytable(~year + penta12_RC, design = mics_design_4_6_p1) -> tab
tab <- as.data.frame(tab)
plot <- ggplot(data = tab, mapping = aes(x=year, y=Freq, fill = penta12_RC)) +
  geom_col(position = "fill") +
  labs(y= "Percentage", x = "Year") +
  labs(title = "Pentavalent 2") +
  labs(fill = "Pentavalent") +
  scale_fill_discrete(labels = c("No", "Yes")) +
  scale_y_continuous(labels=percent)
print(plot)
ggsave("plotP2.png", width = 8, height = 8, units = "cm")

svytable(~year + penta123_RC, design = mics_design_4_6_p1) -> tab
tab <- as.data.frame(tab)
plot <- ggplot(data = tab, mapping = aes(x=year, y=Freq, fill = penta123_RC)) +
  geom_col(position = "fill") +
  labs(y= "Percentage", x = "Year") +
  labs(title = "Pentavalent 3") +
  labs(fill = "Vaccinated") +
  scale_fill_discrete(labels = c("No", "Yes")) +
  scale_y_continuous(labels=percent)
print(plot)
ggsave("plotP3.png", width = 8, height = 8, units = "cm")


dat <- data.frame(
  penta1 = c(61.59, 77.83, 71.08),
  penta2 = c(52.98, 69.03, 62.55),
  penta3 = c(40.71, 57.11, 56.43),
  year = as.factor(c("2006", "2012", "2017"))
)

dat_long <- dat %>%
  gather("Stat", "Value", -year)

ggplot(dat_long, aes(x = year, y = Value, fill = Stat)) +
  geom_col(position = "dodge")



# dat_long <- mics4_6_p1 %>% gather("penta","counts", penta1_RC, penta12_RC, penta123_RC)

# mics_design_4_6_p2 <- svydesign(data = dat_long, 
                        # weights = ~chweight, 
                         #id = ~strata+HH1)
# mics_design_4_6_p2

# dat_long %>% count(penta)

svytable(~year + penta1_RC, ~year + penta12_RC, ~year + penta123_RC, design = mics_design_4_6_p1) -> tab
tab <- as.data.frame(tab)

ggplot(tab, aes( x = year, y = Freq, fill = penta))  +
  geom_col(position = "dodge")



app2 <- mics4_6_p1 %>% 
  group_by(year) %>% 
  summarise(penta1 = sum(penta1_RC == "1"),
            penta2 = sum(penta12_RC == "1"),
            penta3 = sum(penta123_RC == "1")) %>% 
  gather( "category", "counts", -year)

ggplot(app2, aes(year, counts)) + 
  geom_col(aes(fill = category), position = "dodge")

tab <- svytable(~ethnicity, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab

```



```{r analysis over time P1}


#penta123
summ(svyglm(penta123_RC ~year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)


summ(svyglm(penta123_RC ~HH6, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~HH7R, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~windex5, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~HL4, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~ethnicity, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~melevel, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~ethnicity_r, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~melevel_r, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~PoB, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~ANC, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~ANC_W, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

# with year as factor and interaction

summ(svyglm(penta123_RC ~HH6 + year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~HH6 + year + HH6*year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(penta123_RC ~HH7R + year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~HH7R + year + HH7R*year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(penta123_RC ~windex5 + year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~windex5 + year + windex5*year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(penta123_RC ~HL4 + year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~HL4 + year + HL4*year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(penta123_RC ~melevel + year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~melevel + year +melevel*year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(penta123_RC ~ethnicity_r + year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~ethnicity_r + year + ethnicity_r*year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(penta123_RC ~melevel_r + year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~melevel_r + year + melevel_r*year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(penta123_RC ~PoB  + year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~PoB + year + PoB*year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(penta123_RC ~ANC  + year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~ANC + year + ANC*year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(penta123_RC ~ANC_W + year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~ANC_W + year + ANC_W*year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(penta123_RC ~ANC_T + year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~ANC_T + year + ANC_T*year, design = mics_design_4_6_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

```

```{r plot interactions}


A <- svyglm(penta123_RC ~melevel_r + year + melevel_r*year, design = mics_design_4_6_p1, family = quasibinomial())

B <- svyglm(penta123_RC ~HH6 + year + HH6*year, design = mics_design_4_6_p1, family = quasibinomial())
summ(B,  exp = TRUE, confint = TRUE, digits = 2)

C <- svyglm(penta123_RC ~windex5 + year + windex5*year, design = mics_design_4_6_p1, family = quasibinomial())
summ(C,  exp = TRUE, confint = TRUE, digits = 2)

D <- svyglm(penta123_RC ~melevel + year +melevel*year, design = mics_design_4_6_p1, family = quasibinomial())
summ(D,  exp = TRUE, confint = TRUE, digits = 2)

E <- svyglm(penta123_RC ~ethnicity_r + year + ethnicity_r*year, design = mics_design_4_6_p1, family = quasibinomial())
summ(E,  exp = TRUE, confint = TRUE, digits = 2)

F <- svyglm(penta123_RC ~PoB + year + PoB*year, design = mics_design_4_6_p1, family = quasibinomial())
summ(F,  exp = TRUE, confint = TRUE, digits = 2)

G <- svyglm(penta123_RC ~ANC + year + ANC*year, design = mics_design_4_6_p1, family = quasibinomial())
summ(G,  exp = TRUE, confint = TRUE, digits = 2)

H <- svyglm(penta123_RC ~ANC_W + year + ANC_W*year, design = mics_design_4_6_p1, family = quasibinomial())
summ(H,  exp = TRUE, confint = TRUE, digits = 2)

I <- svyglm(penta123_RC ~ANC_T + year + ANC_T*year, design = mics_design_4_6_p1, family = quasibinomial())
summ(I,  exp = TRUE, confint = TRUE, digits = 2)




plotPA <- plot_model(A, type = "pred", terms = c("year", "melevel_r"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate Pentavalent vaccine", x = "year") +
  labs(title = "mother's education level * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("none", "primary", "secundary or higher")) +
  theme(legend.position="bottom")
print(plotPA)
ggsave("plotPA.png")


plotPB <- plot_model(B, type = "pred", terms = c("year", "HH6"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate Pentavalent vaccine", x = "year") +
  labs(title = "area * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("urban", "rural with road", "rural without road")) +
  theme(legend.position="bottom")
print(plotPB)
ggsave("plotPB.png")

plotPC <- plot_model(C, type = "pred", terms = c("year", "windex5"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate Pentavalent vaccine", x = "year") +
  labs(title = "wealth index quintile * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("poorest", "second", "third", "fourth", "richest")) +
  theme(legend.position="bottom")
print(plotPC)
ggsave("plotPC.png")

plotPD <- plot_model(D, type = "pred", terms = c("year", "melevel"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate Pentavalent vaccine", x = "year") +
  labs(title = "mother's education level * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("none", "primary", "lower secondary",  "upper secondary", "post-secondary", "higher")) +
  theme(legend.position="bottom")
print(plotPD)
ggsave("plotPD.png")

plotPE <- plot_model(E, type = "pred", terms = c("year", "ethnicity_r"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate Pentavalent vaccine", x = "year") +
  labs(title = "ethnicity * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("Lao-Thai", "Mon-Khmer", "Hmong-Mien", "other")) +
  theme(legend.position="bottom")
print(plotPE)
ggsave("plotPE.png")


plotPF <- plot_model(F, type = "pred", terms = c("year", "PoB"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate Pentavalent vaccine", x = "year") +
  labs(title = "place of birth * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("home", "public hospital", "other")) +
  theme(legend.position="bottom")
print(plotPF)
ggsave("plotPF.png")

plotPG <- plot_model(G, type = "pred", terms = c("year", "ANC"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate Pentavalent vaccine", x = "year") +
  labs(title = "antenatal care * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("no", "yes")) +
  theme(legend.position="bottom")
print(plotPG)
ggsave("plotPG.png")


plotPH <- plot_model(H, type = "pred", terms = c("year", "ANC_W"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate Pentavalent vaccine", x = "year") +
  labs(title = "antenatal care giver * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("no one", "doctor", "nurse/midwife", "other")) +
  theme(legend.position="bottom")
print(plotPH)
ggsave("plotPH.png")


plotPI <- plot_model(I, type = "pred", terms = c("year", "ANC_T"), show.p = TRUE) + geom_line()  +
  labs(y= "coverage rate Pentavalent vaccine", x = "year") +
  labs(title = "ANC times * year") +
  labs(colour =  "") +
  scale_colour_discrete(labels = c("1-3", "4-6", "7 or more")) +
  theme(legend.position="bottom")
print(plotPI)
ggsave("plotPI.png")




```

## mics3 P1

## Data


```{r dataset mics3 ch}

mics3.ch <- read_sav("./data/mics3/ch.sav")


```


```{r dataset mics3 wm}

mics3.wm <- read_sav("./data/mics3/wm.sav")

```


```{r glimpse}

# Mothers or primary caretakers of children under five – ch.sav
dim(mics3.ch)
# [1] 4204 335 
glimpse(mics3.ch) 

# look at lables 
sjPlot::view_df(mics3.ch)
sjPlot::view_df(mics3.wm)

# Mother / caretaker
mics3.ch %>% count(UF6) # range from 1-16
# need to make a individual number for the merging

```

```{r merging}
# selecting subset of variables of women's dataset
mics3.wm_var <- subset(mics3.wm, select = c("HH1", "HH2", "LN", "MN2A", "MN2B", "MN2C", "MN2F", "MN2G", "MN2H", "MN2X", "MN2Y","MN8"))

# HH1-2, LN for identifying women
# MN2 - ANC
# MN8 - POB

# change variable name in women dataset in order to match with children's
# woman's line number instead of line number
mics3.wm_var$UF6 <- mics3.wm_var$LN
mics3.wm %>% count(LN, WM4) # probably the same variable


# Merge joining variables from dataset woman to dataset children_2017 using as key variable: UF4 (mothers or caretakers line number in ch.sav).
# Common variables used to merge are: HH1, HH2, UF4 in children, LN in women
mics3.ch_wm <- merge(mics3.ch, mics3.wm_var, by=c("HH1", "HH2", "UF6"), all.x = TRUE)

```

```{r household and child id}

# Household ID
mics3.ch_wm %>% unite(HH_id, c(HH1, HH2), sep = "_", remove = FALSE, na.rm = FALSE) -> mics3.ch_wm

# Are there any duplicates?
mics3.ch_wm %>% group_by(HH_id) %>% filter(n()>1) %>% summarize(n=n())
# 1046 duplicates meaning more children in one household

# Unique id for each child
# UF4 should be the individual number of each child (LN of child)

mics3.ch_wm %>% 
  unite(ch_id, 
        c(HH1, HH2, UF4), sep = "_", remove = FALSE, na.rm = FALSE) -> mics3.ch_wm
mics3.ch_wm %>% group_by(ch_id) %>% filter(n()>1) %>% summarize(n=n())
# none 

```

```{r strata}

# strata
# Do I need a new variable combining HH6 and HH7?

# The sample for the Lao PDR Multiple Indicator Cluster Survey (MICS) was designed to provide estimates on a large number of indicators conerning the situation of children and women at the national level, for urban and rural areas, and for three regions: North, Central and South.

mics3.ch_wm %>% 
  unite(strata, c(HH7, HH6), sep = "_", remove = FALSE, na.rm = FALSE) -> mics3.ch_wm
mics3.ch_wm %>% count(strata)

```

```{r date of interview}

# Day of the interview

mics3.ch_wm$UF8D_2 <- as.numeric(as.character(mics3.ch_wm$UF8D))
mics3.ch_wm$UF8Y_2 <- as.numeric(as.character(mics3.ch_wm$UF8Y))
mics3.ch_wm$UF8M_2 <- as.numeric(as.character(mics3.ch_wm$UF8M))

# day of interview
mics3.ch_wm %>%  mutate(I_date = make_date(UF8Y_2, UF8M_2, UF8D_2)) -> mics3.ch_wm
# A function from lubridate package

```



```{r date of birth}

# Date of birth 
mics3.ch_wm %>% count(UF10D)
mics3.ch_wm %>% count(UF10M)

class(mics3.ch_wm$UF10M)

mics3.ch_wm$UF10D_2 <- as.numeric(mics3.ch_wm$UF10D)

mics3.ch_wm$UF10M_2 <- as.numeric(mics3.ch_wm$UF10M)

mics3.ch_wm$UF10Y_2 <- as.numeric(mics3.ch_wm$UF10Y)

mics3.ch_wm %>%  mutate(dob_ch = make_date(UF10Y_2, UF10M_2, UF10D_2)) -> mics3.ch_wm

```

```{r mics3.ch_p1}

mics3.ch_wm %>% filter(UF11 >= 1) -> mics3.ch_p1


```

#### DPT vaccine


```{r DTP 1}

# DPT 1 Only Card

mics3.ch_p1 %>% count(IM4AD)

#change date variables into categorical variables
mics3.ch_p1 %>% mutate(DPT1_C = if_else(IM4AD <= 31 & IM4AD >=1, 1,
                                        if_else(IM4AD == 0, 0,
                                        if_else(IM4AD == 44, 44, 66)))) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT1_C)
mics3.ch_p1 %>% count(DPT1_C, IM15)
mics3.ch_p1 %>% count(DPT1_C, IM15, IM10, IM9)


mics3.ch_p1 %>% 
  mutate(DPT1_C = recode(DPT1_C,
                           "44" = "1",
                           "66" = "66",
                           "1" = "1",
                           "0" = "0"
                           )) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT1_C)

# 66 needs to be replaced with NA because this is recall info and not card info # not neccesary here because there are no entries with 66

mics3.ch_p1$DPT1_C_1 <- mics3.ch_p1$DPT1_C
mics3.ch_p1 %>% replace_with_na(replace = list(DPT1_C_1 = "66")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT1_C_1)


# DTP1 only recall

mics3.ch_p1 %>% count(IM9, IM10, IM15, DPT1_C_1)
mics3.ch_p1 %>% count(IM9, DPT1_C_1)
mics3.ch_p1 %>% count(IM10, IM15)



# First recode IM15 into DPT1_R: recall variable

mics3.ch_p1 %>% count(IM15)
mics3.ch_p1 %>% 
  mutate(DPT1_R = recode(IM15,
                           "1" = "R_1",
                           "2" = "R_0",
                           "8" = "R_8",
                           "9" = "R_9")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT1_R)



# It is not yet correct
# In IM10; if all responses were "NO"; there was no probing for the recall of vaccinations
# Therefore; some of the NAs in the new variable need to be changed to "No" or "DK" #512 no and #13 DK and 2 No response

mics3.ch_p1 %>% 
  mutate(DPT1_R = replace(DPT1_R, is.na(DPT1_R) & IM10 == 2, "R_0"))  %>%
  mutate(DPT1_R = replace(DPT1_R, is.na(DPT1_R) & IM10 == 8, "R_8")) %>%
  mutate(DPT1_R = replace(DPT1_R, is.na(DPT1_R) & IM10 == 9, "R_9")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT1_R)


# combine Recall and Card

mics3.ch_p1 %>% count(DPT1_R, DPT1_C)
mics3.ch_p1 %>% mutate(DPT1_RC = coalesce(DPT1_C, DPT1_R)) -> mics3.ch_p1 
mics3.ch_p1 %>% count(DPT1_RC, IM9)

# Only 1 response is still NA, not categorized. This is solved when using IM9, then the category is 2: Missing, so this response will be categorized as R_0.

mics3.ch_p1 %>% 
  mutate(DPT1_RC = replace(DPT1_RC, is.na(DPT1_RC) & IM9 == 2, "R_0")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT1_RC)


mics3.ch_p1 %>% 
  mutate(DPT1_R_1 = recode(DPT1_RC,
                           "R_0" = "R_0",
                           "R_1" = "R_1",
                           "R_8" = "R_0",
                           "R_9" = "R_0"
                           )) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT1_R_1)

# all outcomes from card RC need to be replaced with NA to only retain recall
mics3.ch_p1 %>% replace_with_na(replace = list(DPT1_R_1 = c("0", "1"))) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT1_R_1)

# combination recall and card
mics3.ch_p1 %>%
  mutate(DPT1_RC_1 = recode(DPT1_RC,
                              "0" = 0,
                              "1" = 1,
                              "R_9" = 0,
                              "R_0" = 0,
                              "R_1" = 1,
                              "R_8" = 0
                              )) -> mics3.ch_p1

mics3.ch_p1 %>% count(DPT1_RC_1) # 0: 592 1: 1064
mics3.ch_p1 %>% count(DPT1_R_1) # 0: 583 1: 355
mics3.ch_p1 %>% count(DPT1_C_1) # 0: 9 1: 709



```

```{r DTP 2}

# DPT 2 Only Card

mics3.ch_p1 %>% count(IM4BD)

#change date variables into categorical variables
mics3.ch_p1 %>% mutate(DPT2_C = if_else(IM4BD <= 31 & IM4BD >=1, 1,
                                        if_else(IM4BD == 0, 0,
                                        if_else(IM4BD == 44, 44, 66)))) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_C)
mics3.ch_p1 %>% count(DPT2_C, IM15)
mics3.ch_p1 %>% count(DPT2_C, IM15, IM10, IM9)


mics3.ch_p1 %>% 
  mutate(DPT2_C = recode(DPT2_C,
                           "44" = "1",
                           "66" = "66",
                           "1" = "1",
                           "0" = "0"
                           )) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_C)

# 66 needs to be replaced with NA because this is recall info and not card info # not neccesary here because there are no entries with 66

mics3.ch_p1$DPT2_C_1 <- mics3.ch_p1$DPT2_C
mics3.ch_p1 %>% replace_with_na(replace = list(DPT2_C_1 = "66")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_C_1)


# DTP1 only recall

mics3.ch_p1 %>% count(IM9, IM10, IM15, DPT2_C_1)
mics3.ch_p1 %>% count(IM9, DPT2_C_1)
mics3.ch_p1 %>% count(IM10, IM15)



# First recode IM15 into DPT2_R: recall variable

mics3.ch_p1 %>% count(IM15)
mics3.ch_p1 %>% 
  mutate(DPT2_R = recode(IM15,
                           "1" = "R_1",
                           "2" = "R_0",
                           "8" = "R_8",
                           "9" = "R_9")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_R)

# Then recode IM16 into DPT2_R_2: recall variable

mics3.ch_p1 %>% count(IM16)
mics3.ch_p1 %>% 
  mutate(DPT2_R_2 = recode(IM16,
                           "1" = "R_1",
                           "2" = "R_2",
                           "3" = "R_3",
                           "4" = "R_4",
                           "5" = "R_5",
                           "6" = "R_6",
                           "7" = "R_7",
                           "8" = "R_8",
                           "9" = "R_9")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_R_2)

# make a new variable combining IM15 and IM16. 
# IM 21: 2,3,4,5,6 of 7 means having the second DPT vaccine, IM16: 1,8 or 9 had only one or dont know whether they had one DPT vaccine or more, therefore do not include them assign to 0 together with IM15 No and DK.
 
mics3.ch_p1 %>% count(DPT2_R_2, DPT1_R)
mics3.ch_p1 %>% mutate(DPT2_R_3 = coalesce(DPT2_R_2, DPT1_R)) -> mics3.ch_p1 
mics3.ch_p1 %>% count(DPT2_R_3)

mics3.ch_p1 %>% count(IM9, IM10, DPT2_R_3) # everything is correct, no need for replacing

# Recode recall variable DPT2 into yes or no

mics3.ch_p1 %>% 
  mutate(DPT2_R_2 = recode(DPT2_R_3,
                           "R_0" = "R_0",
                           "R_1" = "R_0",
                           "R_2" = "R_1",
                           "R_3" = "R_1",
                           "R_4" = "R_1",
                           "R_5" = "R_1",
                           "R_6" = "R_1",
                           "R_7" = "R_1",
                           "R_8" = "R_0",
                           "R_9" = "R_0"
                           )) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_R_2)


# combine Recall and Card

mics3.ch_p1 %>% count(DPT2_R_2, DPT2_C)

# R_0	0	  3		
# R_0	1	  21		
# R_0	NA	663		
# R_1	1	  10		
# R_1	NA	274		
# NA	0	  71		
# NA	1	  606		
# NA	NA	8

# 21 children have 1 on card and value 0 on recall; 1o children have value 1 on card and 1 on recall, 8 children have no value on both card. 
# 21 and 10 children should be counted on the card, in recall variable change for NA

mics3.ch_p1 %>% mutate(DPT2_RC = coalesce(DPT2_C, DPT2_R_2)) -> mics3.ch_p1 
mics3.ch_p1 %>% count(DPT2_RC, IM9)

# Only 1 response is still NA, not categorized. This is solved when using IM9, then the category is 2: Missing, so this response will be categorized as R_0.

mics3.ch_p1 %>% 
  mutate(DPT2_RC = replace(DPT2_RC, is.na(DPT2_RC) & IM9 == 2, "R_0")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_RC)
mics3.ch_p1 %>% 
  mutate(DPT2_RC = replace(DPT2_RC, is.na(DPT2_RC) & IM9 == 1, "R_0")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_RC)


mics3.ch_p1 %>% 
  mutate(DPT2_R_1 = recode(DPT2_RC,
                           "R_0" = "R_0",
                           "R_1" = "R_1",
                           "R_8" = "R_0",
                           "R_9" = "R_0"
                           )) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_R_1)

# all outcomes from card RC need to be replaced with NA to only retain recall
mics3.ch_p1 %>% replace_with_na(replace = list(DPT2_R_1 = c("0", "1"))) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_R_1)

# combination recall and card
mics3.ch_p1 %>%
  mutate(DPT2_RC_1 = recode(DPT2_RC,
                              "0" = 0,
                              "1" = 1,
                              "R_9" = 0,
                              "R_0" = 0,
                              "R_1" = 1,
                              "R_8" = 0
                              )) -> mics3.ch_p1

mics3.ch_p1 %>% count(DPT2_RC_1) # 0: 745 1: 911
mics3.ch_p1 %>% count(DPT2_R_1) # 0: 671 1: 274
mics3.ch_p1 %>% count(DPT2_C_1) # 0: 74 1: 637




```

```{r DTP 3}

# DPT 2 Only Card

mics3.ch_p1 %>% count(IM4CD)

#change date variables into categorical variables
mics3.ch_p1 %>% mutate(DPT3_C = if_else(IM4CD <= 31 & IM4CD >=1, 1,
                                        if_else(IM4CD == 0, 0,
                                        if_else(IM4CD == 44, 44, 66)))) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT3_C)
mics3.ch_p1 %>% count(DPT3_C, IM15)
mics3.ch_p1 %>% count(DPT3_C, IM15, IM10, IM9)


mics3.ch_p1 %>% 
  mutate(DPT3_C = recode(DPT3_C,
                           "44" = "1",
                           "66" = "66",
                           "1" = "1",
                           "0" = "0"
                           )) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT3_C)

# 66 needs to be replaced with NA because this is recall info and not card info # not neccesary here because there are no entries with 66

mics3.ch_p1$DPT3_C_1 <- mics3.ch_p1$DPT3_C
mics3.ch_p1 %>% replace_with_na(replace = list(DPT3_C_1 = "66")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT3_C_1)


# DTP1 only recall

mics3.ch_p1 %>% count(IM9, IM10, IM15, DPT3_C_1)
mics3.ch_p1 %>% count(IM9, DPT3_C_1)
mics3.ch_p1 %>% count(IM10, IM15)



# First recode IM15 into DPT3_R: recall variable

mics3.ch_p1 %>% count(IM15)
mics3.ch_p1 %>% 
  mutate(DPT3_R = recode(IM15,
                           "1" = "R_1",
                           "2" = "R_0",
                           "8" = "R_8",
                           "9" = "R_9")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT3_R)

# Then recode IM16 into DPT3_R_2: recall variable

mics3.ch_p1 %>% count(IM16)
mics3.ch_p1 %>% 
  mutate(DPT3_R_2 = recode(IM16,
                           "1" = "R_1",
                           "2" = "R_2",
                           "3" = "R_3",
                           "4" = "R_4",
                           "5" = "R_5",
                           "6" = "R_6",
                           "7" = "R_7",
                           "8" = "R_8",
                           "9" = "R_9")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT3_R_2)

# make a new variable combining IM15 and IM16. 
# IM 21: 2,3,4,5,6 of 7 means having the second DPT vaccine, IM16: 1,8 or 9 had only one or dont know whether they had one DPT vaccine or more, therefore do not include them assign to 0 together with IM15 No and DK.
 
mics3.ch_p1 %>% count(DPT3_R_2, DPT1_R)
mics3.ch_p1 %>% mutate(DPT3_R_3 = coalesce(DPT3_R_2, DPT1_R)) -> mics3.ch_p1 
mics3.ch_p1 %>% count(DPT3_R_3)

mics3.ch_p1 %>% count(IM9, IM10, DPT3_R_3) # everything is correct, no need for replacing

# Recode recall variable DPT3 into yes or no

mics3.ch_p1 %>% 
  mutate(DPT3_R_2 = recode(DPT3_R_3,
                           "R_0" = "R_0",
                           "R_1" = "R_0",
                           "R_2" = "R_0",
                           "R_3" = "R_1",
                           "R_4" = "R_1",
                           "R_5" = "R_1",
                           "R_6" = "R_1",
                           "R_7" = "R_1",
                           "R_8" = "R_0",
                           "R_9" = "R_0"
                           )) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT3_R_2)


# combine Recall and Card

mics3.ch_p1 %>% count(DPT3_R_2, DPT3_C)

# R_0	0	  3		
# R_0	1	  21		
# R_0	NA	663		
# R_1	1	  10		
# R_1	NA	274		
# NA	0	  71		
# NA	1	  606		
# NA	NA	8

# 21 children have 1 on card and value 0 on recall; 1o children have value 1 on card and 1 on recall, 8 children have no value on both card. 
# 21 and 10 children should be counted on the card, in recall variable change for NA

mics3.ch_p1 %>% mutate(DPT3_RC = coalesce(DPT3_C, DPT3_R_2)) -> mics3.ch_p1 
mics3.ch_p1 %>% count(DPT3_RC, IM9)

# Only 1 response is still NA, not categorized. This is solved when using IM9, then the category is 2: Missing, so this response will be categorized as R_0.

mics3.ch_p1 %>% 
  mutate(DPT3_RC = replace(DPT3_RC, is.na(DPT3_RC) & IM9 == 2, "R_0")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT3_RC)
mics3.ch_p1 %>% 
  mutate(DPT3_RC = replace(DPT3_RC, is.na(DPT3_RC) & IM9 == 1, "R_0")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT3_RC)
mics3.ch_p1 %>% 
  mutate(DPT3_RC = replace(DPT3_RC, is.na(DPT3_RC) & IM9 == 8, "R_0")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT3_RC)


mics3.ch_p1 %>% 
  mutate(DPT3_R_1 = recode(DPT3_RC,
                           "R_0" = "R_0",
                           "R_1" = "R_1",
                           "R_8" = "R_0",
                           "R_9" = "R_0"
                           )) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT3_R_1)

# all outcomes from card RC need to be replaced with NA to only retain recall
mics3.ch_p1 %>% replace_with_na(replace = list(DPT3_R_1 = c("0", "1"))) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT3_R_1)

# combination recall and card
mics3.ch_p1 %>%
  mutate(DPT3_RC_1 = recode(DPT3_RC,
                              "0" = 0,
                              "1" = 1,
                              "R_9" = 0,
                              "R_0" = 0,
                              "R_1" = 1,
                              "R_8" = 0
                              )) -> mics3.ch_p1

mics3.ch_p1 %>% count(DPT3_RC_1) # 0: 962 1: 694
mics3.ch_p1 %>% count(DPT3_R_1) # 0: 793 1: 173
mics3.ch_p1 %>% count(DPT3_C_1) # 0: 169 1: 521

```

```{r penta 123}

# check if they got all 3 vaccinations, not only second or third. 


mics3.ch_p1 %>% count(DPT1_RC_1, DPT2_RC_1, DPT3_RC_1)


# new variables at least one vaccine


# new variable penta1 got at least one vaccinations according to card or recall
mics3.ch_p1 %>% mutate(penta1_RC = if_else(DPT1_RC_1 == 1 | DPT2_RC_1 == 1 | DPT3_RC_1 == 1, 1, 0)) -> mics3.ch_p1
mics3.ch_p1 %>% count(penta1_RC)



# new variable penta12 got at least two vaccinations according to card or recall
mics3.ch_p1 %>% mutate(penta12_RC = if_else(DPT1_RC_1 == 1 & DPT2_RC_1 == 1, 1,
                                    if_else(DPT1_RC_1 == 1 & DPT3_RC_1 == 1, 1,
                                    if_else(DPT2_RC_1 == 1 & DPT3_RC_1 == 1, 1, 0)))) -> mics3.ch_p1
mics3.ch_p1 %>% count(penta12_RC)


# new variable penta123 got at least three vaccinations according to card or recall
mics3.ch_p1 %>% mutate(penta123_RC = if_else(DPT1_RC_1 == 1 & DPT2_RC_1 == 1 & DPT3_RC_1 == 1, 1, 0)) -> mics3.ch_p1
mics3.ch_p1 %>% count(penta123_RC)

mics3.ch_p1$year <- mics3.ch_p1$UF8Y



```

```{r changing to factor}

mics3.ch_p1$penta1_RC <- as.factor(mics3.ch_p1$penta1_RC)
mics3.ch_p1$penta12_RC <- as.factor(mics3.ch_p1$penta12_RC)
mics3.ch_p1$penta123_RC <- as.factor(mics3.ch_p1$penta123_RC)

mics3.ch_p1$year <- as.factor(mics3.ch_p1$year)

```

```{r selecting variables }
mics3.ch_var <- subset(mics3.ch_p1, select = c("penta1_RC", "penta12_RC", "penta123_RC", "year", "chweight", "HH1", "strata"))

```

```{r bind mics 3 to mics 4 and 6}

mics3_4_6_p1 <- bind_rows(mics3.ch_var, mics4_6_p1)

sjPlot::view_df(mics3_4_6_p1)


```

```{r survey design}
# Make design for hepb0 with selected children aged under 3: n = 13460

mics_design3_4_6_p1 <- svydesign(data = mics3_4_6_p1, 
                         weights = ~chweight, 
                         id = ~strata+HH1)


```


```{r dependent over time}
svytable(~year + penta1_RC, design = mics_design3_4_6_p1) -> tab
tab <- as.data.frame(tab)
plot <- ggplot(data = tab, mapping = aes(x=year, y=Freq, fill = penta1_RC)) +
  geom_col(position = "fill") +
  labs(y= "Percentage", x = "Year") +
  labs(title = "Pentavalent 1") +
  labs(fill = "Pentavalent") +
  scale_fill_discrete(labels = c("No", "Yes")) +
  scale_y_continuous(labels=percent)
print(plot)
ggsave("plotP4.png", width = 8, height = 8, units = "cm")

svytable(~year + penta12_RC, design = mics_design3_4_6_p1) -> tab
tab <- as.data.frame(tab)
plot <- ggplot(data = tab, mapping = aes(x=year, y=Freq, fill = penta12_RC)) +
  geom_col(position = "fill") +
  labs(y= "Percentage", x = "Year") +
  labs(title = "Pentavalent 2") +
  labs(fill = "Pentavalent") +
  scale_fill_discrete(labels = c("No", "Yes")) +
  scale_y_continuous(labels=percent)
print(plot)
ggsave("plotP5.png", width = 8, height = 8, units = "cm")

svytable(~year + penta123_RC, design = mics_design3_4_6_p1) -> tab
tab <- as.data.frame(tab)
plot <- ggplot(data = tab, mapping = aes(x=year, y=Freq, fill = penta123_RC)) +
  geom_col(position = "fill") +
  labs(y= "Percentage", x = "Year") +
  labs(title = "Pentavalent 3") +
  labs(fill = "Vaccinated") +
  scale_fill_discrete(labels = c("No", "Yes")) +
  scale_y_continuous(labels=percent)
print(plot)
ggsave("plotP6.png", width = 8, height = 8, units = "cm")
```

