---
title: "mics4_td"
author: "Trude"
date: "28-4-2021"
output: github_document:
  toc: true
  toc_depth: 3
  number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Lao PDR: MICS Data - mics4






```{r options}

options(scipen = 999) # suppress scientific notion

```



```{r packages}

library(tidyverse)

# library(expss) # export

library(haven) 

library(sjPlot)

#library(sjlabelled)

#library(labelled)

#library(surveytoolbox) # install with #devtools::install_github("martinctc/surveytoolbox")

library(lubridate) # working with dates

library(survey)

#library(sjmisc)

#library(knitr)

library(janitor)

#library(survminer)

library(DataExplorer)

library(naniar)

library(jtools)

library(MASS)

library(lmtest)

library(WeMix)
```



## Data


```{r dataset mics4 ch}

mics4.ch <- read_sav("./data/mics4/ch.sav")

```


```{r dataset mics4 wm}

mics4.wm <- read_sav("./data/mics4/wm.sav")

```


```{r glimpse}

# look at lables 
sjPlot::view_df(mics4.ch)

```

```{r selecting variables children dataset}

mics4.ch_var <- subset(mics4.ch, select = c("HH1", "HH2", "UF4", "UF6", "UF8Y", "HH6", "HH7", "CAGE", "AG2", "CAGED", "IM1", "IM3H0D", "IM3H0M", "IM3H0Y", "IM3H1D", "IM3H1M", "IM3H1Y", "IM3H2D", "IM3H2M", "IM3H2Y", "IM3H3D", "IM3H3M", "IM3H3Y", "IM5", "IM6", "IM19A", "IM19B", "IM19C", "IM11", "IM12", "IM13", "IM14", "IM15", "AG1D", "AG1M", "AG1Y", "ethnicity", "melevel", "HH7R", "windex5", "HL4", "chweight", "UF11"))

```


### Merging women data to children data 

```{r merging}
# selecting subset of variables of women's dataset
mics4.wm_var <- subset(mics4.wm, select = c("HH1", "HH2", "LN", "MN1", "MN2A", "MN2B", "MN2C", "MN2F", "MN2G", "MN2X", "MN3", "MN18"))

# change variable name in women dataset in order to match with children's
mics4.wm_var$UF6 <- mics4.wm_var$LN
mics4.wm_var %>% count(UF6, LN)

# 11258 281
# 23937 12 


# Merge joining variables from dataset woman to dataset children_2012 using as key variable: UF6 (mothers or caretakers line number in ch.sav).
# Common variables used to merge are: HH1, HH2, UF6 in children, LN in women
mics4.ch_wm <- merge(mics4.ch_var, mics4.wm_var, by=c("HH1", "HH2", "UF6"), all.x = TRUE)

# Look if merging succeeded
# look at lables 
sjPlot::view_df(mics4.wm_var)
sjPlot::view_df(mics4.ch_wm)


```




### New variables


```{r recall or not}

# # If response to IM5 and IM6 was always No or DK; child did not receive any vaccination! And will result in NA in recall questions
mics4.ch_wm %>% count(IM5, IM6, IM19A, IM19B, IM19C)


# New variable: IM5_IM6 = 0 when there was no recall questions done anymore. entry 1 from IM5 also stops the questionnaire.!!

mics4.ch_wm %>% 
  mutate(IM5_IM6 = ifelse((IM5 == 2 | IM5 == 8) | 
                            (IM6 == 2 | IM6 == 8), 0, 1)) -> mics4.ch_wm
mics4.ch_wm %>% count(IM5_IM6, IM5, IM6)

mics4.ch_wm %>% 
  mutate(IM5_IM6_1 = ifelse((IM5 == 2 | IM5 == 8) | 
                            (IM6 == 2 |IM6 == 8 | IM6 == 9), 0, 1)) -> mics4.ch_wm
mics4.ch_wm %>% count(IM5_IM6_1, IM5, IM6)


mics4.ch_wm %>% 
  mutate(IM5_2 = ifelse((IM5_IM6 == 0 & IM5 == 2), 2,
                  ifelse((IM5_IM6 == 0 & IM5 == 8), 8, NA))) -> mics4.ch_wm

mics4.ch_wm %>% count(IM5,IM5_2)
# is this variable necessary?

```


```{r date of birth}

# Date of birth 
mics4.ch_wm %>% count(AG1D)
mics4.ch_wm %>% count(AG1M)

class(mics4.ch_wm$UB1M)

mics4.ch_wm$AG1D_2 <- as.numeric(mics4.ch_wm$AG1D)

mics4.ch_wm$AG1M_2 <- as.numeric(mics4.ch_wm$AG1M)

mics4.ch_wm$AG1Y_2 <- as.numeric(mics4.ch_wm$AG1Y)

mics4.ch_wm %>%  mutate(dob_ch = make_date(AG1Y_2, AG1M_2, AG1D_2)) -> mics4.ch_wm
#mics4.ch_wm$dob_ch
class(mics4.ch_wm$AG1M_2)

```

```{r household and child id}


# Household ID
mics4.ch_wm %>% unite(HH_id, c(HH1, HH2), sep = "_", remove = FALSE, na.rm = FALSE) -> mics4.ch_wm


# households with more than one child
mics4.ch_wm %>% 
  filter(AG2 <3) %>% 
  group_by(HH_id) %>% filter(n()>1) %>% summarize(n=n())# 806

# unique id for each child
mics4.ch_wm %>% unite(ch_id, c(HH1, HH2, UF4), sep = "_", remove = FALSE, na.rm = FALSE) -> mics4.ch_wm

mics4.ch_wm %>% group_by(ch_id) %>% filter(n()>1) %>% summarize(n=n()) # none...
# identify each child


```




```{r strata}

mics4.ch_wm %>% 
  unite(strata, c(HH7, HH6), sep = "_", remove = FALSE, na.rm = FALSE) -> mics4.ch_wm
mics4.ch_wm %>% count(strata)

# 49 strata??

# Understanding the sample design
mics4.ch_wm %>% count(HH1) # enumeration areas; 20 hh were drawn for each enumeration area
mics4.ch_wm %>% count(HH6)
mics4.ch_wm %>% tabyl(HH7, HH6)

mics4.ch_wm %>% count(strata) # 49 rows

# How many clusters:

# Provinces are strata
mics4.ch_wm %>% summarize(n_clusters = n_distinct(HH7, HH1))
# 998

mics4.ch_wm %>% summarize(n_clusters = n_distinct(strata, HH1))
# 998 # same

```



```{r recode categories in independent variables}



mics4.ch_wm$ethnicity <- as.factor(mics4.ch_wm$ethnicity)
mics4.ch_wm$melevel <- as.factor(mics4.ch_wm$melevel)


mics4.ch_wm %>% mutate(ethnicity_r = recode(ethnicity, "1" = 1, "2" = 2, "3" = 3, "4" = 4, "9" = 4)) -> mics4.ch_wm
mics4.ch_wm %>% count(ethnicity_r)

mics4.ch_wm %>% mutate(melevel_r = recode(melevel, "1" = 0, "2" = 1, "3" = 2, "4" = 2, "5" = 2, "6" = 2, "9" = 0)) -> mics4.ch_wm
mics4.ch_wm %>% count(melevel, melevel_r)
```




### Subsets

```{r mics4.ch_b1}

#subset children under 3
mics4.ch_wm %>% filter(AG2 < 3) -> mics4.ch_b1 
# 6591 when using CAGE, 
# 6573 using AG2, difference is because there are 19 children who are 3 years and 35 months, and 1 child 36 month and 2 years old. 


```




```{r mics4.ch_p1}

mics4.ch_b1 %>% filter(CAGED > 365) -> mics4.ch_p1


```

## mics4_b1


### New variables

```{r hepatitis B birth dose}


# Convert to numeric values: day/ month/ year

mics4.ch_b1$IM3H0D_2 <- as.numeric(mics4.ch_b1$IM3H0D)
mics4.ch_b1$IM3H0M_2 <- as.numeric(mics4.ch_b1$IM3H0M)
mics4.ch_b1$IM3H0Y_2 <- as.numeric(mics4.ch_b1$IM3H0Y)

# Now create the date
mics4.ch_b1 %>% mutate(IM3H0_date = make_date(IM3H0Y_2, IM3H0M_2, IM3H0D_2)) -> mics4.ch_b1
mics4.ch_b1 %>% count(IM3H0_date) # looks ok


# Time since vaccination

# I am using a command from R base here. There is probably a way to calculate it with a tidyverse command

mics4.ch_b1$IM3H0_time <- as.numeric(difftime(mics4.ch_b1$IM3H0_date, mics4.ch_b1$dob_ch, units = "days"))
summary(mics4.ch_b1$IM3H0_time)
# Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
# -365.00    0.00    0.00   17.44    6.50  688.00    5100 

# Comments on time since vaccination:
# min = -365 probably mistake in year. 
# Max = 688 days; could be a mistake in writing down the year?


# histogram
mics4.ch_b1 %>% ggplot(aes(x=IM3H0_time)) + geom_histogram(binwidth = 1)

# Card: vaccinated within 24 hours

mics4.ch_b1 %>% 
  mutate(hepb0_C24 = ifelse(IM3H0_time == 0, "The same day", ifelse(IM3H0_time == 1, "The next day", "Later"))) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C24) 

# some children can have NA because they have no date of birth instead of no date on vaccination!! They have no info on time since vaccination (IM3H0_time), but that doesn't mean that they are not vaccinated. Check by comparing info on dob and date of vaccination. 

mics4.ch_b1 %>% mutate(dov_1 = if_else(IM3H0D <= 31 & IM3H0D >=1, 1, 0)) -> mics4.ch_b1
mics4.ch_b1 %>% mutate(dob_1 = if_else(AG1D <= 31 & AG1D >=1, 1, 0)) -> mics4.ch_b1
mics4.ch_b1 %>% count(dov_1, dob_1, hepb0_C24)
#24 children have a date on vaccination but no date on birth, therefore the time difference can not be calculated. They are in the category NA, while they should be in the category 'later'. 
#2 children have dates on both vaccination and birth but have NA on hepb0_C24. Why? normally they should be categorized in "LAter". Maybe because the have a negative time??

#change date variables into categorical variables
mics4.ch_b1 %>% mutate(hepb0_C = if_else(IM3H0D <= 31 & IM3H0D >=1, 1,
                                        if_else(IM3H0D == 0, 0,
                                        if_else(IM3H0D == 44, 44, 
                                        if_else(IM3H0D == 66, 66,99))))) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C)

# Code variable hepb0_C
# if date is there = 1
# marked on card = 44
# mother reported = 66  # technically recall 
# missing = 99
# not given = 0


mics4.ch_b1 %>% count(hepb0_C, hepb0_C24) # There are 24 + 2 people for which the the categorization did not work - why? - because there is no date of birth or negative one. 

# combination of card within 24 hours and card date variable
mics4.ch_b1 %>% 
  unite(hepb0_C, c(hepb0_C, hepb0_C24), sep = "_", remove = FALSE, na.rm = FALSE) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C)


# NA_NA needs to be replaced with NA
mics4.ch_b1 %>% replace_with_na(replace = list(hepb0_C = "NA_NA")) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C)


# Recall variable IM14 hepb0 within 24 hours or later
# Recode IM14 into hepb0_R: recall variable

mics4.ch_b1 %>% count(IM14)
mics4.ch_b1$IM14_2 <- as.numeric(mics4.ch_b1$IM14)
mics4.ch_b1 %>% count(IM13)
mics4.ch_b1$IM13_2 <- as.numeric(mics4.ch_b1$IM13)
mics4.ch_b1 %>% 
  mutate(hepb0_R_14 = recode(IM14_2,
                           "1" = "R_Yes",
                           "2" = "R_Later",
                           "9" = "R_9")) -> mics4.ch_b1
mics4.ch_b1 %>% 
  mutate(hepb0_R_13 = recode(IM13_2,
                           "1" = "R_Yes",
                           "2" = "R_No",
                           "8" = "R_8",
                           "9" = "R_9")) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C, hepb0_R_13, hepb0_R_14)


mics4.ch_b1 %>% count(hepb0_C, hepb0_R_13, hepb0_R_14, IM6, IM5)

# It is not yet correct
# In IM6; if responses were No, DK or Missing; there was no probing for the recall of vaccinations
# Therefore; some of the NAs in the new variable need to be changed to "No" or "DK" or Missing

mics4.ch_b1 %>% 
  mutate(hepb0_R_13 = replace(hepb0_R_13, is.na(hepb0_R_13) & IM6 == 2, "R_No"))  %>%
  mutate(hepb0_R_13 = replace(hepb0_R_13, is.na(hepb0_R_13) & IM6 == 8, "R_8"))  %>%
  mutate(hepb0_R_13 = replace(hepb0_R_13, is.na(hepb0_R_13) & IM6 == 9, "R_9")) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_R_13)
mics4.ch_b1 %>% count(hepb0_C, hepb0_R_13, hepb0_R_14)

# Combine Recall variable 13 and 14 into one recall variable
mics4.ch_b1 %>% 
  unite(hepb0_R, c(hepb0_R_13, hepb0_R_14), sep = "_", remove = FALSE, na.rm = FALSE) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C)

mics4.ch_b1 %>% count(hepb0_C, hepb0_R)
mics4.ch_b1 %>% mutate(hepb0_RC = coalesce(hepb0_C, hepb0_R)) -> mics4.ch_b1 
mics4.ch_b1 %>% count(hepb0_RC)

# Now, all responses should be categorized correctly, at least all NA's. 
# Except for 44_NA -> 1_Later: Marked on card, not known whether within 24 hrs
# and 66_NA -> which should be categorized as recall, mother reported that there was a vaccination but not sure whether within 24 hours 

mics4.ch_b1 %>% 
  mutate(hepb0_RC = recode(hepb0_RC,
                           "0_NA" = "0",
                           "1_NA" = "1_Later", 
                           "44_NA" = "1_Later",
                           "66_NA" = "R_Later",
                           "99_NA" = "0",
                           "R_8_NA" = "R_8",
                           "R_9_NA" = "R_9",
                           "R_No_NA" = "R_No",
                           "R_Yes_R_9" = "R_Later",
                           "R_Yes_R_Later" = "R_Later",
                           "R_Yes_R_Yes" = "R_Yes" )) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_RC)

# hepatitis B birth dose (yes, no)
# DK will be grouped with no
# Missing will be grouped with no
# Within 24 hours or the next day: 1
# later: 2
# no vaccination: 0
mics4.ch_b1 %>% 
  mutate(hepb0_RC_1 = recode(hepb0_RC,
                           "0" = "0",
                           "1_Later" = "2",
                           "1_The next day" = "1",
                           "1_The same day" = "1",
                           "R_No" = "0",
                           "R_8" = "0",
                           "R_9" = "0",
                           "R_Later" = "2",
                           "R_Yes" = "1")) -> mics4.ch_b1

mics4.ch_b1 %>% count(hepb0_RC_1, hepb0_RC)


# create new variable within 24 hours: 1, not within 24 hours:0
mics4.ch_b1 %>% 
  mutate(hepb0_RC_24 = recode(hepb0_RC_1,
                           "0" = "0",
                           "2" = "0",
                           "1" = "1"
                          )) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_RC_24)

# create new variable hepb0 yes or no card and recall
mics4.ch_b1 %>% 
  mutate(hepb0_RC_2 = recode(hepb0_RC_1,
                           "0" = "0",
                           "2" = "1",
                           "1" = "1"
                          )) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_RC_2)

# only card
# 66_NA needs to be replaced with NA
mics4.ch_b1 %>% replace_with_na(replace = list(hepb0_C = "66_NA")) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C)

# only card variable hepb0 (yes/no)
mics4.ch_b1 %>% 
  mutate(hepb0_C_2 = recode(hepb0_C,
                           "0_NA" = "0",
                           "1_Later" = "1",
                           "1_NA" = "1",
                           "1_The next day" = "1",
                           "1_The same day" = "1",
                           "44_NA" = "1",
                           "99_NA" = "0")) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C_2)

# only card variable hepb0 (24hrs)
mics4.ch_b1 %>% 
  mutate(hepb0_C_24 = recode(hepb0_C,
                           "0_NA" = "0",
                           "1_Later" = "0",
                           "1_NA" = "0",
                           "1_The next day" = "1",
                           "1_The same day" = "1",
                           "44_NA" = "0",
                           "99_NA" = "0")) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C_24)

mics4.ch_b1$hepb0_R_1 <- mics4.ch_b1$hepb0_RC
mics4.ch_b1 %>% count(hepb0_R_1)

# all outcomes from Card need to be replaced with NA: hepb0_RC is now variable hepb0_R with recall from card variable outcome 66
mics4.ch_b1 %>% replace_with_na(replace = list(hepb0_R_1 = c("0", "1_Later", "1_The next day", "1_The same day"))) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_R_1)

# only recal hepbo within 24 hours (yes/no)
mics4.ch_b1 %>%
  mutate(hepb0_R_24 = recode(hepb0_R_1,
                           "R_No" = "0",
                           "R_8" = "0",
                           "R_9" = "0",
                           "R_Later" = "0",
                           "R_Yes" = "1")) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_R_24)

# only recall variable hepb0 (yes/no)
mics4.ch_b1 %>% 
  mutate(hepb0_R_2 = recode(hepb0_R_1,
                           "R_No" = "0",
                           "R_8" = "0",
                           "R_9" = "0",
                           "R_Later" = "1",
                           "R_Yes" = "1"
                          )) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_R_2)


# Needed dichotomous variables for analysis
mics4.ch_b1 %>% count(hepb0_RC_2) # 0: 3444 1: 3129
mics4.ch_b1 %>% count(hepb0_RC_24)# 0: 5287 1: 1286
mics4.ch_b1 %>% count(hepb0_C_2)  # 0: 1197 1: 1653
mics4.ch_b1 %>% count(hepb0_C_24) # 0: 1939 1: 911
mics4.ch_b1 %>% count(hepb0_R_2) # 0: 2247 1: 1476
mics4.ch_b1 %>% count(hepb0_R_24) # 0: 3348 1: 375



```


```{r anc replace 9 with na}


mics4.ch_b1 %>% count(MN18)

mics4.ch_b1 %>% count(MN3)

mics4.ch_b1 %>% count(MN1)

mics4.ch_b1 %>% replace_with_na(replace = list(MN18 = "99")) -> mics4.ch_b1

mics4.ch_b1 %>% replace_with_na(replace = list(MN3 = "99")) -> mics4.ch_b1

mics4.ch_b1 %>% replace_with_na(replace = list(MN1 = "9")) -> mics4.ch_b1

mics4.ch_b1 %>% count(MN18)

mics4.ch_b1 %>% count(MN3)

mics4.ch_b1 %>% count(MN1)


```



```{r anc}


mics4.ch_b1$ANC <- mics4.ch_b1$MN1

mics4.ch_b1 %>% mutate(ANC = recode(ANC,
                                     "1" = 1,
                                     "2" = 0
                                     )) -> mics4.ch_b1

mics4.ch_b1 %>% count(MN18)

class(mics4.ch_b1$MN18)
mics4.ch_b1$MN18 <- as.factor(mics4.ch_b1$MN18)


# new variable place of delivery
mics4.ch_b1 %>% mutate(PoB = dplyr::recode(MN18,
                        "11" = "1",
                        "12" = "1",
                        "21" = "2",
                        "22" = "2",
                        "26" = "2",
                        "31" = "3",
                        "32" = "3",
                        "33" = "3",
                        "36" = "3",
                        "96" = "3"
                        )) -> mics4.ch_b1
mics4.ch_b1 %>% count(MN18, PoB)



mics4.ch_b1 %>% mutate(ANC_T = if_else(MN3 >= 1 & MN3 <=3 | MN3 == 98, 1,
                                        if_else(MN3 >= 4 & MN3 <= 6, 2, 3
                                       ))) -> mics4.ch_b1
mics4.ch_b1 %>% count(MN3, ANC_T)


mics4.ch_b1 %>% count(MN18_1)

mics4.ch_b1 %>% count(MN2A, MN2B, MN2C, MN2F, MN2G, MN2X)
mics4.ch_b1 %>% count(MN1, MN2A)


# changing variable MN2 into categories

mics4.ch_b1 %>% count(MN2A, MN2B, MN2C, MN2F, MN2G, MN2X)
mics4.ch_b1 %>% count(MN1, MN2A)

mics4.ch_b1 %>% 
  unite(ANC_W, c(MN1, MN2A, MN2B), sep = "_", remove = FALSE, na.rm = FALSE) -> mics4.ch_b1

mics4.ch_b1 %>% replace_with_na(replace = list(ANC_W = "NA_NA_NA")) -> mics4.ch_b1
mics4.ch_b1 %>% replace_with_na(replace = list(ANC_W = "NA__")) -> mics4.ch_b1


mics4.ch_b1 %>% mutate(ANC_W = recode(ANC_W,
                                     "1_?_?" = 3,
                                     "1__" = 3,
                                     "1__B" = 2,
                                     "1_A_" = 1,
                                     "1_A_B" = 1,
                                     "2__" = 0,
                                     "9__" = 0)) -> mics4.ch_b1
mics4.ch_b1 %>% count(ANC_W)


```





```{r changing to factor}
# changing variables into factors

# data b1
mics4.ch_b1$HH7R <- as.factor(mics4.ch_b1$HH7R)
mics4.ch_b1$HH6 <- as.factor(mics4.ch_b1$HH6)
mics4.ch_b1$windex5 <- as.factor(mics4.ch_b1$windex5)
mics4.ch_b1$HL4 <- as.factor(mics4.ch_b1$HL4)
mics4.ch_b1$ethnicity <- as.factor(mics4.ch_b1$ethnicity)
mics4.ch_b1$melevel <- as.factor(mics4.ch_b1$melevel)
mics4.ch_b1$ethnicity_r <- as.factor(mics4.ch_b1$ethnicity_r)
mics4.ch_b1$melevel_r <- as.factor(mics4.ch_b1$melevel_r)
mics4.ch_b1$PoB <- as.factor(mics4.ch_b1$PoB)
mics4.ch_b1$ANC <- as.factor(mics4.ch_b1$ANC)
mics4.ch_b1$ANC_W <- as.factor(mics4.ch_b1$ANC_W)
mics4.ch_b1$ANC_T <- as.factor(mics4.ch_b1$ANC_T)

mics4.ch_b1$hepb0_RC_2 <- as.factor(mics4.ch_b1$hepb0_RC_2)
mics4.ch_b1$hepb0_RC_24 <- as.factor(mics4.ch_b1$hepb0_RC_24)
mics4.ch_b1$hepb0_C_2 <- as.factor(mics4.ch_b1$hepb0_C_2)
mics4.ch_b1$hepb0_C_24 <- as.factor(mics4.ch_b1$hepb0_C_24)
mics4.ch_b1$hepb0_R_2 <- as.factor(mics4.ch_b1$hepb0_R_2)
mics4.ch_b1$hepb0_R_24 <- as.factor(mics4.ch_b1$hepb0_R_24)



```





### Survey design b1


```{r survey design}
# Make design for hepb0 with selected children aged under 3: n = 6573

mics_design_b1 <- svydesign(data = mics4.ch_b1, 
                         weights = ~chweight, 
                         id = ~strata+HH1)


```


### Descriptive analysis


```{r descriptive}


# taking survey design into account 

# What are interesting things to explore in the dataset?

# Province
# Area
# Direction?
# Wealth score
# melevel education mother
# Age
# Ethnicity

tab <- svytable(~ethnicity, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab

tab <- svytable(~melevel, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab
  
tab <- svytable(~HL4, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab 

tab <- svytable(~windex5, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab

tab <- svytable(~HH6, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab

tab <- svytable(~HH7R, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab

 
# combination of independent variables in graphs

svytable(~ethnicity + HH7R, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=ethnicity, y=Freq, fill = HH7R)) +
  geom_col(position = "fill") +
  coord_flip()


svytable(~ethnicity + windex5, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=ethnicity, y=Freq, fill = windex5)) +
  geom_col(position = "fill") +
  coord_flip()


svytable(~melevel + HH6, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=melevel, y=Freq, fill = HH6)) +
  geom_col(position = "fill") +
  coord_flip()


svytable(~melevel + HH7R, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=melevel, y=Freq, fill = HH7R)) +
  geom_col(position = "fill") +
  coord_flip()


svytable(~melevel + windex5, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=melevel, y=Freq, fill = windex5)) +
  geom_col(position = "fill") +
  coord_flip()

# Pretty much all looks like you would expect



# Age should not give too many surprises?
svytable(~AG2 + HH7R, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=AG2, y=Freq, fill = HH7R)) +
  geom_col(position = "fill") +
  coord_flip()

svytable(~ethnicity + AG2, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=ethnicity, y=Freq, fill = AG2)) +
  geom_col(position = "fill") +
  coord_flip()

svytable(~HL4 + AG2, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=HL4, y=Freq, fill = AG2)) +
  geom_col(position = "fill") +
  coord_flip()


# Vaccination documents


```




```{r anc}
# place of delivery: PoB
mics4.ch_b1 %>% count(PoB)
tab <- svytable(~PoB, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab

# received antenatal care: ANC
tab <- svytable(~ANC, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab

# times received antenatal care: MN3
tab <- svytable(~ANC_T, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab

# antenatal care provider MN2
mics4.ch_b1 %>% count(ANC_W)

tab <- svytable(~ANC_W, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab


```



```{r descriptives dependent variables}

tab <- svytable(~hepb0_RC_2, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab 

tab <- svytable(~hepb0_RC_24, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab 

tab <- svytable(~hepb0_C_2, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab

tab <- svytable(~hepb0_C_24, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab 

tab <- svytable(~hepb0_R_2, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab 

tab <- svytable(~hepb0_R_24, design = mics_design_b1) %>%
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab 

```



### Bivariate analysis - Inference


```{r inference hepb0}

# Looking at association between independent and dependent variables:
# HH7R, HH6, windex5, HL4, ethnicity, melevel, PoB, ANC, MN2, ANC_T
# Using design b1: first combination card and recall variable: hepb0_RC_2, hepb0_RC_24


# survey design graphs
## hepb0_RC_2

svytable(~hepb0_RC_2 + HH6, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=hepb0_RC_2, y=Freq, fill = HH6)) +
  geom_col(position = "fill") 

svytable(~hepb0_RC_2 + HH7R, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=hepb0_RC_2, y=Freq, fill = HH7R)) +
  geom_col(position = "fill") 

svytable(~hepb0_RC_2 + windex5, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=hepb0_RC_2, y=Freq, fill = windex5)) +
  geom_col(position = "fill") 

svytable(~hepb0_RC_2 + HL4, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=hepb0_RC_2, y=Freq, fill = HL4)) +
  geom_col(position = "fill") 

svytable(~hepb0_RC_2 + ethnicity, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=hepb0_RC_2, y=Freq, fill = ethnicity)) +
  geom_col(position = "fill") 

svytable(~hepb0_RC_2 + melevel, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=hepb0_RC_2, y=Freq, fill = melevel)) +
  geom_col(position = "fill") 

svytable(~hepb0_RC_2 + PoB, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=hepb0_RC_2, y=Freq, fill = PoB)) +
  geom_col(position = "fill") 

svytable(~hepb0_RC_2 + ANC, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=hepb0_RC_2, y=Freq, fill = ANC)) +
  geom_col(position = "fill") 

svytable(~hepb0_RC_2 + ANC_W, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=hepb0_RC_2, y=Freq, fill = ANC_W)) +
  geom_col(position = "fill") 

svytable(~hepb0_RC_2 + ANC_T, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=hepb0_RC_2, y=Freq, fill = ANC_T)) +
  geom_col(position = "fill") 


## hepb0_RC_24

svytable(~hepb0_RC_24 + HH6, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=hepb0_RC_24, y=Freq, fill = HH6)) +
  geom_col(position = "fill") 

svytable(~hepb0_RC_24 + HH7R, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=hepb0_RC_24, y=Freq, fill = HH7R)) +
  geom_col(position = "fill") 

svytable(~hepb0_RC_24 + windex5, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=hepb0_RC_24, y=Freq, fill = windex5)) +
  geom_col(position = "fill") 

svytable(~hepb0_RC_24 + HL4, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=hepb0_RC_24, y=Freq, fill = HL4)) +
  geom_col(position = "fill") 

svytable(~hepb0_RC_24 + ethnicity, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=hepb0_RC_24, y=Freq, fill = ethnicity)) +
  geom_col(position = "fill") 

svytable(~hepb0_RC_24 + melevel, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=hepb0_RC_24, y=Freq, fill = melevel)) +
  geom_col(position = "fill") 

svytable(~hepb0_RC_24 + PoB, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=hepb0_RC_24, y=Freq, fill = PoB)) +
  geom_col(position = "fill") 

svytable(~hepb0_RC_24 + ANC, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=hepb0_RC_24, y=Freq, fill = ANC)) +
  geom_col(position = "fill") 

svytable(~hepb0_RC_24 + ANC_W, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=hepb0_RC_24, y=Freq, fill = ANC_W)) +
  geom_col(position = "fill") 

svytable(~hepb0_RC_24 + ANC_T, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=hepb0_RC_24, y=Freq, fill = ANC_T)) +
  geom_col(position = "fill") 



# H0: hepb0 coverage not associated with independent variables
# H1: hepb0 coverage associated with independent variables
svychisq(~hepb0_RC_2 + HH6, design = mics_design_b1, statistic = "Chisq") 
svychisq(~hepb0_RC_2 + HH7R, design = mics_design_b1, statistic = "Chisq") #ns
svychisq(~hepb0_RC_2 + windex5, design = mics_design_b1, statistic = "Chisq") 
svychisq(~hepb0_RC_2 + HL4, design = mics_design_b1, statistic = "Chisq") #ns
svychisq(~hepb0_RC_2 + ethnicity, design = mics_design_b1, statistic = "Chisq") 
svychisq(~hepb0_RC_2 + melevel, design = mics_design_b1, statistic = "Chisq") 
svychisq(~hepb0_RC_2 + PoB, design = mics_design_b1, statistic = "Chisq") 
svychisq(~hepb0_RC_2 + ANC, design = mics_design_b1, statistic = "Chisq") 
svychisq(~hepb0_RC_2 + ANC_W, design = mics_design_b1, statistic = "Chisq") 
svychisq(~hepb0_RC_2 + ANC_T, design = mics_design_b1, statistic = "Chisq")

# H0: hepb0 coverage within 24 hours not associated with independent variables
# H1: hepb0 coverage within 24 hours associated with independent variables
svychisq(~hepb0_RC_24 + HH6, design = mics_design_b1, statistic = "Chisq") 
svychisq(~hepb0_RC_24 + HH7R, design = mics_design_b1, statistic = "Chisq") #ns
svychisq(~hepb0_RC_24 + windex5, design = mics_design_b1, statistic = "Chisq") 
svychisq(~hepb0_RC_24 + HL4, design = mics_design_b1, statistic = "Chisq") # ns
svychisq(~hepb0_RC_24 + ethnicity, design = mics_design_b1, statistic = "Chisq") 
svychisq(~hepb0_RC_24 + melevel, design = mics_design_b1, statistic = "Chisq") 
svychisq(~hepb0_RC_24 + PoB, design = mics_design_b1, statistic = "Chisq") 
svychisq(~hepb0_RC_24 + ANC, design = mics_design_b1, statistic = "Chisq") 
svychisq(~hepb0_RC_24 + ANC_W, design = mics_design_b1, statistic = "Chisq") 
svychisq(~hepb0_RC_24 + ANC_T, design = mics_design_b1, statistic = "Chisq")



svytable(~hepb0_RC_2 + HH6, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=hepb0_RC_2, y=Freq, fill = HH6)) +
  geom_col(position = "fill") 


# H0: hepb0 coverage not associated with area
# H1: hepb0 coverage associated with area
svychisq(~hepb0_RC_2 + HH6, design = mics_design_b1, statistic = "Chisq") 

# does work: Pearson's X^2: Rao & Scott adjustment
# data:  svychisq(~hepb0_RC_2 + HH6, design = mics_design_b1, statistic = "Chisq")
# X-squared = 347.37, df = 2, p-value = 0.000052




# Getting summary statistics while accounting for survey design

# what would be a numeric variable??
# UF11
svymean(~UF11, design = mics_design_b1, na.rm=TRUE)
#       mean     SE
# UF11 2.0415 0.016

svyquantile(x = ~UF11, design = mics_design_b1, na.rm=TRUE, quantiles = 0.5) # 2



svyby(formula = ~UF11, 
      by = ~HH7,
      design = mics_design_b1,
      FUN = svymean, na.rm = TRUE,
      keep.names = FALSE) -> tab
ggplot(data = tab, mapping = aes(x = HH7, y = UF11)) +  
  geom_col() + 
  labs(y = "mean age", x = "Province") # looks terrible


# with error bars

tab <- mutate(tab, lower = UF11 - se, upper = UF11 + se)
tab

ggplot(data = tab, mapping = aes(x = HH7, y = UF11, ymin = lower, ymax = upper)) +  
  geom_col() + 
  geom_errorbar(width = 2) +
  labs(y = "mean age", x = "Province") # looks terrible # Error bars


# Inference
svyttest(formula = UF11 ~ HH6, design = mics_design_b1) # p-value = 0.4025


```


```{r odds ratio hepb0}
class(mics4.ch_b1$hepb0_RC_2)
class(mics4.ch_b1$HH6)


#hepb0 yes/no
summ(svyglm(hepb0_RC_2 ~HH6, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)
summ(svyglm(hepb0_RC_2 ~HH7R, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)
summ(svyglm(hepb0_RC_2 ~windex5, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)
summ(svyglm(hepb0_RC_2 ~HL4, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)
summ(svyglm(hepb0_RC_2 ~ethnicity, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)
summ(svyglm(hepb0_RC_2 ~melevel, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)
summ(svyglm(hepb0_RC_2 ~ethnicity_r, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)
summ(svyglm(hepb0_RC_2 ~melevel_r, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)
summ(svyglm(hepb0_RC_2 ~PoB, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)
summ(svyglm(hepb0_RC_2 ~ANC, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)
summ(svyglm(hepb0_RC_2 ~ANC_W, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)
summ(svyglm(hepb0_RC_2 ~ANC_T, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)

#hep0 within 24 hours
summ(svyglm(hepb0_RC_24 ~HH6, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)
summ(svyglm(hepb0_RC_24 ~HH7R, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)
summ(svyglm(hepb0_RC_24 ~windex5, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)
summ(svyglm(hepb0_RC_24 ~HL4, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)
summ(svyglm(hepb0_RC_24 ~ethnicity, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)
summ(svyglm(hepb0_RC_24 ~melevel, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)
summ(svyglm(hepb0_RC_24 ~ethnicity_r, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)
summ(svyglm(hepb0_RC_24 ~melevel_r, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)
summ(svyglm(hepb0_RC_24 ~PoB, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)
summ(svyglm(hepb0_RC_24 ~ANC, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)
summ(svyglm(hepb0_RC_24 ~ANC_W, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)
summ(svyglm(hepb0_RC_24 ~ANC_T, design = mics_design_b1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 4)


```

### Multivariate analysis

```{r hepb0 multivariate}


full <- svyglm(hepb0_RC_2 ~HH6 + windex5 + ethnicity_r + melevel_r + ANC + ANC_W + PoB + HL4 + HH7R, design = mics_design_b1, family = quasibinomial())

null <- svyglm(hepb0_RC_2 ~ 1, design = mics_design_b1, family = quasibinomial())

anova(full,null, test="Chisq") 


# test correlation between variables 
m <- vcov(full)
mcor <- cov2cor(m)
mcor

stepAIC(full)

psrsq(full, method = "Nagelkerke")
psrsq(full, method = "Cox-Snell")
psrsq(full, method = c("Cox-Snell", "Nagelkerke"))

# best predicted model

BPM <- svyglm(formula = hepb0_RC_2 ~ HH6 + windex5 + ethnicity_r + 
    melevel_r + ANC, design = mics_design_b1, family = quasibinomial())

summ(BPM, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE)


# other possible models ANC varied

A <- svyglm(hepb0_RC_2 ~HH6 + windex5 + ethnicity_r + melevel_r + ANC, design = mics_design_b1, family = quasibinomial())

B <- svyglm(hepb0_RC_2 ~HH6 + windex5 + ethnicity_r + melevel_r + ANC_T, design = mics_design_b1, family = quasibinomial())

C <- svyglm(hepb0_RC_2 ~HH6 + windex5 + ethnicity_r + melevel_r + ANC + ANC_W, design = mics_design_b1, family = quasibinomial())

D <- svyglm(hepb0_RC_2 ~HH6 + windex5 + ethnicity_r + melevel_r + PoB, design = mics_design_b1, family = quasibinomial())

E <- svyglm(hepb0_RC_2 ~HH6 + windex5 + ethnicity_r + melevel_r + ANC_W, design = mics_design_b1, family = quasibinomial())

summ(A, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )
summ(B, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )
summ(C, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )
summ(D, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )
summ(E, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )


# other possible models independent variables varied

A <- svyglm(hepb0_RC_2 ~HH6 + windex5 + ethnicity_r + ANC, design = mics_design_b1, family = quasibinomial())

B <- svyglm(hepb0_RC_2 ~HH6 + windex5 + melevel_r + ANC, design = mics_design_b1, family = quasibinomial())

C <- svyglm(hepb0_RC_2 ~HH6 + ethnicity_r + melevel_r + ANC, design = mics_design_b1, family = quasibinomial())

D <- svyglm(hepb0_RC_2 ~ windex5 + ethnicity_r + melevel_r + ANC, design = mics_design_b1, family = quasibinomial())

summ(A, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )
summ(B, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )
summ(C, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )
summ(D, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )

```



```{r hepb0 within 24 hours multivariate}

full <- svyglm(hepb0_RC_24 ~HH6 + windex5 + ethnicity_r + melevel_r + ANC + ANC_W + PoB + HL4 + HH7R, design = mics_design_b1, family = quasibinomial())

null <- svyglm(hepb0_RC_24 ~ 1, design = mics_design_b1, family = quasibinomial())

anova(full,null, test="Chisq") 


# test correlation between variables 
m <- vcov(full)
mcor <- cov2cor(m)
mcor

stepAIC(full, direction = 'backward')

psrsq(full, method = "Nagelkerke")
psrsq(full, method = "Cox-Snell")
psrsq(full, method = c("Cox-Snell", "Nagelkerke"))

# best predicted model

BPM <- svyglm(formula = hepb0_RC_24 ~ HH6 + windex5 + ethnicity_r + 
    melevel_r + ANC, design = mics_design_b1, family = quasibinomial())

summ(BPM, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE)


# other possible models ANC varied

A <- svyglm(hepb0_RC_24 ~HH6 + windex5 + ethnicity_r + melevel_r + ANC, design = mics_design_b1, family = quasibinomial())

B <- svyglm(hepb0_RC_24 ~HH6 + windex5 + ethnicity_r + melevel_r + ANC_T, design = mics_design_b1, family = quasibinomial())

C <- svyglm(hepb0_RC_24 ~HH6 + windex5 + ethnicity_r + melevel_r + ANC + ANC_W, design = mics_design_b1, family = quasibinomial())

D <- svyglm(hepb0_RC_24 ~HH6 + windex5 + ethnicity_r + melevel_r + PoB, design = mics_design_b1, family = quasibinomial())

E <- svyglm(hepb0_RC_24 ~HH6 + windex5 + ethnicity_r + melevel_r + ANC_W, design = mics_design_b1, family = quasibinomial())

summ(A, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )
summ(B, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )
summ(C, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )
summ(D, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )
summ(E, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )


# other possible models independent variables varied

A <- svyglm(hepb0_RC_24 ~HH6 + windex5 + ethnicity_r + ANC, design = mics_design_b1, family = quasibinomial())

B <- svyglm(hepb0_RC_24 ~HH6 + windex5 + melevel_r + ANC, design = mics_design_b1, family = quasibinomial())

C <- svyglm(hepb0_RC_24 ~HH6 + ethnicity_r + melevel_r + ANC, design = mics_design_b1, family = quasibinomial())

D <- svyglm(hepb0_RC_24 ~ windex5 + ethnicity_r + melevel_r + ANC, design = mics_design_b1, family = quasibinomial())

summ(A, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )
summ(B, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )
summ(C, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )
summ(D, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )

```

```{r mixed model}

#bi_1 <- mix(hepb0_RC_2 ~ HH6 + (1|HH_id),data=mics4.ch_b1,
#family=binomial(link="logit"),verbose=FALSE,
#weights=c("chweight"),nQuad=13)

```




## mics4_p1



### New variables

```{r pentavalent 1}



# Penta 1 Only Card

mics4.ch_p1 %>% count(IM3H1D)

#change date variables into categorical variables
mics4.ch_p1 %>% mutate(penta1_C = if_else(IM3H1D <= 31 & IM3H1D >=1, 1,
                                        if_else(IM3H1D == 0, 0,
                                        if_else(IM3H1D == 44, 44,
                                        if_else(IM3H1D == 99, 99, 66))))) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_C)

mics4.ch_p1 %>% 
  mutate(penta1_C = recode(penta1_C,
                           "44" = "1",
                           "66" = "66",
                           "99" = "0",
                           "1" = "1",
                           "0" = "0"
                           )) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_C)

# 66 needs to be replaced with NA because this is recall info and not card info
# penta1_C_1: only card variable
mics4.ch_p1$penta1_C_1 <- mics4.ch_p1$penta1_C
mics4.ch_p1 %>% replace_with_na(replace = list(penta1_C_1 = "66")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_C_1)


# Penta 1 only recall



# First recode IM11 into penta1_R: recall variable

mics4.ch_p1 %>% count(IM11)
mics4.ch_p1$IM11_2 <- as.factor(mics4.ch_p1$IM11)

mics4.ch_p1 %>% 
  mutate(penta1_R = recode(IM11_2,
                           "1" = "R_1",
                           "2" = "R_0",
                           "8" = "R_8")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_R)

mics4.ch_p1 %>% count(penta1_R, IM5, IM6, penta1_C)
mics4.ch_p1 %>% count(IM6, penta1_C)


# It is not yet correct
# In IM6; if all responses were "NO"; there was no probing for the recall of vaccinations
# Therefore; some of the NAs in the new variable need to be changed to "No" or "DK" #564 no and #11 DK and 3 missing


mics4.ch_p1 %>% 
  mutate(penta1_R = replace(penta1_R, is.na(penta1_R) & IM6 == 2, "R_0"))  %>%
  mutate(penta1_R = replace(penta1_R, is.na(penta1_R) & IM6 == 8, "R_8")) %>%
  mutate(penta1_R = replace(penta1_R, is.na(penta1_R) & IM6 == 9, "R_0")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_R)


# combine Recall and Card

mics4.ch_p1 %>% count(penta1_R, penta1_C)
mics4.ch_p1 %>% mutate(penta1_RC = coalesce(penta1_R, penta1_C)) -> mics4.ch_p1 
mics4.ch_p1 %>% count(penta1_RC)

# Now, all responses should be categorized correctly !!!
# Except for R_8 -> R_0 # and 66 -> which should be categorized as recall, mother reported that there was a vaccination but not sure whether within 24 hours 

mics4.ch_p1 %>% 
  mutate(penta1_R_1 = recode(penta1_RC,
                            "66" = "R_1",
                           "R_0" = "R_0",
                           "R_1" = "R_1",
                           "R_8" = "R_0"
                           )) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_R_1)

# all outcomes from card RC need to be replaced with NA to only retain recall
mics4.ch_p1 %>% replace_with_na(replace = list(penta1_R_1 = c("0", "1"))) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_R_1)

# combination recall and card
mics4.ch_p1 %>%
  mutate(penta1_RC_1 = recode(penta1_RC,
                              "0" = 0,
                              "1" = 1,
                              "66" = 1,
                              "R_0" = 0,
                              "R_1" = 1,
                              "R_8" = 0
                              )) -> mics4.ch_p1

mics4.ch_p1 %>% count(penta1_RC_1) # 0: 940 1: 3374
mics4.ch_p1 %>% count(penta1_R_1) # 0: 867 1: 1605
mics4.ch_p1 %>% count(penta1_C_1) # 0: 73 1: 1769

# new variables



```


```{r pentavalent 2}


# Penta 2 Only Card

mics4.ch_p1 %>% count(IM3H2D)

#change date variables into categorical variables
mics4.ch_p1 %>% mutate(penta2_C = if_else(IM3H2D <= 31 & IM3H2D >=1, 1,
                                        if_else(IM3H2D == 0, 0,
                                        if_else(IM3H2D == 44, 44,
                                        if_else(IM3H2D == 99, 99, 66))))) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_C)

mics4.ch_p1 %>% 
  mutate(penta2_C = recode(penta2_C,
                           "44" = "1",
                           "66" = "66",
                           "99" = "0",
                           "1" = "1",
                           "0" = "0"
                           )) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_C)

# 66 needs to be replaced with NA because this is recall info and not card info
# penta2_C_1: only card variable
mics4.ch_p1$penta2_C_1 <- mics4.ch_p1$penta2_C
mics4.ch_p1 %>% replace_with_na(replace = list(penta2_C_1 = "66")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_C_1)


# Penta 2 only recall



# First recode IM11 into penta2_R: recall variable

mics4.ch_p1 %>% count(IM12)
mics4.ch_p1$IM12_2 <- as.numeric(mics4.ch_p1$IM12)

mics4.ch_p1 %>% 
  mutate(penta2_R = recode(IM12_2,
                           "1" = "R_1",
                           "2" = "R_2",
                           "3" = "R_3",
                           "4" = "R_4",
                           "5" = "R_5",
                           "6" = "R_6",
                           "7" = "R_7",
                           "8" = "R_8",
                           "9" = "R_9")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_R)

# mics4.ch_p1 %>% count(penta2_R, IM5, IM6, penta2_C)
# mics4.ch_p1 %>% count(IM6, penta2_C)

# It is not yet correct
# In IM6; if all responses were "NO"; there was no probing for the recall of vaccinations
# Therefore; some of the NAs in the new variable need to be changed to "No" or "DK" #564 no and #11 DK and 3 missing


mics4.ch_p1 %>% 
  mutate(penta2_R = replace(penta2_R, is.na(penta2_R) & IM6 == 2, "R_0"))  %>%
  mutate(penta2_R = replace(penta2_R, is.na(penta2_R) & IM6 == 8, "R_8")) %>%
  mutate(penta2_R = replace(penta2_R, is.na(penta2_R) & IM6 == 9, "R_9")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_R) 
mics4.ch_p1 %>% count(penta1_R)


# make a new variable combining IM20 and IM21. 
# IM 21: 2,3,4,5,6 of 7 means having the second pentavalent vaccine, IM21: 1,8 or 9 had only one or dont know whether they had one pentavalent vaccine or more, therefore do not include them assign to 0 together with IM20 No and DK = penta1_R.

mics4.ch_p1 %>% count(penta2_R, penta1_R)
mics4.ch_p1 %>% mutate(penta2_R_3 = coalesce(penta2_R, penta1_R)) -> mics4.ch_p1 
mics4.ch_p1 %>% count(penta2_R_3)

# Recode recall variable penta 2 into yes or no

mics4.ch_p1 %>% 
  mutate(penta2_R_2 = recode(penta2_R_3,
                           "R_0" = "R_0",
                           "R_1" = "R_0",
                           "R_2" = "R_1",
                           "R_3" = "R_1",
                           "R_4" = "R_1",
                           "R_5" = "R_1",
                           "R_6" = "R_1",
                           "R_7" = "R_1",
                           "R_8" = "R_0",
                           "R_9" = "R_0"
                           )) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_R_2)

# combine Recall and Card

mics4.ch_p1 %>% mutate(penta2_RC = coalesce(penta2_R_2, penta2_C)) -> mics4.ch_p1 
mics4.ch_p1 %>% count(penta2_RC)

# Now, all responses should be categorized correctly !!!
# Except for R_8 -> R_0 # and 66 -> which should be categorized as recall, mother reported that there was a vaccination but not sure whether within 24 hours 

mics4.ch_p1 %>% 
  mutate(penta2_R_1 = recode(penta2_RC,
                            "66" = "R_1",
                           "R_0" = "R_0",
                           "R_1" = "R_1")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_R_1)

# all outcomes from card RC need to be replaced with NA to only retain recall
mics4.ch_p1 %>% replace_with_na(replace = list(penta2_R_1 = c("0", "1"))) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_R_1)

# combination recall and card
mics4.ch_p1 %>%
  mutate(penta2_RC_1 = recode(penta2_RC,
                              "0" = 0,
                              "1" = 1,
                              "66" = 1,
                              "R_0" = 0,
                              "R_1" = 1)) -> mics4.ch_p1

mics4.ch_p1 %>% count(penta2_RC_1) # 0: 1360 1: 2954
mics4.ch_p1 %>% count(penta2_R_1) # 0: 1186 1: 1298
mics4.ch_p1 %>% count(penta2_C_1) # 0: 174 1: 1656


```



```{r pentavalent 3}


# Penta 3 Only Card

mics4.ch_p1 %>% count(IM3H3D)

#change date variables into categorical variables
mics4.ch_p1 %>% mutate(penta3_C = if_else(IM3H3D <= 31 & IM3H3D >=1, 1,
                                        if_else(IM3H3D == 0, 0,
                                        if_else(IM3H3D == 44, 44,   
                                        if_else(IM3H3D == 66, 66, 99))))) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta3_C)

mics4.ch_p1 %>% 
  mutate(penta3_C = recode(penta3_C,
                           "44" = "1",
                           "66" = "66",
                           "99" = "0",
                           "1" = "1",
                           "0" = "0"
                           )) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta3_C)

# 66 needs to be replaced with NA because this is recall info and not card info

mics4.ch_p1$penta3_C_1 <- mics4.ch_p1$penta3_C
mics4.ch_p1 %>% replace_with_na(replace = list(penta3_C_1 = "66")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta3_C_1)


# Penta 2 only recall

mics4.ch_p1 %>% count(IM11, IM12, IM5, IM6)
mics4.ch_p1 %>% count(IM11, IM12, IM6)




# First recode IM12 into penta3_R: recall variable

mics4.ch_p1$IM12 <- as.factor(mics4.ch_p1$IM12)

mics4.ch_p1 %>% count(IM12)
mics4.ch_p1 %>% 
  mutate(penta3_R = recode(IM12,
                           "1" = "R_1",
                           "2" = "R_2",
                           "3" = "R_3",
                           "4" = "R_4",
                           "5" = "R_5",
                           "6" = "R_6",
                           "7" = "R_7",
                           "8" = "R_8",
                           "9" = "R_9")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta3_R)


mics4.ch_p1 %>% count(penta3_R, IM11, IM5, IM6)

# It is not yet correct
# In IM11 & IM12; if all responses were "NO"; there was no probing for the recall of vaccinations
# Therefore; some of the NAs in the new variable need to be changed to "No" or "DK" #564 no and #11 DK and # 3 missing values. 

mics4.ch_p1 %>% 
  mutate(penta3_R = replace(penta3_R, is.na(penta3_R) & IM6 == 2, "R_0"))  %>%
  mutate(penta3_R = replace(penta3_R, is.na(penta3_R) & IM6 == 8, "R_8")) %>%
  mutate(penta3_R = replace(penta3_R, is.na(penta3_R) & IM6 == 9, "R_9"))-> mics4.ch_p1
 mics4.ch_p1 %>% count(penta3_R)


# make a new variable combining IM11 and IM12. 
# IM 21: 2,3,4,5,6 of 7 means having the second pentavalent vaccine, IM21: 1,8 or 9 had only one or dont know whether they had one pentavalent vaccine or more, therefore do not include them assign to 0 together with IM20 No and DK.
mics4.ch_p1 %>% count(penta3_R, penta1_R)
mics4.ch_p1 %>% mutate(penta3_R_3 = coalesce(penta3_R, penta1_R)) -> mics4.ch_p1 
mics4.ch_p1 %>% count(penta3_R_3)

# Recode recall variable penta3 into yes or no

mics4.ch_p1 %>% 
  mutate(penta3_R_2 = recode(penta3_R_3,
                           "R_0" = "R_0",
                           "R_1" = "R_0",
                           "R_2" = "R_0",
                           "R_3" = "R_1",
                           "R_4" = "R_1",
                           "R_5" = "R_1",
                           "R_6" = "R_1",
                           "R_7" = "R_1",
                           "R_8" = "R_0",
                           "R_9" = "R_0"
                           )) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta3_R_2)


# combine Recall and Card

mics4.ch_p1 %>% mutate(penta3_RC = coalesce(penta3_R_2, penta3_C)) -> mics4.ch_p1 
mics4.ch_p1 %>% count(penta3_RC)

# Now, all responses should be categorized correctly!
# Except for 66 -> which should be categorized as recall (R_1), mother reported that there was a vaccination 

mics4.ch_p1 %>% 
  mutate(penta3_R_1 = recode(penta3_RC,
                            "66" = "R_1",
                           "R_0" = "R_0",
                           "R_1" = "R_1"                                                       )) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta3_R_1)

# all outcomes from card RC need to be replaced with NA to only retain recall
mics4.ch_p1 %>% replace_with_na(replace = list(penta3_R_1 = c("0", "1"))) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta3_R_1)



# categorize combination recall and card into dichotomous variable
mics4.ch_p1 %>%
  mutate(penta3_RC_1 = recode(penta3_RC,
                              "0" = 0,
                              "1" = 1,
                              "66" = 1,
                              "R_0" = 0,
                              "R_1" = 1
                                       )) -> mics4.ch_p1

mics4.ch_p1 %>% count(penta3_RC_1) # 0: 1893 1: 2421
mics4.ch_p1 %>% count(penta3_R_1) # 0: 1552 1: 955
mics4.ch_p1 %>% count(penta3_C_1) # 0: 341  1: 1466





```



```{r penta 123}

# check if they got all 3 vaccinations, not only second or third. 

mics4.ch_p1 %>% count(penta1_R_1, penta2_R_1, penta3_R_1)
mics4.ch_p1 %>% count(penta1_C_1, penta2_C_1, penta3_C_1, penta1_C)
mics4.ch_p1 %>% count(penta1_RC_1, penta2_RC_1, penta3_RC_1)
mics4.ch_p1 %>% count(penta1_R_1, penta2_R_1, penta3_R_1, penta2_RC, penta3_RC)



# new variables at least one vaccine

# new variable penta1 got at least one vaccinations according to card
mics4.ch_p1 %>% mutate(penta1_C = if_else(penta1_C_1 == 1 | penta2_C_1 == 1 | penta3_C_1 == 1, 1, 0)) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_C)

# new variable penta1 got at least one vaccinations according to card or recall
mics4.ch_p1 %>% mutate(penta1_RC = if_else(penta1_RC_1 == 1 | penta2_RC_1 == 1 | penta3_RC_1 == 1, 1, 0)) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_RC)


mics4.ch_p1$penta1_R <- mics4.ch_p1$penta1_R_1


mics4.ch_p1 %>% count(penta1_RC)
mics4.ch_p1 %>% count(penta1_R) 
mics4.ch_p1 %>% count(penta1_C)

# new variable penta12 got at least two vaccinations according to card
mics4.ch_p1 %>% mutate(penta12_C = if_else(penta1_C_1 == 1 & penta2_C_1 == 1, 1,
                                   if_else(penta1_C_1 == 1 & penta3_C_1 == 1, 1,
                                   if_else(penta2_C_1 == 1 & penta3_C_1 == 1, 1, 0)))) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta12_C)

# new variable penta12 got at least two vaccinations according to card or recall
mics4.ch_p1 %>% mutate(penta12_RC = if_else(penta1_RC_1 == 1 & penta2_RC_1 == 1, 1,
                                    if_else(penta1_RC_1 == 1 & penta3_RC_1 == 1, 1,
                                    if_else(penta2_RC_1 == 1 & penta3_RC_1 == 1, 1, 0)))) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta12_RC)

# change name recall at least two 
mics4.ch_p1$penta12_R <- mics4.ch_p1$penta2_R_1


mics4.ch_p1 %>% count(penta12_RC)
mics4.ch_p1 %>% count(penta12_R) 
mics4.ch_p1 %>% count(penta12_C)

# new variable penta123 got at least three vaccinations according to card
mics4.ch_p1 %>% mutate(penta123_C = if_else(penta1_C_1 == 1 & penta2_C_1 == 1 & penta3_C_1 == 1, 1, 0)) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta123_C)

# new variable penta123 got at least three vaccinations according to card or recall
mics4.ch_p1 %>% mutate(penta123_RC = if_else(penta1_RC_1 == 1 & penta2_RC_1 == 1 & penta3_RC_1 == 1, 1, 0)) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta123_RC)

# change names
mics4.ch_p1$penta123_R <- mics4.ch_p1$penta3_R_1

mics4.ch_p1 %>% count(penta123_RC)
mics4.ch_p1 %>% count(penta123_R) 
mics4.ch_p1 %>% count(penta123_C)

```

```{r anc replace 9 with na}

mics4.ch_p1 %>% count(MN18)

mics4.ch_p1 %>% count(MN3)

mics4.ch_p1 %>% count(MN1)

mics4.ch_p1 %>% replace_with_na(replace = list(MN18 = "99")) -> mics4.ch_p1

mics4.ch_p1 %>% replace_with_na(replace = list(MN3 = "99")) -> mics4.ch_p1

mics4.ch_p1 %>% replace_with_na(replace = list(MN1 = "9")) -> mics4.ch_p1


mics4.ch_p1 %>% count(MN18)

mics4.ch_p1 %>% count(MN3)

mics4.ch_p1 %>% count(MN1)

```

```{r anc}

mics4.ch_p1$ANC <- mics4.ch_p1$MN1

mics4.ch_p1 %>% mutate(ANC = recode(ANC,
                                     "1" = 1,
                                     "2" = 0
                                     )) -> mics4.ch_p1

# new variable place of delivery
mics4.ch_p1 %>% mutate(PoB = dplyr::recode(MN18,
                        "11" = "1",
                        "12" = "1",
                        "21" = "2",
                        "22" = "2",
                        "26" = "2",
                        "31" = "3",
                        "32" = "3",
                        "33" = "3",
                        "36" = "3",
                        "96" = "3"
                        )) -> mics4.ch_p1
mics4.ch_p1 %>% count(MN18, PoB)


mics4.ch_p1 %>% mutate(ANC_T = if_else(MN3 >= 1 & MN3 <=3 | MN3 == 98, 1,
                                        if_else(MN3 >= 4 & MN3 <= 6, 2, 3
                                       ))) -> mics4.ch_p1
mics4.ch_p1 %>% count(MN3, ANC_T)

mics4.ch_p1 %>% count(MN2A, MN2B, MN2C, MN2F, MN2G, MN2X)
mics4.ch_p1 %>% count(MN1, MN2A)


# changing variable MN2 into categories

mics4.ch_p1 %>% count(MN2A, MN2B, MN2C, MN2F, MN2G, MN2X)
mics4.ch_p1 %>% count(MN1, MN2A)

mics4.ch_p1 %>% 
  unite(ANC_W, c(MN1, MN2A, MN2B), sep = "_", remove = FALSE, na.rm = FALSE) -> mics4.ch_p1

mics4.ch_p1 %>% replace_with_na(replace = list(ANC_W = "NA_NA_NA")) -> mics4.ch_p1
mics4.ch_p1 %>% replace_with_na(replace = list(ANC_W = "NA__")) -> mics4.ch_p1


mics4.ch_p1 %>% mutate(ANC_W = recode(ANC_W,
                                     "1_?_?" = 3,
                                     "1__" = 3,
                                     "1__B" = 2,
                                     "1_A_" = 1,
                                     "1_A_B" = 1,
                                     "2__" = 0,
                                     "9__" = 0)) -> mics4.ch_p1
mics4.ch_p1 %>% count(ANC_W)


```


```{r changing to factor}
# changing variables into factors

mics4.ch_p1$HH7R <- as.factor(mics4.ch_p1$HH7R)
mics4.ch_p1$HH6 <- as.factor(mics4.ch_p1$HH6)
mics4.ch_p1$windex5 <- as.factor(mics4.ch_p1$windex5)
mics4.ch_p1$HL4 <- as.factor(mics4.ch_p1$HL4)
mics4.ch_p1$ethnicity <- as.factor(mics4.ch_p1$ethnicity)
mics4.ch_p1$melevel <- as.factor(mics4.ch_p1$melevel)
mics4.ch_p1$ethnicity_r <- as.factor(mics4.ch_p1$ethnicity_r)
mics4.ch_p1$melevel_r <- as.factor(mics4.ch_p1$melevel_r)
mics4.ch_p1$PoB <- as.factor(mics4.ch_p1$PoB)
mics4.ch_p1$ANC <- as.factor(mics4.ch_p1$ANC)
mics4.ch_p1$ANC_W <- as.factor(mics4.ch_p1$ANC_W)
mics4.ch_p1$ANC_T <- as.factor(mics4.ch_p1$ANC_T)


mics4.ch_p1$penta1_RC <- as.factor(mics4.ch_p1$penta1_RC)
mics4.ch_p1$penta12_RC <- as.factor(mics4.ch_p1$penta12_RC)
mics4.ch_p1$penta123_RC <- as.factor(mics4.ch_p1$penta123_RC)

mics4.ch_p1$penta1_C <- as.factor(mics4.ch_p1$penta1_C)
mics4.ch_p1$penta12_C <- as.factor(mics4.ch_p1$penta12_C)
mics4.ch_p1$penta123_C <- as.factor(mics4.ch_p1$penta123_C)

mics4.ch_p1$penta1_R <- as.factor(mics4.ch_p1$penta1_R)
mics4.ch_p1$penta12_R <- as.factor(mics4.ch_p1$penta12_R)
mics4.ch_p1$penta123_R <- as.factor(mics4.ch_p1$penta123_R)


```



### survey design p1

```{r survey design}




# Make design for pentavalent with selected children aged under 3 and older than 1 year: n = 4314

mics_design_p1 <- svydesign(data = mics4.ch_p1, 
                         weights = ~chweight, 
                         id = ~strata+HH1)



```


### Descriptive analysis - weighted

```{r descriptive}


# taking survey design into account 

# What are interesting things to explore in the dataset?

# Province
# Area
# Direction?
# Wealth score
# melevel education mother
# Age
# Ethnicity

tab <- svytable(~ethnicity, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab

tab <- svytable(~melevel, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab
  
tab <- svytable(~HL4, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab 

tab <- svytable(~windex5, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab

tab <- svytable(~HH6, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab

tab <- svytable(~HH7R, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab

 
# combination of independent variables in graphs

svytable(~ethnicity + HH7R, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=ethnicity, y=Freq, fill = HH7R)) +
  geom_col(position = "fill") +
  coord_flip()


svytable(~ethnicity + windex5, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=ethnicity, y=Freq, fill = windex5)) +
  geom_col(position = "fill") +
  coord_flip()


svytable(~melevel + HH6, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=melevel, y=Freq, fill = HH6)) +
  geom_col(position = "fill") +
  coord_flip()


svytable(~melevel + HH7R, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=melevel, y=Freq, fill = HH7R)) +
  geom_col(position = "fill") +
  coord_flip()


svytable(~melevel + windex5, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=melevel, y=Freq, fill = windex5)) +
  geom_col(position = "fill") +
  coord_flip()

# Pretty much all looks like you would expect



# Age should not give too many surprises?
svytable(~AG2 + HH7R, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=AG2, y=Freq, fill = HH7R)) +
  geom_col(position = "fill") +
  coord_flip()

svytable(~ethnicity + AG2, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=ethnicity, y=Freq, fill = AG2)) +
  geom_col(position = "fill") +
  coord_flip()

svytable(~HL4 + AG2, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=HL4, y=Freq, fill = AG2)) +
  geom_col(position = "fill") +
  coord_flip()


```




```{r anc}
# place of delivery: ANC8
mics4.ch_p1 %>% count(PoB)
tab <- svytable(~PoB, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab

# received antenatal care: ANC
tab <- svytable(~ANC, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab

# times received antenatal care: MN3
tab <- svytable(~ANC_T, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab

# antenatal care provider MN2
mics4.ch_b1 %>% count(ANC_W, MN2B, MN2C,MN2F, MN2G, MN2X)

tab <- svytable(~ANC_W, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab
tab <- svytable(~MN2B, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab
tab <- svytable(~MN2C, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab
tab <- svytable(~MN2F, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab
tab <- svytable(~MN2G, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab
tab <- svytable(~MN2X, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab

```

```{r dependent variables}

tab <- svytable(~penta1_RC_1, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab 

tab <- svytable(~penta1_R_1, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab 

tab <- svytable(~penta1_C_1, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab

tab <- svytable(~penta2_RC_1, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab 

tab <- svytable(~penta2_R_1, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab 

tab <- svytable(~penta2_C_1, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab 

tab <- svytable(~penta3_RC_1, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab 

tab <- svytable(~penta3_R_1, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab

tab <- svytable(~penta3_C_1, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab 


```




### Bivariate analysis


```{r pentavalent RC}

## penta1_RC

svytable(~penta1_RC + HH6, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_RC, y=Freq, fill = HH6)) +
  geom_col(position = "fill") 

svytable(~penta1_RC + HH7R, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_RC, y=Freq, fill = HH7R)) +
  geom_col(position = "fill") 

svytable(~penta1_RC + windex5, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_RC, y=Freq, fill = windex5)) +
  geom_col(position = "fill") 

svytable(~penta1_RC + HL4, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_RC, y=Freq, fill = HL4)) +
  geom_col(position = "fill") 

svytable(~penta1_RC + ethnicity, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_RC, y=Freq, fill = ethnicity)) +
  geom_col(position = "fill") 

svytable(~penta1_RC + melevel, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_RC, y=Freq, fill = melevel)) +
  geom_col(position = "fill") 

svytable(~penta1_RC + PoB, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_RC, y=Freq, fill = PoB)) +
  geom_col(position = "fill") 

svytable(~penta1_RC + ANC, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_RC, y=Freq, fill = ANC)) +
  geom_col(position = "fill") 

svytable(~penta1_RC + ANC_W, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_RC, y=Freq, fill = ANC_W)) +
  geom_col(position = "fill") 

svytable(~penta1_RC + ANC_T, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_RC, y=Freq, fill = ANC_T)) +
  geom_col(position = "fill") 

# H0: penta1 coverage not associated with independent variables
# H1: penta1 coverage associated with independent variables
svychisq(~penta1_RC + HH6, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta1_RC + HH7R, design = mics_design_p1, statistic = "Chisq") #ns
svychisq(~penta1_RC + windex5, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta1_RC + HL4, design = mics_design_p1, statistic = "Chisq") #ns
svychisq(~penta1_RC + ethnicity, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta1_RC + melevel, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta1_RC + PoB, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta1_RC + ANC, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta1_RC + ANC_W, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta1_RC + ANC_T, design = mics_design_p1, statistic = "Chisq")



## penta12_RC

svytable(~penta12_RC + HH6, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_RC, y=Freq, fill = HH6)) +
  geom_col(position = "fill") 

svytable(~penta12_RC + HH7R, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_RC, y=Freq, fill = HH7R)) +
  geom_col(position = "fill") 

svytable(~penta12_RC + windex5, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_RC, y=Freq, fill = windex5)) +
  geom_col(position = "fill") 

svytable(~penta12_RC + HL4, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_RC, y=Freq, fill = HL4)) +
  geom_col(position = "fill") 

svytable(~penta12_RC + ethnicity, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_RC, y=Freq, fill = ethnicity)) +
  geom_col(position = "fill") 

svytable(~penta12_RC + melevel, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_RC, y=Freq, fill = melevel)) +
  geom_col(position = "fill") 

svytable(~penta12_RC + PoB, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_RC, y=Freq, fill = PoB)) +
  geom_col(position = "fill") 

svytable(~penta12_RC + ANC, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_RC, y=Freq, fill = ANC)) +
  geom_col(position = "fill") 

svytable(~penta12_RC + ANC_W, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_RC, y=Freq, fill = ANC_W)) +
  geom_col(position = "fill") 

svytable(~penta12_RC + ANC_T, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_RC, y=Freq, fill = ANC_T)) +
  geom_col(position = "fill") 

# H0: penta2 coverage not associated with independent variables
# H1: penta2 coverage associated with independent variables
svychisq(~penta12_RC + HH6, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta12_RC + HH7R, design = mics_design_p1, statistic = "Chisq") #ns
svychisq(~penta12_RC + windex5, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta12_RC + HL4, design = mics_design_p1, statistic = "Chisq") #ns
svychisq(~penta12_RC + ethnicity, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta12_RC + melevel, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta12_RC + PoB, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta12_RC + ANC, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta12_RC + ANC_W, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta12_RC + ANC_T, design = mics_design_p1, statistic = "Chisq")



## penta123_RC

svytable(~penta123_RC + HH6, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_RC, y=Freq, fill = HH6)) +
  geom_col(position = "fill") 

svytable(~penta123_RC + HH7R, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_RC, y=Freq, fill = HH7R)) +
  geom_col(position = "fill") 

svytable(~penta123_RC + windex5, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_RC, y=Freq, fill = windex5)) +
  geom_col(position = "fill") 

svytable(~penta123_RC + HL4, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_RC, y=Freq, fill = HL4)) +
  geom_col(position = "fill") 

svytable(~penta123_RC + ethnicity, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_RC, y=Freq, fill = ethnicity)) +
  geom_col(position = "fill") 

svytable(~penta123_RC + melevel, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_RC, y=Freq, fill = melevel)) +
  geom_col(position = "fill") 

svytable(~penta123_RC + PoB, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_RC, y=Freq, fill = PoB)) +
  geom_col(position = "fill") 

svytable(~penta123_RC + ANC, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_RC, y=Freq, fill = ANC)) +
  geom_col(position = "fill") 

svytable(~penta123_RC + ANC_W, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_RC, y=Freq, fill = ANC_W)) +
  geom_col(position = "fill") 

svytable(~penta123_RC + ANC_T, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_RC, y=Freq, fill = ANC_T)) +
  geom_col(position = "fill") 

# H0: penta3 coverage not associated with independent variables
# H1: penta3 coverage associated with independent variables
svychisq(~penta123_RC + HH6, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta123_RC + HH7R, design = mics_design_p1, statistic = "Chisq") #ns
svychisq(~penta123_RC + windex5, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta123_RC + HL4, design = mics_design_p1, statistic = "Chisq") #ns
svychisq(~penta123_RC + ethnicity, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta123_RC + melevel, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta123_RC + PoB, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta123_RC + ANC, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta123_RC + ANC_W, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta123_RC + ANC_T, design = mics_design_p1, statistic = "Chisq")




```




```{r pentavalent C}

## penta1_C

svytable(~penta1_C + HH6, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_C, y=Freq, fill = HH6)) +
  geom_col(position = "fill") 

svytable(~penta1_C + HH7R, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_C, y=Freq, fill = HH7R)) +
  geom_col(position = "fill") 

svytable(~penta1_C + windex5, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_C, y=Freq, fill = windex5)) +
  geom_col(position = "fill") 

svytable(~penta1_C + HL4, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_C, y=Freq, fill = HL4)) +
  geom_col(position = "fill") 

svytable(~penta1_C + ethnicity, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_C, y=Freq, fill = ethnicity)) +
  geom_col(position = "fill") 

svytable(~penta1_C + melevel, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_C, y=Freq, fill = melevel)) +
  geom_col(position = "fill") 

svytable(~penta1_C + PoB, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_C, y=Freq, fill = PoB)) +
  geom_col(position = "fill") 

svytable(~penta1_C + ANC, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_C, y=Freq, fill = ANC)) +
  geom_col(position = "fill") 

svytable(~penta1_C + ANC_W, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_C, y=Freq, fill = ANC_W)) +
  geom_col(position = "fill") 

svytable(~penta1_C + ANC_T, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_C, y=Freq, fill = ANC_T)) +
  geom_col(position = "fill") 

# H0: penta1 coverage not associated with independent variables
# H1: penta1 coverage associated with independent variables
svychisq(~penta1_C + HH6, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta1_C + HH7R, design = mics_design_p1, statistic = "Chisq") #ns
svychisq(~penta1_C + windex5, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta1_C + HL4, design = mics_design_p1, statistic = "Chisq") #ns
svychisq(~penta1_C + ethnicity, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta1_C + melevel, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta1_C + PoB, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta1_C + ANC, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta1_C + ANC_W, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta1_C + ANC_T, design = mics_design_p1, statistic = "Chisq")



## penta12_C

svytable(~penta12_C + HH6, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_C, y=Freq, fill = HH6)) +
  geom_col(position = "fill") 

svytable(~penta12_C + HH7R, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_C, y=Freq, fill = HH7R)) +
  geom_col(position = "fill") 

svytable(~penta12_C + windex5, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_C, y=Freq, fill = windex5)) +
  geom_col(position = "fill") 

svytable(~penta12_C + HL4, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_C, y=Freq, fill = HL4)) +
  geom_col(position = "fill") 

svytable(~penta12_C + ethnicity, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_C, y=Freq, fill = ethnicity)) +
  geom_col(position = "fill") 

svytable(~penta12_C + melevel, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_C, y=Freq, fill = melevel)) +
  geom_col(position = "fill") 

svytable(~penta12_C + PoB, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_C, y=Freq, fill = PoB)) +
  geom_col(position = "fill") 

svytable(~penta12_C + ANC, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_C, y=Freq, fill = ANC)) +
  geom_col(position = "fill") 

svytable(~penta12_C + ANC_W, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_C, y=Freq, fill = ANC_W)) +
  geom_col(position = "fill") 

svytable(~penta12_C + ANC_T, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_C, y=Freq, fill = ANC_T)) +
  geom_col(position = "fill") 

# H0: penta2 coverage not associated with independent variables
# H1: penta2 coverage associated with independent variables
svychisq(~penta12_C + HH6, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta12_C + HH7R, design = mics_design_p1, statistic = "Chisq") #ns
svychisq(~penta12_C + windex5, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta12_C + HL4, design = mics_design_p1, statistic = "Chisq") #ns
svychisq(~penta12_C + ethnicity, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta12_C + melevel, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta12_C + PoB, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta12_C + ANC, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta12_C + ANC_W, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta12_C + ANC_T, design = mics_design_p1, statistic = "Chisq")



## penta123_C

svytable(~penta123_C + HH6, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_C, y=Freq, fill = HH6)) +
  geom_col(position = "fill") 

svytable(~penta123_C + HH7R, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_C, y=Freq, fill = HH7R)) +
  geom_col(position = "fill") 

svytable(~penta123_C + windex5, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_C, y=Freq, fill = windex5)) +
  geom_col(position = "fill") 

svytable(~penta123_C + HL4, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_C, y=Freq, fill = HL4)) +
  geom_col(position = "fill") 

svytable(~penta123_C + ethnicity, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_C, y=Freq, fill = ethnicity)) +
  geom_col(position = "fill") 

svytable(~penta123_C + melevel, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_C, y=Freq, fill = melevel)) +
  geom_col(position = "fill") 

svytable(~penta123_C + PoB, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_C, y=Freq, fill = PoB)) +
  geom_col(position = "fill") 

svytable(~penta123_C + ANC, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_C, y=Freq, fill = ANC)) +
  geom_col(position = "fill") 

svytable(~penta123_C + ANC_W, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_C, y=Freq, fill = ANC_W)) +
  geom_col(position = "fill") 

svytable(~penta123_C + ANC_T, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_C, y=Freq, fill = ANC_T)) +
  geom_col(position = "fill") 

# H0: penta3 coverage not associated with independent variables
# H1: penta3 coverage associated with independent variables
svychisq(~penta123_C + HH6, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta123_C + HH7R, design = mics_design_p1, statistic = "Chisq") #ns
svychisq(~penta123_C + windex5, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta123_C + HL4, design = mics_design_p1, statistic = "Chisq") #ns
svychisq(~penta123_C + ethnicity, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta123_C + melevel, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta123_C + PoB, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta123_C + ANC, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta123_C + ANC_W, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta123_C + ANC_T, design = mics_design_p1, statistic = "Chisq")


```



```{r pentavalent R}

## penta1_R

svytable(~penta1_R + HH6, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_R, y=Freq, fill = HH6)) +
  geom_col(position = "fill") 

svytable(~penta1_R + HH7R, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_R, y=Freq, fill = HH7R)) +
  geom_col(position = "fill") 

svytable(~penta1_R + windex5, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_R, y=Freq, fill = windex5)) +
  geom_col(position = "fill") 

svytable(~penta1_R + HL4, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_R, y=Freq, fill = HL4)) +
  geom_col(position = "fill") 

svytable(~penta1_R + ethnicity, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_R, y=Freq, fill = ethnicity)) +
  geom_col(position = "fill") 

svytable(~penta1_R + melevel, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_R, y=Freq, fill = melevel)) +
  geom_col(position = "fill") 

svytable(~penta1_R + PoB, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_R, y=Freq, fill = PoB)) +
  geom_col(position = "fill") 

svytable(~penta1_R + ANC, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_R, y=Freq, fill = ANC)) +
  geom_col(position = "fill") 

svytable(~penta1_R + ANC_W, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_R, y=Freq, fill = ANC_W)) +
  geom_col(position = "fill") 

svytable(~penta1_R + ANC_T, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta1_R, y=Freq, fill = ANC_T)) +
  geom_col(position = "fill") 

# H0: penta1 coverage not associated with independent variables
# H1: penta1 coverage associated with independent variables
svychisq(~penta1_R + HH6, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta1_R + HH7R, design = mics_design_p1, statistic = "Chisq") #ns
svychisq(~penta1_R + windex5, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta1_R + HL4, design = mics_design_p1, statistic = "Chisq") #ns
svychisq(~penta1_R + ethnicity, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta1_R + melevel, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta1_R + PoB, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta1_R + ANC, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta1_R + ANC_W, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta1_R + ANC_T, design = mics_design_p1, statistic = "Chisq")



## penta12_R

svytable(~penta12_R + HH6, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_R, y=Freq, fill = HH6)) +
  geom_col(position = "fill") 

svytable(~penta12_R + HH7R, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_R, y=Freq, fill = HH7R)) +
  geom_col(position = "fill") 

svytable(~penta12_R + windex5, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_R, y=Freq, fill = windex5)) +
  geom_col(position = "fill") 

svytable(~penta12_R + HL4, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_R, y=Freq, fill = HL4)) +
  geom_col(position = "fill") 

svytable(~penta12_R + ethnicity, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_R, y=Freq, fill = ethnicity)) +
  geom_col(position = "fill") 

svytable(~penta12_R + melevel, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_R, y=Freq, fill = melevel)) +
  geom_col(position = "fill") 

svytable(~penta12_R + PoB, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_R, y=Freq, fill = PoB)) +
  geom_col(position = "fill") 

svytable(~penta12_R + ANC, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_R, y=Freq, fill = ANC)) +
  geom_col(position = "fill") 

svytable(~penta12_R + ANC_W, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_R, y=Freq, fill = ANC_W)) +
  geom_col(position = "fill") 

svytable(~penta12_R + ANC_T, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta12_R, y=Freq, fill = ANC_T)) +
  geom_col(position = "fill") 

# H0: penta2 coverage not associated with independent variables
# H1: penta2 coverage associated with independent variables
svychisq(~penta12_R + HH6, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta12_R + HH7R, design = mics_design_p1, statistic = "Chisq") #ns
svychisq(~penta12_R + windex5, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta12_R + HL4, design = mics_design_p1, statistic = "Chisq") #ns
svychisq(~penta12_R + ethnicity, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta12_R + melevel, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta12_R + PoB, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta12_R + ANC, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta12_R + ANC_W, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta12_R + ANC_T, design = mics_design_p1, statistic = "Chisq")



## penta123_R

svytable(~penta123_R + HH6, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_R, y=Freq, fill = HH6)) +
  geom_col(position = "fill") 

svytable(~penta123_R + HH7R, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_R, y=Freq, fill = HH7R)) +
  geom_col(position = "fill") 

svytable(~penta123_R + windex5, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_R, y=Freq, fill = windex5)) +
  geom_col(position = "fill") 

svytable(~penta123_R + HL4, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_R, y=Freq, fill = HL4)) +
  geom_col(position = "fill") 

svytable(~penta123_R + ethnicity, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_R, y=Freq, fill = ethnicity)) +
  geom_col(position = "fill") 

svytable(~penta123_R + melevel, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_R, y=Freq, fill = melevel)) +
  geom_col(position = "fill") 

svytable(~penta123_R + PoB, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_R, y=Freq, fill = PoB)) +
  geom_col(position = "fill") 

svytable(~penta123_R + ANC, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_R, y=Freq, fill = ANC)) +
  geom_col(position = "fill") 

svytable(~penta123_R + ANC_W, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_R, y=Freq, fill = ANC_W)) +
  geom_col(position = "fill") 

svytable(~penta123_R + ANC_T, design = mics_design_p1) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=penta123_R, y=Freq, fill = ANC_T)) +
  geom_col(position = "fill") 

# H0: penta3 coverage not associated with independent variables
# H1: penta3 coverage associated with independent variables
svychisq(~penta123_R + HH6, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta123_R + HH7R, design = mics_design_p1, statistic = "Chisq") #ns
svychisq(~penta123_R + windex5, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta123_R + HL4, design = mics_design_p1, statistic = "Chisq") #ns
svychisq(~penta123_R + ethnicity, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta123_R + melevel, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta123_R + PoB, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta123_R + ANC, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta123_R + ANC_W, design = mics_design_p1, statistic = "Chisq") 
svychisq(~penta123_R + ANC_T, design = mics_design_p1, statistic = "Chisq")

```



```{r OR pentavalent Recall + Card}
class(mics4.ch_p1$penta123_RC)

summ(svyglm(penta1_RC ~HH6, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_RC ~HH7R, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_RC ~windex5, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_RC ~HL4, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_RC ~ethnicity, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_RC ~melevel, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_RC ~ethnicity_r, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_RC ~melevel_r, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_RC ~PoB, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_RC ~ANC, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_RC ~ANC_W, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_RC ~ANC_T, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(penta12_RC ~HH6, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_RC ~HH7R, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_RC ~windex5, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_RC ~HL4, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_RC ~ethnicity, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_RC ~melevel, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_RC ~ethnicity_r, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_RC ~melevel_r, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_RC ~PoB, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_RC ~ANC, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_RC ~ANC_W, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_RC ~ANC_T, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(penta123_RC ~HH6, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~HH7R, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~windex5, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~HL4, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~ethnicity, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~melevel, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~ethnicity_r, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~melevel_r, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~PoB, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~ANC, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~ANC_W, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_RC ~ANC_T, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)


```




```{r OR pentavalent Card}

summ(svyglm(penta1_C ~HH6, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_C ~HH7R, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_C ~windex5, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_C ~HL4, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_C ~ethnicity, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_C ~melevel, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_C ~ethnicity_r, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_C ~melevel_r, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_C ~PoB, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_C ~ANC, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_C ~ANC_W, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_C ~ANC_T, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(penta12_C ~HH6, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_C ~HH7R, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_C ~windex5, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_C ~HL4, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_C ~ethnicity, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_C ~melevel, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_C ~ethnicity_r, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_C ~melevel_r, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_C ~PoB, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_C ~ANC, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_C ~ANC_W, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_C ~ANC_T, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(penta123_C ~HH6, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_C ~HH7R, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_C ~windex5, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_C ~HL4, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_C ~ethnicity, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_C ~melevel, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_C ~ethnicity_r, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_C ~melevel_r, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_C ~PoB, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_C ~ANC, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_C ~ANC_W, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_C ~ANC_T, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)




```





```{r OR pentavalent Recall}


summ(svyglm(penta1_R ~HH6, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_R ~HH7R, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_R ~windex5, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_R ~HL4, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_R ~ethnicity, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_R ~melevel, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_R ~ethnicity_r, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_R ~melevel_r, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_R ~PoB, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_R ~ANC, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_R ~ANC_W, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta1_R ~ANC_T, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(penta12_R ~HH6, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_R ~HH7R, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_R ~windex5, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_R ~HL4, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_R ~ethnicity, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_R ~melevel, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_R ~ethnicity_r, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_R ~melevel_r, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_R ~PoB, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_R ~ANC, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_R ~ANC_W, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta12_R ~ANC_T, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)

summ(svyglm(penta123_R ~HH6, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_R ~HH7R, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_R ~windex5, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_R ~HL4, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_R ~ethnicity, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_R ~melevel, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_R ~ethnicity_r, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_R ~melevel_r, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_R ~PoB, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_R ~ANC, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_R ~ANC_W, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)
summ(svyglm(penta123_R ~ANC_T, design = mics_design_p1, family = quasibinomial()), exp = TRUE, confint = TRUE, digits = 2)



```




```{r multivariate penta123}


full <- svyglm(penta123_RC ~HH6 + windex5 + ethnicity_r + melevel_r + HL4 + HH7R +PoB, design = mics_design_p1, family = quasibinomial())

null <- svyglm(penta123_RC ~ 1, design = mics_design_p1, family = quasibinomial())

anova(full,null, test="Chisq") 


# test correlation between variables 
m <- vcov(full)
mcor <- cov2cor(m)
mcor

stepAIC(full, direction = 'backward')

psrsq(full, method = "Nagelkerke")
psrsq(full, method = "Cox-Snell")
psrsq(full, method = c("Cox-Snell", "Nagelkerke"))

# best predicted model

BPM <- svyglm(formula = penta123_RC ~ HH6 + windex5 + ethnicity_r + 
    melevel_r + ANC, design = mics_design_p1, family = quasibinomial())

summ(BPM, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE)


# other possible models ANC varied

A <- svyglm(penta123_RC ~HH6 + windex5 + ethnicity_r + melevel_r + ANC, design = mics_design_p1, family = quasibinomial())

B <- svyglm(penta123_RC ~HH6 + windex5 + ethnicity_r + melevel_r + ANC_T, design = mics_design_p1, family = quasibinomial())

C <- svyglm(penta123_RC ~HH6 + windex5 + ethnicity_r + melevel_r + ANC + ANC_W, design = mics_design_p1, family = quasibinomial())

D <- svyglm(penta123_RC ~HH6 + windex5 + ethnicity_r + melevel_r + PoB, design = mics_design_p1, family = quasibinomial())

E <- svyglm(penta123_RC ~HH6 + windex5 + ethnicity_r + melevel_r + ANC_W, design = mics_design_p1, family = quasibinomial())

summ(A, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )
summ(B, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )
summ(C, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )
summ(D, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )
summ(E, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )


# other possible models independent variables varied

A <- svyglm(penta123_RC ~HH6 + windex5 + ethnicity_r + ANC, design = mics_design_p1, family = quasibinomial())

B <- svyglm(penta123_RC ~HH6 + windex5 + melevel_r + ANC, design = mics_design_p1, family = quasibinomial())

C <- svyglm(penta123_RC ~HH6 + ethnicity_r + melevel_r + ANC, design = mics_design_p1, family = quasibinomial())

D <- svyglm(penta123_RC ~ windex5 + ethnicity_r + melevel_r + ANC, design = mics_design_p1, family = quasibinomial())

summ(A, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )
summ(B, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )
summ(C, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )
summ(D, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )


```



```{r error in stepAIC}


full <- svyglm(penta123_RC ~HH6 + windex5 + ethnicity_r + melevel_r + MN1 + MN2A + MN18_1, design = mics_design_p1, family = quasibinomial())


full_step <- stepAIC(full)


# is because of the NAs

mics4.ch_p1 %>% count(MN18, MN18_1) # 43 # Place of delivery

mics4.ch_p1 %>% count(MN1) # received ANC yes or no  # 1701 NAs

mics4.ch_p1 %>% count(MN2A)  # This is not a "cleaned" variable! It should be a combination variable that indicates one option (i.e. the doctor) against all other options for the delivery
#### Way too many NAs -> this is because it is a combination variable




# only MN18_1
test <- svyglm(penta123_RC ~HH6 + windex5 + ethnicity_r + melevel_r + MN18_1, design = mics_design_p1, family = quasibinomial())
test_step <- stepAIC(test)
test_step$anova

# only MN1
test <- svyglm(penta123_RC ~HH6 + windex5 + ethnicity_r + melevel_r + MN1, design = mics_design_p1, family = quasibinomial())
test_step <- stepAIC(test)
test_step$anova



# only MN2A
test <- svyglm(penta123_RC ~HH6 + windex5 + ethnicity_r + melevel_r + MN2A, design = mics_design_p1, family = quasibinomial())
test_step <- stepAIC(test)
test_step$anova



# only MN18_1 & MN2A
test <- svyglm(penta123_RC ~HH6 + windex5 + ethnicity_r + melevel_r + MN18_1 + MN2A, design = mics_design_p1, family = quasibinomial())
test_step <- stepAIC(test)
test_step$anova

## ERROR


# only MN1 & MN2A
test <- svyglm(penta123_RC ~HH6 + windex5 + ethnicity_r + melevel_r + MN1 + MN2A, design = mics_design_p1, family = quasibinomial())
test_step <- stepAIC(test)
test_step$anova



mics4.ch_p1 %>% count(MN1, MN2A, MN2B, MN2C, MN2F, MN2G, MN2X)

```




```{r multivariate penta123}
# Antenatal care seperately in the model

A <- svyglm(penta123_RC ~HH6 + windex5 + ethnicity_r + melevel_r + ANC + ANC_W, design = mics_design_p1, family = quasibinomial())

B <- svyglm(penta123_RC ~HH6 + windex5 + ethnicity_r + melevel_r + ANC_T, design = mics_design_p1, family = quasibinomial())

C <- svyglm(penta123_RC ~HH6 + windex5 + ethnicity_r + melevel_r + ANC + ANC_W, design = mics_design_p1, family = quasibinomial())

D <- svyglm(penta123_RC ~HH6 + windex5 + ethnicity_r + melevel_r + PoB, design = mics_design_p1, family = quasibinomial())

E <- svyglm(penta123_RC ~HH6 + windex5 + ethnicity_r + melevel_r + ANC_W, design = mics_design_p1, family = quasibinomial())

F <- svyglm(penta123_RC ~HH6, design = mics_design_p1, family = quasibinomial())

G <- svyglm(penta123_RC ~ HH6 + windex5 + melevel_r + ethnicity_r, design = mics_design_p1, family = quasibinomial())

summ(C, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE )


C$aic # does not work


m <- vcov(C)

mcor <- cov2cor(m)

mcor




 
stepAIC(A, direction = 'backward')



class(mics4.ch_p1$HH6)
lrtest(B) # does not work for survey weighted models?

psrsq(C, method = "Nagelkerke")
 
psrsq(C, method = "Cox-Snell")

psrsq(C, method = c("Cox-Snell", "Nagelkerke"))

 

# Compare null model

null <- svyglm(penta123_RC ~ 1, design = mics_design_p1, family = quasibinomial())

# which test is better
anova(C,null, test="Chisq") 


plot(fitted(B),rstandard(B))

 
# Area under curve

prob = predict(B, type=c("response"))

 

g <- pROC::roc(penta123_RC ~ windex5, data = mics4.ch_p1)

plot(g, print.auc=TRUE)   

B$auc

# best predicted model

BPM <- svyglm(formula = penta123_RC ~ HH6 + windex5 + ethnicity_r + 
    melevel_r + ANC, design = mics_design_p1, family = quasibinomial())

summ(BPM, exp = TRUE, confint = TRUE, digits = 2, vifs = TRUE)

```


