---
title: "LAO MICS 3"
author: "Trude"
date: "06-05-2021"
output:
  html_document:
    toc: yes
    toc_depth: 3
    number_sections: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




# Lao PDR: MICS Data - mics3






```{r options}

options(scipen = 999) # suppress scientific notion

```



```{r packages}

library(tidyverse)

# library(expss) # export

library(haven) 

library(sjPlot)

#library(sjlabelled)

#library(labelled)

#library(surveytoolbox) # install with #devtools::install_github("martinctc/surveytoolbox")

library(lubridate) # working with dates

library(survey)

#library(sjmisc)

#library(knitr)

library(janitor)

#library(survminer)

library(DataExplorer)

library(naniar)

```




## Data


```{r dataset mics3}

# package haven
mics3.ch <- read_sav("./data/mics3/ch.sav")

mics3.wm <- read_sav("./data/mics3/wm.sav")

```




## Data: mics3.ch - children under five


```{r mics3.ch glimpse}

# Mothers or primary caretakers of children under five – ch.sav
dim(mics3.ch)
# [1] 4204 335 
glimpse(mics3.ch) 

# look at lables 
sjPlot::view_df(mics3.ch)
mics3.ch %>% labelled::look_for("UF4")
sjPlot::view_df(mics3.wm)

# Mother / caretaker
mics3.ch %>% count(UF4) # range from 1-20
# need to make a individual number for the merging

```

### merging women to children and subset children under 3

```{r merging}
# selecting subset of variables of women's dataset
mics3.wm_var <- subset(mics3.wm, select = c("HH1", "HH2", "LN", "MN2A", "MN2B", "MN2C", "MN2F", "MN2G", "MN2H", "MN2X", "MN2Y","MN8"))

# change variable name in women dataset in order to match with children's
# use of LN or WM4? woman's line number instead of line number
mics3.wm_var$UF6 <- mics3.wm_var$LN
mics3.wm_var$UF6
mics3.wm %>% count(LN, WM4) # probably the same variable


# Merge joining variables from dataset woman to dataset children_2017 using as key variable: UF4 (mothers or caretakers line number in ch.sav).
# Common variables used to merge are: HH1, HH2, UF4 in children, LN in women
mics3.ch_wm <- merge(mics3.ch, mics3.wm_var, by=c("HH1", "HH2", "UF6"), all.x = TRUE)

#subset children under 3
mics3.ch_wm %>% filter(UF11 < 3) -> mics3.ch_b1 # 6

```

## New variables in mics3.ch

```{r household and child id}

# Household ID
mics3.ch_b1 %>% unite(HH_id, c(HH1, HH2), sep = "_", remove = FALSE, na.rm = FALSE) -> mics3.ch_b1

# Are there any duplicates?
mics3.ch_b1 %>% group_by(HH_id) %>% filter(n()>1) %>% summarize(n=n())
# 336 duplicates meaning more children in one household

# Unique id for each child
# UF4 should be the individual number of each child (LN of child)

mics3.ch_b1 %>% unite(ch_id, c(HH1, HH2, UF4), sep = "_", remove = FALSE, na.rm = FALSE) -> mics3.ch_b1
mics3.ch_b1 %>% group_by(ch_id) %>% filter(n()>1) %>% summarize(n=n())
# none 

```

### strata

```{r strata}

# strata
# Do I need a new variable combining HH6 and HH7?
mics3.ch_b1 %>% unite(strata, c(HH7, HH6), sep = "_", remove = FALSE, na.rm = FALSE) -> mics3.ch_b1
mics3.ch_b1 %>% count(strata)

```



```{r date of interview}

# Day of the interview

mics3.ch_b1$UF8D_2 <- as.numeric(as.character(mics3.ch_b1$UF8D))
mics3.ch_b1$UF8Y_2 <- as.numeric(as.character(mics3.ch_b1$UF8Y))
mics3.ch_b1$UF8M_2 <- as.numeric(as.character(mics3.ch_b1$UF8M))

# day of interview
mics3.ch_b1 %>%  mutate(I_date = make_date(UF8Y_2, UF8M_2, UF8D_2)) -> mics3.ch_b1
# A function from lubridate package

```



```{r date of birth}

# Date of birth 
mics3.ch_b1 %>% count(UF10D)
mics3.ch_b1 %>% count(UF10M)

class(mics3.ch_b1$UF10M)

mics3.ch_b1$UF10D_2 <- as.numeric(mics3.ch_b1$UF10D)

mics3.ch_b1$UF10M_2 <- as.numeric(mics3.ch_b1$UF10M)

mics3.ch_b1$UF10Y_2 <- as.numeric(mics3.ch_b1$UF10Y)

mics3.ch_b1 %>%  mutate(dob_ch = make_date(UF10Y_2, UF10M_2, UF10D_2)) -> mics3.ch_b1
mics3.ch_b1$dob_ch
class(mics3.ch_b1$UF10M_2)

```


### tetravalent 1

```{r tetravalent 1}

mics3.ch_b1 %>% filter(UF11 >= 1) -> mics3.ch_p1

# tetra 1 Only Card

mics3.ch_p1 %>% count(IM5AD)

#change date variables into categorical variables
mics3.ch_p1 %>% mutate(tetra1_C = if_else(IM5AD <= 31 & IM5AD >=1, 1,
                                        if_else(IM5AD == 0, 0,
                                        if_else(IM5AD == 44, 44, 66)))) -> mics3.ch_p1
mics3.ch_p1 %>% count(tetra1_C)

mics3.ch_p1 %>% 
  mutate(tetra1_C = recode(tetra1_C,
                           "44" = "1",
                           "66" = "66",
                           "1" = "1",
                           "0" = "0"
                           )) -> mics3.ch_p1
mics3.ch_p1 %>% count(tetra1_C)

# 66 needs to be replaced with NA because this is recall info and not card info # not neccesary here because there are no entries with 66

mics3.ch_p1$tetra1_C_1 <- mics3.ch_p1$tetra1_C
mics3.ch_p1 %>% replace_with_na(replace = list(tetra1_C_1 = "66")) -> mics3.ch_p1
mics3.ch_p1 %>% count(tetra1_C_1)




```

### tetravalent 2

```{r tetravalent 2}



# tetra 2 Only Card

mics3.ch_p1 %>% count(IM5BD)

#change date variables into categorical variables
mics3.ch_p1 %>% mutate(tetra2_C = if_else(IM5BD <= 31 & IM5BD >=1, 1,
                                        if_else(IM5BD == 0, 0,
                                        if_else(IM5BD == 44, 44, 66)))) -> mics3.ch_p1
mics3.ch_p1 %>% count(tetra2_C)

mics3.ch_p1 %>% 
  mutate(tetra2_C = recode(tetra2_C,
                           "44" = "1",
                           "66" = "66",
                           "1" = "1",
                           "0" = "0"
                           )) -> mics3.ch_p1
mics3.ch_p1 %>% count(tetra2_C)

# 66 needs to be replaced with NA because this is recall info and not card info

mics3.ch_p1$tetra2_C_1 <- mics3.ch_p1$tetra2_C
mics3.ch_p1 %>% replace_with_na(replace = list(tetra2_C_1 = "66")) -> mics3.ch_p1
mics3.ch_p1 %>% count(tetra2_C_1)



```


### tetravalent 3

```{r tetravalent 3}


# tetra 3 Only Card

mics3.ch_p1 %>% count(IM5CD)

#change date variables into categorical variables
mics3.ch_p1 %>% mutate(tetra3_C = if_else(IM5CD <= 31 & IM5CD >=1, 1,
                                        if_else(IM5CD == 0, 0,
                                        if_else(IM5CD == 44, 44, 66)))) -> mics3.ch_p1
mics3.ch_p1 %>% count(tetra3_C)

mics3.ch_p1 %>% 
  mutate(tetra3_C = recode(tetra3_C,
                           "44" = "1",
                           "66" = "66",
                           "1" = "1",
                           "0" = "0"
                           )) -> mics3.ch_p1
mics3.ch_p1 %>% count(tetra3_C)

# 66 needs to be replaced with NA because this is recall info and not card info

mics3.ch_p1$tetra3_C_1 <- mics3.ch_p1$tetra3_C
mics3.ch_p1 %>% replace_with_na(replace = list(tetra3_C_1 = "66")) -> mics3.ch_p1
mics3.ch_p1 %>% count(tetra3_C_1)



```

### DPT 1

```{r}

# DPT 1 Only Card

mics3.ch_p1 %>% count(IM4AD)

#change date variables into categorical variables
mics3.ch_p1 %>% mutate(DPT1_C = if_else(IM4AD <= 31 & IM4AD >=1, 1,
                                        if_else(IM4AD == 0, 0,
                                        if_else(IM4AD == 44, 44, 66)))) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT1_C)
mics3.ch_p1 %>% count(DPT1_C, IM15)
mics3.ch_p1 %>% count(DPT1_C, IM15, IM10, IM9)


mics3.ch_p1 %>% 
  mutate(DPT1_C = recode(DPT1_C,
                           "44" = "1",
                           "66" = "66",
                           "1" = "1",
                           "0" = "0"
                           )) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT1_C)

# 66 needs to be replaced with NA because this is recall info and not card info # not neccesary here because there are no entries with 66

mics3.ch_p1$DPT1_C_1 <- mics3.ch_p1$DPT1_C
mics3.ch_p1 %>% replace_with_na(replace = list(DPT1_C_1 = "66")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT1_C_1)


# DTP1 only recall

mics3.ch_p1 %>% count(IM9, IM10, IM15, DPT1_C_1)
mics3.ch_p1 %>% count(IM9, DPT1_C_1)
mics3.ch_p1 %>% count(IM10, IM15)



# First recode IM15 into DPT1_R: recall variable

mics3.ch_p1 %>% count(IM15)
mics3.ch_p1 %>% 
  mutate(DPT1_R = recode(IM15,
                           "1" = "R_1",
                           "2" = "R_0",
                           "8" = "R_8",
                           "9" = "R_9")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT1_R)



# It is not yet correct
# In IM10; if all responses were "NO"; there was no probing for the recall of vaccinations
# Therefore; some of the NAs in the new variable need to be changed to "No" or "DK" #512 no and #13 DK and 2 No response

mics3.ch_p1 %>% 
  mutate(DPT1_R = replace(DPT1_R, is.na(DPT1_R) & IM10 == 2, "R_0"))  %>%
  mutate(DPT1_R = replace(DPT1_R, is.na(DPT1_R) & IM10 == 8, "R_8")) %>%
  mutate(DPT1_R = replace(DPT1_R, is.na(DPT1_R) & IM10 == 9, "R_9")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT1_R)


# combine Recall and Card

mics3.ch_p1 %>% count(DPT1_R, DPT1_C)
mics3.ch_p1 %>% mutate(DPT1_RC = coalesce(DPT1_C, DPT1_R)) -> mics3.ch_p1 
mics3.ch_p1 %>% count(DPT1_RC, IM9)

# Only 1 response is still NA, not categorized. This is solved when using IM9, then the category is 2: Missing, so this response will be categorized as R_0.

mics3.ch_p1 %>% 
  mutate(DPT1_RC = replace(DPT1_RC, is.na(DPT1_RC) & IM9 == 2, "R_0")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT1_RC)


mics3.ch_p1 %>% 
  mutate(DPT1_R_1 = recode(DPT1_RC,
                           "R_0" = "R_0",
                           "R_1" = "R_1",
                           "R_8" = "R_0",
                           "R_9" = "R_0"
                           )) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT1_R_1)

# all outcomes from card RC need to be replaced with NA to only retain recall
mics3.ch_p1 %>% replace_with_na(replace = list(DPT1_R_1 = c("0", "1"))) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT1_R_1)

# combination recall and card
mics3.ch_p1 %>%
  mutate(DPT1_RC_1 = recode(DPT1_RC,
                              "0" = 0,
                              "1" = 1,
                              "R_9" = 0,
                              "R_0" = 0,
                              "R_1" = 1,
                              "R_8" = 0
                              )) -> mics3.ch_p1

mics3.ch_p1 %>% count(DPT1_RC_1) # 0: 1340 1: 3200
mics3.ch_p1 %>% count(DPT1_R_1) # 0: 1051 1: 1376
mics3.ch_p1 %>% count(DPT1_C_1) # 0: 289 1: 1824


```

### DPT 2

```{r}

# DPT 2 Only Card

mics3.ch_p1 %>% count(IM4BD)

#change date variables into categorical variables
mics3.ch_p1 %>% mutate(DPT2_C = if_else(IM4BD <= 31 & IM4BD >=1, 1,
                                        if_else(IM4BD == 0, 0,
                                        if_else(IM4BD == 44, 44, 66)))) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_C)
mics3.ch_p1 %>% count(DPT2_C, IM15)
mics3.ch_p1 %>% count(DPT2_C, IM15, IM10, IM9)


mics3.ch_p1 %>% 
  mutate(DPT2_C = recode(DPT2_C,
                           "44" = "1",
                           "66" = "66",
                           "1" = "1",
                           "0" = "0"
                           )) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_C)

# 66 needs to be replaced with NA because this is recall info and not card info # not neccesary here because there are no entries with 66

mics3.ch_p1$DPT2_C_1 <- mics3.ch_p1$DPT2_C
mics3.ch_p1 %>% replace_with_na(replace = list(DPT2_C_1 = "66")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_C_1)


# DTP1 only recall

mics3.ch_p1 %>% count(IM9, IM10, IM15, DPT2_C_1)
mics3.ch_p1 %>% count(IM9, DPT2_C_1)
mics3.ch_p1 %>% count(IM10, IM15)

# First recode IM16 into DPT2_R: recall variable

mics3.ch_p1 %>% count(IM16)
mics3.ch_p1 %>% 
  mutate(DPT2_R = recode(IM16,
                           "1" = "R_1",
                           "2" = "R_2",
                           "3" = "R_3",
                           "4" = "R_4",
                           "5" = "R_5",
                           "6" = "R_6",
                           "7" = "R_7",
                           "8" = "R_8",
                           "9" = "R_9")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_R)

# make a new variable combining IM15 and IM16. 
# IM 21: 2,3,4,5,6 of 7 means having the second DPTvalent vaccine, IM16: 1,8 or 9 had only one or dont know whether they had one DPTvalent vaccine or more, therefore do not include them assign to 0 together with IM15 No and DK.
 
mics3.ch_p1 %>% count(DPT2_R, DPT1_R)
mics3.ch_p1 %>% mutate(DPT2_R_3 = coalesce(DPT2_R, DPT1_R)) -> mics3.ch_p1 
mics3.ch_p1 %>% count(DPT2_R_3)

mics3.ch_p1 %>% count(IM10, DPT2_R_3) # everything is correct, no need for replacing

# Recode recall variable DPT2 into yes or no

mics3.ch_p1 %>% 
  mutate(DPT2_R_2 = recode(DPT2_R_3,
                           "R_0" = "R_0",
                           "R_1" = "R_0",
                           "R_2" = "R_1",
                           "R_3" = "R_1",
                           "R_4" = "R_1",
                           "R_5" = "R_1",
                           "R_6" = "R_1",
                           "R_7" = "R_1",
                           "R_8" = "R_0",
                           "R_9" = "R_0"
                           )) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_R_2)


# combine Recall and Card

mics3.ch_p1 %>% mutate(DPT2_RC = coalesce(DPT2_R_2, DPT2_C)) -> mics3.ch_p1 
mics3.ch_p1 %>% count(DPT2_RC)
mics3.ch_p1 %>% count(DPT2_RC, IM9)

# Only 1 response is still NA, not categorized. This is solved when using IM9, then the category is 2: Missing, so this response will be categorized as R_0.

mics3.ch_p1 %>% 
  mutate(DPT2_RC = replace(DPT2_RC, is.na(DPT2_RC) & IM9 == 2, "R_0")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_RC)

### old
# DPT 2 Only Card

mics3.ch_p1 %>% count(IM4BD)

#change date variables into categorical variables
mics3.ch_p1 %>% mutate(DPT2_C = if_else(IM4BD <= 31 & IM4BD >=1, 1,
                                        if_else(IM4BD == 0, 0,
                                        if_else(IM4BD == 44, 44, 66)))) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_C)

mics3.ch_p1 %>% 
  mutate(DPT2_C = recode(DPT2_C,
                           "44" = "1",
                           "66" = "66",
                           "1" = "1",
                           "0" = "0"
                           )) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_C)

# 66 needs to be replaced with NA because this is recall info and not card info # not neccesary here because there are no entries with 66

mics3.ch_p1$DPT2_C_1 <- mics3.ch_p1$DPT2_C
mics3.ch_p1 %>% replace_with_na(replace = list(DPT2_C_1 = "66")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_C_1)

# tetra 2 only recall

mics3.ch_p1 %>% count(IM15, IM11, IM11_2, IM11_IM12)




# First recode IM16 into tetra2_R: recall variable

mics3.ch_p1 %>% count(IM16)
mics3.ch_p1 %>% 
  mutate(DPT2_R = recode(IM16,
                           "1" = "R_1",
                           "2" = "R_2",
                           "3" = "R_3",
                           "4" = "R_4",
                           "5" = "R_5",
                           "6" = "R_6",
                           "7" = "R_7",
                           "8" = "R_8",
                           "9" = "R_9")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_R)


# mics3.ch_p1 %>% count(DPT2_R, IM15, IM11, IM11_IM12)

# It is not yet correct
# In IM11 & IM12; if all responses were "NO"; there was no probing for the recall of vaccinations
# Therefore; some of the NAs in the new variable need to be changed to "No" or "DK" #631 no and #38 DK

mics3.ch_p1 %>% 
  mutate(DPT2_R = replace(DPT2_R, is.na(DPT2_R) & IM11 == 2, "R_0"))  %>%
  mutate(DPT2_R = replace(DPT2_R, is.na(DPT2_R) & 
                               IM11 == 8, "R_8")) -> mics3.ch_p1
 mics3.ch_p1 %>% count(DPT2_R)


# make a new variable combining IM15 and IM16. 
# IM 21: 2,3,4,5,6 of 7 means having the second DPTvalent vaccine, IM16: 1,8 or 9 had only one or dont know whether they had one DPTvalent vaccine or more, therefore do not include them assign to 0 together with IM15 No and DK.
 
mics3.ch_p1 %>% count(DPT2_R, DPT1_R)
mics3.ch_p1 %>% mutate(DPT2_R_3 = coalesce(DPT2_R, DPT1_R)) -> mics3.ch_p1 
mics3.ch_p1 %>% count(DPT2_R_3)

# Recode recall variable DPT2 into yes or no

mics3.ch_p1 %>% 
  mutate(DPT2_R_2 = recode(DPT2_R_3,
                           "R_0" = "R_0",
                           "R_1" = "R_0",
                           "R_2" = "R_1",
                           "R_3" = "R_1",
                           "R_4" = "R_1",
                           "R_5" = "R_1",
                           "R_6" = "R_1",
                           "R_7" = "R_1",
                           "R_8" = "R_0",
                           "R_9" = "R_0"
                           )) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_R_2)


# combine Recall and Card

mics3.ch_p1 %>% mutate(DPT2_RC = coalesce(DPT2_R_2, DPT2_C)) -> mics3.ch_p1 
mics3.ch_p1 %>% count(DPT2_RC)

# Now, all responses should be categorized correctly!
# Except for 66 -> which should be categorized as recall (R_1), mother reported that there was a vaccination 

mics3.ch_p1 %>% 
  mutate(DPT2_R_1 = recode(DPT2_RC,
                            "66" = "R_1",
                           "R_0" = "R_0",
                           "R_1" = "R_1"                                                       )) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_R_1)

# all outcomes from card RC need to be replaced with NA to only retain recall
mics3.ch_p1 %>% replace_with_na(replace = list(DPT2_R_1 = c("0", "1"))) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT2_R_1)



# categorize combination recall and card into dichotomous variable
mics3.ch_p1 %>%
  mutate(DPT2_RC_1 = recode(DPT2_RC,
                              "0" = 0,
                              "1" = 1,
                              "66" = 1,
                              "R_0" = 0,
                              "R_1" = 1
                                       )) -> mics3.ch_p1

mics3.ch_p1 %>% count(DPT2_RC_1) # 0: 1734 1: 2806
mics3.ch_p1 %>% count(DPT2_R_1) # 0: 1348 1: 1085
mics3.ch_p1 %>% count(DPT2_C_1) # 0: 386 1: 1721





```

### DPT 3

```{r}

# DPT 3 Only Card

mics3.ch_p1 %>% count(IM4CD)

#change date variables into categorical variables
mics3.ch_p1 %>% mutate(DPT3_C = if_else(IM4CD <= 31 & IM4CD >=1, 1,
                                        if_else(IM4CD == 0, 0,
                                        if_else(IM4CD == 44, 44, 66)))) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT3_C)

mics3.ch_p1 %>% 
  mutate(DPT3_C = recode(DPT3_C,
                           "44" = "1",
                           "66" = "66",
                           "1" = "1",
                           "0" = "0"
                           )) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT3_C)

# 66 needs to be replaced with NA because this is recall info and not card info # not neccesary here because there are no entries with 66

mics3.ch_p1$DPT3_C_1 <- mics3.ch_p1$DPT3_C
mics3.ch_p1 %>% replace_with_na(replace = list(DPT3_C_1 = "66")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT3_C_1)

# tetra 3 only recall

mics3.ch_p1 %>% count(IM15, IM11, IM11_2, IM11_IM12)




# First recode IM16 into tetra3_R: recall variable

mics3.ch_p1 %>% count(IM16)
mics3.ch_p1 %>% 
  mutate(DPT3_R = recode(IM16,
                           "1" = "R_1",
                           "2" = "R_2",
                           "3" = "R_3",
                           "4" = "R_4",
                           "5" = "R_5",
                           "6" = "R_6",
                           "7" = "R_7",
                           "8" = "R_8",
                           "9" = "R_9")) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT3_R)


# mics3.ch_p1 %>% count(DPT3_R, IM15, IM11, IM11_IM12)

# It is not yet correct
# In IM11 & IM12; if all responses were "NO"; there was no probing for the recall of vaccinations
# Therefore; some of the NAs in the new variable need to be changed to "No" or "DK" #631 no and #38 DK

mics3.ch_p1 %>% 
  mutate(DPT3_R = replace(DPT3_R, is.na(DPT3_R) & IM11 == 2, "R_0"))  %>%
  mutate(DPT3_R = replace(DPT3_R, is.na(DPT3_R) & 
                               IM11 == 8, "R_8")) -> mics3.ch_p1
 mics3.ch_p1 %>% count(DPT3_R)


# make a new variable combining IM15 and IM16. 
# IM 21: 2,3,4,5,6 of 7 means having the second DPTvalent vaccine, IM16: 1,8 or 9 had only one or dont know whether they had one DPTvalent vaccine or more, therefore do not include them assign to 0 together with IM15 No and DK.
mics3.ch_p1 %>% count(DPT3_R, DPT1_R)
mics3.ch_p1 %>% mutate(DPT3_R_3 = coalesce(DPT3_R, DPT1_R)) -> mics3.ch_p1 
mics3.ch_p1 %>% count(DPT3_R_3)

# Recode recall variable DPT3 into yes or no

mics3.ch_p1 %>% 
  mutate(DPT3_R_2 = recode(DPT3_R_3,
                           "R_0" = "R_0",
                           "R_1" = "R_0",
                           "R_2" = "R_0",
                           "R_3" = "R_1",
                           "R_4" = "R_1",
                           "R_5" = "R_1",
                           "R_6" = "R_1",
                           "R_7" = "R_1",
                           "R_8" = "R_0",
                           "R_9" = "R_0"
                           )) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT3_R_2)


# combine Recall and Card

mics3.ch_p1 %>% mutate(DPT3_RC = coalesce(DPT3_R_2, DPT3_C)) -> mics3.ch_p1 
mics3.ch_p1 %>% count(DPT3_RC)

# Now, all responses should be categorized correctly!
# Except for 66 -> which should be categorized as recall (R_1), mother reported that there was a vaccination 

mics3.ch_p1 %>% 
  mutate(DPT3_R_1 = recode(DPT3_RC,
                            "66" = "R_1",
                           "R_0" = "R_0",
                           "R_1" = "R_1"                                                       )) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT3_R_1)

# all outcomes from card RC need to be replaced with NA to only retain recall
mics3.ch_p1 %>% replace_with_na(replace = list(DPT3_R_1 = c("0", "1"))) -> mics3.ch_p1
mics3.ch_p1 %>% count(DPT3_R_1)



# categorize combination recall and card into dichotomous variable
mics3.ch_p1 %>%
  mutate(DPT3_RC_1 = recode(DPT3_RC,
                              "0" = 0,
                              "1" = 1,
                              "66" = 1,
                              "R_0" = 0,
                              "R_1" = 1
                                       )) -> mics3.ch_p1

mics3.ch_p1 %>% count(DPT3_RC_1) # 0: 2014 1: 2526
mics3.ch_p1 %>% count(DPT3_R_1) # 0: 1571 1: 864
mics3.ch_p1 %>% count(DPT3_C_1) # 0: 443  1: 1662

```


### Data exploration 


```{r data explorer}

# Data explorer

# introduce(mics3.ch)

# plot_bar(mics3.ch)

```


```{r descriptive}

# UF10 - Consent
mics3.ch %>% count(UF10) # 92 permission not given: looks like these correspond to those 92 children we do not have the age for?
# We can only include those with consent given

# UF17 - completed questionnaire
mics3.ch %>% count(UF17) # COMPLETED 11720

# UB1D,M,Y = DOB child
# other age variables:
mics3.ch %>% count(UF11) # Age in years
mics3.ch %>% count(CAGE) # Age in months
mics3.ch %>% count(CAGED) # Age in days
mics3.ch %>% count(CAGE_6) # Age groups
mics3.ch %>% count(CAGE_11) # other age grouping





# According to questionnaire, only children age 0, 1 or 2 were asked the questions regarding immunization

mics3.ch %>% count(UF11, IM2) # Yes; only chlidren age 0-2 were asked

# But I think, in the report, only children age 0-23 months were inlcuded in the section regarding vaccination


# Characteristics of the children

# anthropology - are all these measurements needed?

mics3.ch %>% count(AN8) # weight in kg; not numeric

mics3.ch %>% ggplot(aes(x=HAP))+geom_histogram()
mics3.ch %>% ggplot(aes(x=HAZ))+geom_histogram()
mics3.ch %>% ggplot(aes(x=HAM))+geom_histogram()
mics3.ch %>% ggplot(aes(x=WAP))+geom_histogram()
mics3.ch %>% ggplot(aes(x=WAZ))+geom_histogram()
mics3.ch %>% ggplot(aes(x=WHP))+geom_histogram()
mics3.ch %>% ggplot(aes(x=WHZ))+geom_histogram()
# there are more


# Mother's education
mics3.ch %>% count(melevel)

# Child disability
mics3.ch %>% count(cdisability)

# area
mics3.ch %>% count(hh6a)

# area
mics3.ch %>% count(hh6b)

# area
mics3.ch %>% count(hh7r)

# ethnicity
mics3.ch %>% count(ethnicity)


# sample weights
mics3.ch %>% count(chweight)

mics3.ch %>% ggplot(aes(x=chweight))+geom_histogram()


```
## Survey design

```{r survey design}

# Data from other datasets need to be added to the children dataset
# Then we need to look at the survey design


# https://campus.datacamp.com/courses/analyzing-survey-data-in-r/exploring-categorical-data-2?ex=1
# datacamp course about sampling weights / survey data


# Understanding the sample design
mics3.ch %>% count(HH1) # enumeration areas; 20 hh were drawn for each enumeration area
mics3.ch %>% count(HH6)

mics3.ch %>% tabyl(HH7, HH6)

mics3.ch %>% count(strata) # 50 rows
# I am unsure what the exact number of the strata is. From what I understand, the provinces AND area (urban, rural, rural wo road) are the strata; 18x3 = 54. Or is it only the 18 provinces?
# The cluster number at least is clear: 1160

# I think it is both province and area!


# How many clusters:

# Provinces are strata
mics3.ch %>% summarize(n_clusters = n_distinct(HH7, HH1))
# 1160

mics3.ch %>% summarize(n_clusters = n_distinct(strata, HH1))
# 1160 # same


# Make design for hepb0 with selected children aged under 3: n = 6887

mics_design <- svydesign(data = mics3.ch, 
                         weights = ~chweight, 
                         id = ~strata+HH1)
mics_design

# Make design for tetravalent with selected children aged under 3 and older than 1 year: n = 4540

mics_design1 <- svydesign(data = mics3.ch_p1, 
                         weights = ~chweight, 
                         id = ~strata+HH1)
mics_design1

# Nest = True or not? 
# Replacement ? I think not - Look at FAQ on mics.unicef; but does it make a difference?


```

## Descriptives weighted

```{r descriptive}


# Ethnicity


# not weighted
mics3.ch %>%                                   
  group_by(ethnicity) %>% 
  summarize(Freq = n()) %>% 
  mutate(Prop = Freq / sum(Freq)) %>% 
     arrange(desc(Prop)) %>% 
  ggplot(mapping = aes(x=ethnicity, y=Prop)) +
  geom_col() +
  coord_flip()


# taking survey design into account 

tab_ethnicity <- svytable(~ethnicity, design = mics_design) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_ethnicity

tab_melevel <- svytable(~melevel, design = mics_design) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_melevel 
  
tab_HL4 <- svytable(~HL4, design = mics_design) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_HL4 

tab_windex5 <- svytable(~windex5, design = mics_design) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_windex5 

tab_HH6 <- svytable(~HH6, design = mics_design) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_HH6 
 
tab_IM2 <- svytable(~IM2, design = mics_design) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_IM2 

tab_IM5 <- svytable(~IM5, design = mics_design) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_IM5 

tab_IM8C <- svytable(~IM8C, design = mics_design) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_IM8C 

tab_hh7r <- svytable(~hh7r, design = mics_design) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_hh7r 

tab_IM6H0D <- svytable(~IM6H0D, design = mics_design) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_IM6H0D
 
tab_IM5AD <- svytable(~IM5AD, design = mics_design1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_IM5AD

tab_IM5BD <- svytable(~IM5BD, design = mics_design1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_IM5BD 

tab_IM5CD <- svytable(~IM5CD, design = mics_design1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_IM5CD 

tab_IM15 <- svytable(~IM15, design = mics_design) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_IM15 

tab_IM15 <- svytable(~IM15, design = mics_design1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_IM15 

tab_IM16 <- svytable(~IM16, design = mics_design1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_IM16 



# What are interesting things to explore in the dataset?

# Province
# Area
# Direction
# Wealth score
# melevel # I guess education mother
# Age
# Ethnicity

svytable(~ethnicity + hh7r, design = mics_design) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=ethnicity, y=Freq, fill = hh7r)) +
  geom_col(position = "fill") +
  coord_flip()


svytable(~ethnicity + windex5, design = mics_design) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=ethnicity, y=Freq, fill = windex5)) +
  geom_col(position = "fill") +
  coord_flip()


svytable(~melevel + HH6, design = mics_design) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=melevel, y=Freq, fill = HH6)) +
  geom_col(position = "fill") +
  coord_flip()


svytable(~melevel + hh7r, design = mics_design) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=melevel, y=Freq, fill = hh7r)) +
  geom_col(position = "fill") +
  coord_flip()


svytable(~melevel + windex5, design = mics_design) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=melevel, y=Freq, fill = windex5)) +
  geom_col(position = "fill") +
  coord_flip()

# Pretty much all looks like you would expect



# Age should not give too many surprises?
svytable(~UF11 + hh7r, design = mics_design) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=UF11, y=Freq, fill = hh7r)) +
  geom_col(position = "fill") +
  coord_flip()

svytable(~ethnicity + UF11, design = mics_design) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=ethnicity, y=Freq, fill = UF11)) +
  geom_col(position = "fill") +
  coord_flip()

svytable(~HL4 + UF11, design = mics_design) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=HL4, y=Freq, fill = UF11)) +
  geom_col(position = "fill") +
  coord_flip()


# Vaccination documents

table(mics3.ch$IM5_2, mics3.ch$UF11)

svytable(~IM5_2 + UF11, design = mics_design) -> tab
tab




table(mics3.ch$IM5_2, mics3.ch$ethnicity)

svytable(~IM5_2 + ethnicity, design = mics_design) -> tab
tab

```

### dependent variables

```{r descriptives dependent variables}
tab_hepb0_RC_2 <- svytable(~hepb0_RC_2, design = mics_design) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_hepb0_RC_2 

tab_hepb0_RC_24 <- svytable(~hepb0_RC_24, design = mics_design) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_hepb0_RC_24 

tab_hepb0_C_2 <- svytable(~hepb0_C_2, design = mics_design) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_hepb0_C_2 

tab_hepb0_C_24 <- svytable(~hepb0_C_24, design = mics_design) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_hepb0_C_24 

tab_hepb0_R_2 <- svytable(~hepb0_R_2, design = mics_design) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_hepb0_R_2 

tab_hepb0_R_R <- svytable(~hepb0_R_R, design = mics_design) %>%
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_hepb0_R_R 

tab_tetra1_RC_1 <- svytable(~tetra1_RC_1, design = mics_design1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_tetra1_RC_1 

tab_tetra1_R_1 <- svytable(~tetra1_R_1, design = mics_design1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_tetra1_R_1 

tab_tetra1_C_1 <- svytable(~tetra1_C_1, design = mics_design1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_tetra1_C_1 

tab_tetra2_RC_1 <- svytable(~tetra2_RC_1, design = mics_design1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_tetra2_RC_1 

tab_tetra2_R_1 <- svytable(~tetra2_R_1, design = mics_design1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_tetra2_R_1 

tab_tetra2_C_1 <- svytable(~tetra2_C_1, design = mics_design1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_tetra2_C_1 

tab_tetra3_RC_1 <- svytable(~tetra3_RC_1, design = mics_design1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_tetra3_RC_1 

tab_tetra3_R_1 <- svytable(~tetra3_R_1, design = mics_design1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_tetra3_R_1 

tab_tetra3_C_1 <- svytable(~tetra3_C_1, design = mics_design1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_tetra3_C_1 


```

```{r inference}

# Looking at two variables: Ethnicity and area (urban / rural)
# Is there an association?

# survey design 

svytable(~ethnicity + HH6, design = mics_design) -> tab
tab <- as.data.frame(tab)
tab
ggplot(data = tab, mapping = aes(x=ethnicity, y=Freq, fill = HH6)) +
  geom_col(position = "fill") +
  coord_flip()


# H0: Area not associated with race
# H1: Area associated with race
# svychisq(~ethnicity + HH6, design = mics_design, statistic = "Chisq") 
# does not work??




svychisq(~ethnicity + HH6, design = mics_design, statistic = "Chisq") 
# X-squared = 1097.5, df = 8, p-value = 0.0003611





# Getting summary statistics while accounting for survey design

# what would be a numeric variable??
# UF11
svymean(~UF11, design = mics_design, na.rm=TRUE)
#       mean     SE
# UF11 2.0415 0.016

svyquantile(x = ~UF11, design = mics_design, na.rm=TRUE, quantiles = 0.5) # 2



svyby(formula = ~UF11, 
      by = ~HH7,
      design = mics_design,
      FUN = svymean, na.rm = TRUE,
      keep.names = FALSE) -> tab
ggplot(data = tab, mapping = aes(x = HH7, y = UF11)) +  
  geom_col() + 
  labs(y = "mean age", x = "Province") # looks terrible


# with error bars

tab <- mutate(tab, lower = UF11 - se, upper = UF11 + se)
tab

ggplot(data = tab, mapping = aes(x = HH7, y = UF11, ymin = lower, ymax = upper)) +  
  geom_col() + 
  geom_errorbar(width = 2) +
  labs(y = "mean age", x = "Province") # looks terrible # Error bars


# Inference
svyttest(formula = UF11 ~ hh6a, design = mics_design) # p-value = 0.4025


```




```{r immunization documents}

# These questions were only asked to children <3

# Immunization documents

mics3.ch %>% filter(UF11 < 3) %>% count(IM2, IM5, IM11) 

# New variables

mics3.ch %>% count(IM5_2) # indicates source of information
mics3.ch %>% count(recall) # recall or not
# but is not perfectly clear; there is also "mothers report" option on vaccination card questions

```




```{r hep B birth dose}

# Subset kids
mics3.ch %>% filter(UF11 < 3) -> mics3.ch_2

# Survey design again, based on option 2

mics_design_2 <- svydesign(data = mics3.ch_2, 
                           weights = ~chweight, 
                           id = ~strata+HH1)
mics_design_2


# Age should not give too many surprises?
svytable(~hbv_bd_3 + HH6, design = mics_design_2) -> tab
tab <- as.data.frame(tab)

ggplot(data = tab, mapping = aes(x=hbv_bd_3, y=Freq, fill = HH6)) +
  geom_col(position = "fill") +
  coord_flip()



# Urban Rural
svytable(~hbv_bd_3 + hh6a, design = mics_design_2) -> tab
tab <- as.data.frame(tab)

ggplot(data = tab, mapping = aes(x=hbv_bd_3, y=Freq, fill = hh6a)) +
  geom_col(position = "fill") +
  coord_flip()



# melevel
svytable(~hbv_bd_3 + melevel, design = mics_design_2) -> tab
tab <- as.data.frame(tab)

ggplot(data = tab, mapping = aes(x=hbv_bd_3, y=Freq, fill = melevel)) +
  geom_col(position = "fill") +
  coord_flip()

tab

```



```{r immunization day}

# immunisation day

mics3.ch %>% count(IM8A) # which is this?

# A NATIONAL POLIO CAMPAIGN
# B NATIONAL MEASLES CAMPAIGN
# C NATIONAL IMMUNIZATION DAY
# D PROVINCIAL HEALTH DAY

```




## Data: mics.hh


```{r check sampling}

mics3.hh %>% tabyl(HH7, HH6) # Provinces explicit strata; area implicit strata

# https://www.restore.ac.uk/PEAS/sratheory.php

#  ‘Explicit stratification’ is where the population of sampling units is explicitly divided into strata and a separate sample selected per stratum. ‘Implicit stratum’ is where the population of sampling units is sorted by some characteristic(s) and then the sample is selected from the sorted list using a fixed sampling interval and a random start. 

```






```{r notes}

# If error code

# https://r-survey.r-forge.r-project.org/survey/exmample-lonely.html
# https://stackoverflow.com/questions/55975478/problems-due-to-having-too-many-single-psus-at-stage-one

# Some PSU only have one: If only one PSU is sampled from a particular stratum the variance can't be computed (there is no unbiased estimator and the standard estimator gives 0/0).


# Work around

#options(survey.adjust.domain.lonely=TRUE)
#options(survey.lonely.psu="adjust")

```














