---
title: "LAO-H-076 MICS study"
author: "lisa"
date: "20 8 2019"
output:
  html_document:
    toc: yes
    toc_depth: 3
    number_sections: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




# Lao PDR: MICS Data - mics6






```{r options}

options(scipen = 999) # suppress scientific notion

```



```{r packages}

library(tidyverse)

# library(expss) # export

library(haven) 

library(sjPlot)

#library(sjlabelled)

#library(labelled)

#library(surveytoolbox) 
# install with #devtools::install_github("martinctc/surveytoolbox")

library(lubridate) # working with dates

library(survey)

#library(sjmisc)

#library(knitr)

library(janitor)

#library(survminer)

library(DataExplorer)

library(naniar)

```




## Data


```{r dataset mics6}

# package haven
mics6.ch <- read_sav("./data/mics6/ch.sav")

mics6.wm <- read_sav("./data/mics6/wm.sav")

```




## Data 


### mics6.ch - children under five


```{r mics6.ch glimpse}

# Mothers or primary caretakers of children under five – ch.sav
dim(mics6.ch)
# [1] 11812   443
glimpse(mics6.ch) 

# look at lables 
sjPlot::view_df(mics6.ch)
mics6.ch %>% labelled::look_for("UF4")

# Mother / caretaker
mics6.ch %>% count(UF4) # range from 1-20
# need to make a individual number for the merging

```


### mics6.wn - Women


```{r mics6.ch glimpse}

# Mothers or primary caretakers of children under five – ch.sav
dim(mics6.wm)

glimpse(mics6.wn) 


```

### Merging women data to children data and subset children under 3


```{r merging}
# selecting subset of variables of women's dataset
mics6.wm_var <- subset(mics6.wm, select = c("HH1", "HH2", "LN", "MN2", "MN3A", "MN3B", "MN3C", "MN3F", "MN3G", "MN3X", "MN5"))

# change variable name in women dataset in order to match with children's
mics6.wm_var$UF4 <- mics6.wm_var$LN
mics6.wm_var %>% count(LN, UF4)


# Merge joining variables from dataset woman to dataset children_2017 using as key variable: UF4 (mothers or caretakers line number in ch.sav).
# Common variables used to merge are: HH1, HH2, UF4 in children, LN in women
mics6.ch_2 <- merge(mics6.ch, mics6.wm_var, by=c("HH1", "HH2", "UF4"), all.x = TRUE)


```


### Subset: Children under 3 

```{r subset}

#subset children under 3
mics6.ch_2 %>% filter(UB2 < 3) -> mics6.ch_2 

# I changed the NAME OF THE DATASET here. It is better to keep the old, original dataset - just in case
# work with a new dataset name

```




### Preparation of dataset



```{r household and child id}

# Household ID
mics6.ch_2 %>% unite(HH_id, c(HH1, HH2), sep = "_", remove = FALSE, na.rm = FALSE) -> mics6.ch_2


# Are there any duplicates?
mics6.ch_2 %>% group_by(HH_id) %>% filter(n()>1) %>% summarize(n=n())
  # many?? assigned to n_HH_id: 2467 observations
# Need to clarify what this means
# Same household ID would suggest children are from same household
# Is there anything in the questionnaire that would indicate that can be more than 1 child under 5 per household
# Does this have any implications for the analysis?

# Yes, it looks as if there is a question at the end, UF16, asking if there is any other child living in that household under 5
mics6.ch_2 %>% filter(UB2 < 3) %>% 
  group_by(HH_id) %>% filter(n()>1) %>% summarize(n=n()) # 839 obs
839/6887 # 12.2%


# Need a unique id for each child
# UF3 should be the individual number of each child (LN of child)
# UF1 = HH1
# UF2 = HH2
mics6.ch_2 %>% unite(ch_id, c(UF1, UF2, UF3), sep = "_", remove = FALSE, na.rm = FALSE) -> mics6.ch_2

mics6.ch_2 %>% group_by(ch_id) %>% filter(n()>1) %>% summarize(n=n()) # none...
# identify each child


```

### strata

```{r strata}

# strata
# Do I need a new variable combining HH6 and HH7?
mics6.ch_2 %>% unite(strata, c(HH7, HH6), sep = "_", remove = FALSE, na.rm = FALSE) -> mics6.ch_2
mics6.ch_2 %>% count(strata)

# This is a good example for the combination of two columns: As you can see, the entries of both columns are connected with "_". Later, you will see another example of merging two columns in which the entries do not overlap

```



```{r date of interview}

# Day of the interview

mics6.ch_2$UF7D_2 <- as.numeric(as.character(mics6.ch_2$UF7D))
mics6.ch_2$UF7Y_2 <- as.numeric(as.character(mics6.ch_2$UF7Y))
mics6.ch_2$UF7M_2 <- as.numeric(as.character(mics6.ch_2$UF7M))

# day of interview
mics6.ch_2 %>%  mutate(I_date = make_date(UF7Y_2, UF7M_2, UF7D_2)) -> mics6.ch_2
# A function from lubridate package

```



```{r date of birth}

# Date of birth 
mics6.ch_2 %>% count(UB1D)
mics6.ch_2 %>% count(UB1M)

class(mics6.ch_2$UB1M)

mics6.ch_2$UB1D_2 <- as.numeric(mics6.ch_2$UB1D)

mics6.ch_2$UB1M_2 <- as.numeric(mics6.ch_2$UB1M)

mics6.ch_2$UB1Y_2 <- as.numeric(mics6.ch_2$UB1Y)

mics6.ch_2 %>%  mutate(dob_ch = make_date(UB1Y_2, UB1M_2, UB1D_2)) -> mics6.ch_2
mics6.ch_2$dob_ch
class(mics6.ch_2$UB1M_2)

```



```{r recall or not}

# IM11
mics6.ch_2 %>% filter(UB2 < 3) %>% count(IM11)
# If vaccination card or any other documents are not available to be checked, IM11 was asked


mics6.ch_2 %>% count(IM11, IM12A, IM12B, IM12C)

# If response to IM11 and IM12 was always No or DK; child did not receive any vaccination!


# Variable: NO or DK

mics6.ch_2 %>% 
  mutate(IM11_IM12 = ifelse((IM11 == 2 | IM11 == 8) & 
                            (IM12A == 2 | IM12A == 8) &
                            (IM12B == 2 | IM12B == 8) &
                             (IM12C == 2 | IM12C == 8), 0, 1)) -> mics6.ch_2
mics6.ch_2 %>% count(IM11_IM12, IM11, IM12A, IM12B, IM12C)

mics6.ch_2 %>% count(IM11, IM11_IM12)

mics6.ch_2 %>% 
  mutate(IM11_2 = ifelse((IM11_IM12 == 0 & IM11 == 2), 2,
                  ifelse((IM11_IM12 == 0 & IM11 == 8), 8, NA))) -> mics6.ch_2

mics6.ch_2 %>% count(IM11,IM11_2)
# looks ok




# Table: is there vaccination card, vaccination document seen, recall
mics6.ch_2 %>% count(IM2, IM5, IM11) # all NAs in kids under 3 are recall; not NA


# New variable
# recall - 0: no; vaccination documents were there
# recall - 1: yes; no vaccination documents 
# Recode all entries into "1"
mics6.ch_2 %>% mutate(recall = recode(IM11, "1" = 1, "2" = 1, "8" = 1)) -> mics6.ch_2
                                  
mics6.ch_2 %>% count(recall) # ok

# Replace all NA in children under 5 with "0"
mics6.ch_2 %>%  mutate(recall = replace(recall, is.na(recall), 0))  -> mics6.ch_2
mics6.ch_2 %>% count(recall)

mics6.ch_2 %>%count(IM11, recall) # seems like it did work

# BUT: Sometimes for the IM6 responses, there was the option for mother´s report.... This is essentially recall!

# I would check that for each vaccination individually

```




```{r notes}

# If error code

# https://r-survey.r-forge.r-project.org/survey/exmample-lonely.html
# https://stackoverflow.com/questions/55975478/problems-due-to-having-too-many-single-psus-at-stage-one

# Some PSU only have one: If only one PSU is sampled from a particular stratum the variance can't be computed (there is no unbiased estimator and the standard estimator gives 0/0).


# Work around

#options(survey.adjust.domain.lonely=TRUE)
#options(survey.lonely.psu="adjust")

```














