---
title: "mics4_td"
author: "Trude"
date: "28-4-2021"
output: github_document:
  toc: true
  toc_depth: 3
  number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Lao PDR: MICS Data - mics4






```{r options}

options(scipen = 999) # suppress scientific notion

```



```{r packages}

library(tidyverse)

# library(expss) # export

library(haven) 

library(sjPlot)

#library(sjlabelled)

#library(labelled)

#library(surveytoolbox) # install with #devtools::install_github("martinctc/surveytoolbox")

library(lubridate) # working with dates

library(survey)

#library(sjmisc)

#library(knitr)

library(janitor)

#library(survminer)

library(DataExplorer)

library(naniar)

```



## Data


```{r dataset mics4}

# package haven
mics4.ch <- read_sav("./data/mics4/ch.sav")

mics4.wm <- read_sav("./data/mics4/wm.sav")

# look at lables 
sjPlot::view_df(mics4.ch)

```

### merging women to children and subset children under 3

```{r merging}
# selecting subset of variables of women's dataset
mics4.wm_var <- subset(mics4.wm, select = c("HH1", "HH2", "LN", "MN1", "MN2A", "MN2B", "MN2C", "MN2F", "MN2G", "MN2X", "MN3", "MN18"))

# change variable name in women dataset in order to match with children's
mics4.wm_var$UF4 <- mics4.wm_var$LN
mics4.wm_var$UF4

# 11258 281
# 23937 12 


# Merge joining variables from dataset woman to dataset children_2017 using as key variable: UF4 (mothers or caretakers line number in ch.sav).
# Common variables used to merge are: HH1, HH2, UF4 in children, LN in women
mics4.ch_wm <- merge(mics4.ch, mics4.wm_var, by=c("HH1", "HH2", "UF4"), all.x = TRUE)

mics4.ch %>% count(CAGE, AG2)

#subset children under 3
mics4.ch_wm %>% filter(AG2 < 3) -> mics4.ch_b1 # 6591 when using CAGE, # 6573 using AG2, difference is because there are 19 children who are 3 years and 35 months, and 1 child 36 month and 2 years old. 

```

```{r recall or not}

# # If response to IM5 and IM6 was always No or DK; child did not receive any vaccination! And will result in NA in recall questions
mics4.ch_b1 %>% count(IM5, IM6, IM19A, IM19B, IM19C)


# New variable: IM5_IM6 = 0 when there was no recall questions done anymore. entry 1 from IM5 also stops the questionnaire.!!

mics4.ch_b1 %>% 
  mutate(IM5_IM6 = ifelse((IM5 == 2 | IM5 == 8) | 
                            (IM6 == 2 | IM6 == 8), 0, 1)) -> mics4.ch_b1
mics4.ch_b1 %>% count(IM5_IM6, IM5, IM6)

mics4.ch_b1 %>% 
  mutate(IM5_IM6_1 = ifelse((IM5 == 2 | IM5 == 8) | 
                            (IM6 == 2 |IM6 == 8 | IM6 == 9), 0, 1)) -> mics4.ch_b1
mics4.ch_b1 %>% count(IM5_IM6_1, IM5, IM6)


mics4.ch_b1 %>% 
  mutate(IM5_2 = ifelse((IM5_IM6 == 0 & IM5 == 2), 2,
                  ifelse((IM5_IM6 == 0 & IM5 == 8), 8, NA))) -> mics4.ch_b1

mics4.ch_b1 %>% count(IM5,IM5_2)
# is this variable necessary?

```

```{r date of birth}

# Date of birth 
mics4.ch_b1 %>% count(AG1D)
mics4.ch_b1 %>% count(AG1M)

class(mics4.ch_b1$UB1M)

mics4.ch_b1$AG1D_2 <- as.numeric(mics4.ch_b1$AG1D)

mics4.ch_b1$AG1M_2 <- as.numeric(mics4.ch_b1$AG1M)

mics4.ch_b1$AG1Y_2 <- as.numeric(mics4.ch_b1$AG1Y)

mics4.ch_b1 %>%  mutate(dob_ch = make_date(AG1Y_2, AG1M_2, AG1D_2)) -> mics4.ch_b1
mics4.ch_b1$dob_ch
class(mics4.ch_b1$AG1M_2)

```

### hepb0

```{r hepatitis B birth dose}


# Convert to numeric values: day/ month/ year

mics4.ch_b1$IM3H0D_2 <- as.numeric(mics4.ch_b1$IM3H0D)
mics4.ch_b1$IM3H0M_2 <- as.numeric(mics4.ch_b1$IM3H0M)
mics4.ch_b1$IM3H0Y_2 <- as.numeric(mics4.ch_b1$IM3H0Y)

# Now create the date
mics4.ch_b1 %>% mutate(IM3H0_date = make_date(IM3H0Y_2, IM3H0M_2, IM3H0D_2)) -> mics4.ch_b1
mics4.ch_b1 %>% count(IM3H0_date) # looks ok


# Time since vaccination

# I am using a command from R base here. There is probably a way to calculate it with a tidyverse command

mics4.ch_b1$IM3H0_time <- as.numeric(difftime(mics4.ch_b1$IM3H0_date, mics4.ch_b1$dob_ch, units = "days"))
summary(mics4.ch_b1$IM3H0_time)
# Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
# -365.00    0.00    0.00   17.44    6.50  688.00    5100 

# Comments on time since vaccination:
# min = -365 probably mistake in year. 
# Max = 688 days; could be a mistake in writing down the year?


# histogram
mics4.ch_b1 %>% ggplot(aes(x=IM3H0_time)) + geom_histogram(binwidth = 1)

# Card: vaccinated within 24 hours

mics4.ch_b1 %>% 
  mutate(hepb0_C24 = ifelse(IM3H0_time == 0, "The same day", ifelse(IM3H0_time == 1, "The next day", "Later"))) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C24) 

# some children can have NA because they have no date of birth instead of no date on vaccination!! They have no info on time since vaccination (IM3H0_time), but that doesn't mean that they are not vaccinated. Check by comparing info on dob and date of vaccination. 

mics4.ch_b1 %>% mutate(dov_1 = if_else(IM3H0D <= 31 & IM3H0D >=1, 1, 0)) -> mics4.ch_b1
mics4.ch_b1 %>% mutate(dob_1 = if_else(AG1D <= 31 & AG1D >=1, 1, 0)) -> mics4.ch_b1
mics4.ch_b1 %>% count(dov_1, dob_1, hepb0_C24)
#24 children have a date on vaccination but no date on birth, therefore the time difference can not be calculated. They are in the category NA, while they should be in the category 'later'. 
#2 children have dates on both vaccination and birth but have NA on hepb0_C24. Why? normally they should be categorized in "LAter". Maybe because the have a negative time??

#change date variables into categorical variables
mics4.ch_b1 %>% mutate(hepb0_C = if_else(IM3H0D <= 31 & IM3H0D >=1, 1,
                                        if_else(IM3H0D == 0, 0,
                                        if_else(IM3H0D == 44, 44, 
                                        if_else(IM3H0D == 66, 66,99))))) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C)

# Code variable hepb0_C
# if date is there = 1
# marked on card = 44
# mother reported = 66  # technically recall 
# missing = 99
# not given = 0


mics4.ch_b1 %>% count(hepb0_C, hepb0_C24) # There are 24 + 2 people for which the the categorization did not work - why? - because there is no date of birth or negative one. 

# combination of card within 24 hours and card date variable
mics4.ch_b1 %>% 
  unite(hepb0_C, c(hepb0_C, hepb0_C24), sep = "_", remove = FALSE, na.rm = FALSE) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C)


# NA_NA needs to be replaced with NA
mics4.ch_b1 %>% replace_with_na(replace = list(hepb0_C = "NA_NA")) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C)


# Recall variable IM14 hepb0 within 24 hours or later
# Recode IM14 into hepb0_R: recall variable

mics4.ch_b1 %>% count(IM14)
mics4.ch_b1$IM14_2 <- as.numeric(mics4.ch_b1$IM14)
mics4.ch_b1 %>% count(IM13)
mics4.ch_b1$IM13_2 <- as.numeric(mics4.ch_b1$IM13)
mics4.ch_b1 %>% 
  mutate(hepb0_R_14 = recode(IM14_2,
                           "1" = "R_Yes",
                           "2" = "R_Later",
                           "9" = "R_9")) -> mics4.ch_b1
mics4.ch_b1 %>% 
  mutate(hepb0_R_13 = recode(IM13_2,
                           "1" = "R_Yes",
                           "2" = "R_No",
                           "8" = "R_8",
                           "9" = "R_9")) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C, hepb0_R_13, hepb0_R_14)


mics4.ch_b1 %>% count(hepb0_C, hepb0_R_13, hepb0_R_14, IM6, IM5)

# It is not yet correct
# In IM6; if responses were No, DK or Missing; there was no probing for the recall of vaccinations
# Therefore; some of the NAs in the new variable need to be changed to "No" or "DK" or Missing

mics4.ch_b1 %>% 
  mutate(hepb0_R_13 = replace(hepb0_R_13, is.na(hepb0_R_13) & IM6 == 2, "R_No"))  %>%
  mutate(hepb0_R_13 = replace(hepb0_R_13, is.na(hepb0_R_13) & IM6 == 8, "R_8"))  %>%
  mutate(hepb0_R_13 = replace(hepb0_R_13, is.na(hepb0_R_13) & IM6 == 9, "R_9")) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_R_13)
mics4.ch_b1 %>% count(hepb0_C, hepb0_R_13, hepb0_R_14)

# Combine Recall variable 13 and 14 into one recall variable
mics4.ch_b1 %>% 
  unite(hepb0_R, c(hepb0_R_13, hepb0_R_14), sep = "_", remove = FALSE, na.rm = FALSE) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C)

mics4.ch_b1 %>% count(hepb0_C, hepb0_R)
mics4.ch_b1 %>% mutate(hepb0_RC = coalesce(hepb0_C, hepb0_R)) -> mics4.ch_b1 
mics4.ch_b1 %>% count(hepb0_RC)

# Now, all responses should be categorized correctly, at least all NA's. 
# Except for 44_NA -> 1_Later: Marked on card, not known whether within 24 hrs
# and 66_NA -> which should be categorized as recall, mother reported that there was a vaccination but not sure whether within 24 hours 

mics4.ch_b1 %>% 
  mutate(hepb0_RC = recode(hepb0_RC,
                           "0_NA" = "0",
                           "1_NA" = "1_Later", 
                           "44_NA" = "1_Later",
                           "66_NA" = "R_Later",
                           "99_NA" = "0",
                           "R_8_NA" = "R_8",
                           "R_9_NA" = "R_9",
                           "R_No_NA" = "R_No",
                           "R_Yes_R_9" = "R_Later",
                           "R_Yes_R_Later" = "R_Later",
                           "R_Yes_R_Yes" = "R_Yes" )) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_RC)

# hepatitis B birth dose (yes, no)
# DK will be grouped with no
# Missing will be grouped with no
# Within 24 hours or the next day: 1
# later: 2
# no vaccination: 0
mics4.ch_b1 %>% 
  mutate(hepb0_RC_1 = recode(hepb0_RC,
                           "0" = "0",
                           "1_Later" = "2",
                           "1_The next day" = "1",
                           "1_The same day" = "1",
                           "R_No" = "0",
                           "R_8" = "0",
                           "R_9" = "0",
                           "R_Later" = "2",
                           "R_Yes" = "1")) -> mics4.ch_b1

mics4.ch_b1 %>% count(hepb0_RC_1, hepb0_RC)


# create new variable within 24 hours: 1, not within 24 hours:0
mics4.ch_b1 %>% 
  mutate(hepb0_RC_24 = recode(hepb0_RC_1,
                           "0" = "0",
                           "2" = "0",
                           "1" = "1"
                          )) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_RC_24)

# create new variable hepb0 yes or no card and recall
mics4.ch_b1 %>% 
  mutate(hepb0_RC_2 = recode(hepb0_RC_1,
                           "0" = "0",
                           "2" = "1",
                           "1" = "1"
                          )) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_RC_2)

# only card
# 66_NA needs to be replaced with NA
mics4.ch_b1 %>% replace_with_na(replace = list(hepb0_C = "66_NA")) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C)

# only card variable hepb0 (yes/no)
mics4.ch_b1 %>% 
  mutate(hepb0_C_2 = recode(hepb0_C,
                           "0_NA" = "0",
                           "1_Later" = "1",
                           "1_NA" = "1",
                           "1_The next day" = "1",
                           "1_The same day" = "1",
                           "44_NA" = "1",
                           "99_NA" = "0")) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C_2)

# only card variable hepb0 (24hrs)
mics4.ch_b1 %>% 
  mutate(hepb0_C_24 = recode(hepb0_C,
                           "0_NA" = "0",
                           "1_Later" = "0",
                           "1_NA" = "0",
                           "1_The next day" = "1",
                           "1_The same day" = "1",
                           "44_NA" = "0",
                           "99_NA" = "0")) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_C_24)

mics4.ch_b1$hepb0_R_1 <- mics4.ch_b1$hepb0_RC
mics4.ch_b1 %>% count(hepb0_R_1)

# all outcomes from Card need to be replaced with NA: hepb0_RC is now variable hepb0_R with recall from card variable outcome 66
mics4.ch_b1 %>% replace_with_na(replace = list(hepb0_R_1 = c("0", "1_Later", "1_The next day", "1_The same day"))) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_R_1)

# only recal hepbo within 24 hours (yes/no)
mics4.ch_b1 %>%
  mutate(hepb0_R_24 = recode(hepb0_R_1,
                           "R_No" = "0",
                           "R_8" = "0",
                           "R_9" = "0",
                           "R_Later" = "0",
                           "R_Yes" = "1")) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_R_24)

# only recall variable hepb0 (yes/no)
mics4.ch_b1 %>% 
  mutate(hepb0_R_2 = recode(hepb0_R_1,
                           "R_No" = "0",
                           "R_8" = "0",
                           "R_9" = "0",
                           "R_Later" = "1",
                           "R_Yes" = "1"
                          )) -> mics4.ch_b1
mics4.ch_b1 %>% count(hepb0_R_2)


# Needed dichotomous variables for analysis
mics4.ch_b1 %>% count(hepb0_RC_2) # 0: 3444 1: 3129
mics4.ch_b1 %>% count(hepb0_RC_24)# 0: 5287 1: 1286
mics4.ch_b1 %>% count(hepb0_C_2)  # 0: 1197 1: 1653
mics4.ch_b1 %>% count(hepb0_C_24) # 0: 1939 1: 911
mics4.ch_b1 %>% count(hepb0_R_2) # 0: 2247 1: 1476
mics4.ch_b1 %>% count(hepb0_R_24) # 0: 3348 1: 375



```

### Pentavalent 1

```{r pentavalent 1}

mics4.ch_b1 %>% filter(CAGED > 365) -> mics4.ch_p1

# Penta 1 Only Card

mics4.ch_p1 %>% count(IM3H1D)

#change date variables into categorical variables
mics4.ch_p1 %>% mutate(penta1_C = if_else(IM3H1D <= 31 & IM3H1D >=1, 1,
                                        if_else(IM3H1D == 0, 0,
                                        if_else(IM3H1D == 44, 44,
                                        if_else(IM3H1D == 99, 99, 66))))) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_C)

mics4.ch_p1 %>% 
  mutate(penta1_C = recode(penta1_C,
                           "44" = "1",
                           "66" = "66",
                           "99" = "0",
                           "1" = "1",
                           "0" = "0"
                           )) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_C)

# 66 needs to be replaced with NA because this is recall info and not card info
# penta1_C_1: only card variable
mics4.ch_p1$penta1_C_1 <- mics4.ch_p1$penta1_C
mics4.ch_p1 %>% replace_with_na(replace = list(penta1_C_1 = "66")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_C_1)


# Penta 1 only recall



# First recode IM11 into penta1_R: recall variable

mics4.ch_p1 %>% count(IM11)
mics4.ch_p1$IM11_2 <- as.factor(mics4.ch_p1$IM11)

mics4.ch_p1 %>% 
  mutate(penta1_R = recode(IM11_2,
                           "1" = "R_1",
                           "2" = "R_0",
                           "8" = "R_8")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_R)

mics4.ch_p1 %>% count(penta1_R, IM5, IM6, penta1_C)
mics4.ch_p1 %>% count(IM6, penta1_C)


# It is not yet correct
# In IM6; if all responses were "NO"; there was no probing for the recall of vaccinations
# Therefore; some of the NAs in the new variable need to be changed to "No" or "DK" #564 no and #11 DK and 3 missing


mics4.ch_p1 %>% 
  mutate(penta1_R = replace(penta1_R, is.na(penta1_R) & IM6 == 2, "R_0"))  %>%
  mutate(penta1_R = replace(penta1_R, is.na(penta1_R) & IM6 == 8, "R_8")) %>%
  mutate(penta1_R = replace(penta1_R, is.na(penta1_R) & IM6 == 9, "R_0")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_R)


# combine Recall and Card

mics4.ch_p1 %>% count(penta1_R, penta1_C)
mics4.ch_p1 %>% mutate(penta1_RC = coalesce(penta1_R, penta1_C)) -> mics4.ch_p1 
mics4.ch_p1 %>% count(penta1_RC)

# Now, all responses should be categorized correctly !!!
# Except for R_8 -> R_0 # and 66 -> which should be categorized as recall, mother reported that there was a vaccination but not sure whether within 24 hours 

mics4.ch_p1 %>% 
  mutate(penta1_R_1 = recode(penta1_RC,
                            "66" = "R_1",
                           "R_0" = "R_0",
                           "R_1" = "R_1",
                           "R_8" = "R_0"
                           )) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_R_1)

# all outcomes from card RC need to be replaced with NA to only retain recall
mics4.ch_p1 %>% replace_with_na(replace = list(penta1_R_1 = c("0", "1"))) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta1_R_1)

# combination recall and card
mics4.ch_p1 %>%
  mutate(penta1_RC_1 = recode(penta1_RC,
                              "0" = 0,
                              "1" = 1,
                              "66" = 1,
                              "R_0" = 0,
                              "R_1" = 1,
                              "R_8" = 0
                              )) -> mics4.ch_p1

mics4.ch_p1 %>% count(penta1_RC_1) # 0: 940 1: 3374
mics4.ch_p1 %>% count(penta1_R_1) # 0: 867 1: 1605
mics4.ch_p1 %>% count(penta1_C_1) # 0: 73 1: 1769

```
### Pentavalent 2

```{r pentavalent 2}


# Penta 2 Only Card

mics4.ch_p1 %>% count(IM3H2D)

#change date variables into categorical variables
mics4.ch_p1 %>% mutate(penta2_C = if_else(IM3H2D <= 31 & IM3H2D >=1, 1,
                                        if_else(IM3H2D == 0, 0,
                                        if_else(IM3H2D == 44, 44,
                                        if_else(IM3H2D == 99, 99, 66))))) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_C)

mics4.ch_p1 %>% 
  mutate(penta2_C = recode(penta2_C,
                           "44" = "1",
                           "66" = "66",
                           "99" = "0",
                           "1" = "1",
                           "0" = "0"
                           )) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_C)

# 66 needs to be replaced with NA because this is recall info and not card info
# penta2_C_1: only card variable
mics4.ch_p1$penta2_C_1 <- mics4.ch_p1$penta2_C
mics4.ch_p1 %>% replace_with_na(replace = list(penta2_C_1 = "66")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_C_1)


# Penta 2 only recall



# First recode IM11 into penta2_R: recall variable

mics4.ch_p1 %>% count(IM12)
mics4.ch_p1$IM12_2 <- as.numeric(mics4.ch_p1$IM12)

mics4.ch_p1 %>% 
  mutate(penta2_R = recode(IM12_2,
                           "1" = "R_1",
                           "2" = "R_2",
                           "3" = "R_3",
                           "4" = "R_4",
                           "5" = "R_5",
                           "6" = "R_6",
                           "7" = "R_7",
                           "8" = "R_8",
                           "9" = "R_9")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_R)

# mics4.ch_p1 %>% count(penta2_R, IM5, IM6, penta2_C)
# mics4.ch_p1 %>% count(IM6, penta2_C)

# It is not yet correct
# In IM6; if all responses were "NO"; there was no probing for the recall of vaccinations
# Therefore; some of the NAs in the new variable need to be changed to "No" or "DK" #564 no and #11 DK and 3 missing


mics4.ch_p1 %>% 
  mutate(penta2_R = replace(penta2_R, is.na(penta2_R) & IM6 == 2, "R_0"))  %>%
  mutate(penta2_R = replace(penta2_R, is.na(penta2_R) & IM6 == 8, "R_8")) %>%
  mutate(penta2_R = replace(penta2_R, is.na(penta2_R) & IM6 == 9, "R_9")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_R) 
mics4.ch_p1 %>% count(penta1_R)


# make a new variable combining IM20 and IM21. 
# IM 21: 2,3,4,5,6 of 7 means having the second pentavalent vaccine, IM21: 1,8 or 9 had only one or dont know whether they had one pentavalent vaccine or more, therefore do not include them assign to 0 together with IM20 No and DK = penta1_R.

mics4.ch_p1 %>% count(penta2_R, penta1_R)
mics4.ch_p1 %>% mutate(penta2_R_3 = coalesce(penta2_R, penta1_R)) -> mics4.ch_p1 
mics4.ch_p1 %>% count(penta2_R_3)

# Recode recall variable penta 2 into yes or no

mics4.ch_p1 %>% 
  mutate(penta2_R_2 = recode(penta2_R_3,
                           "R_0" = "R_0",
                           "R_1" = "R_0",
                           "R_2" = "R_1",
                           "R_3" = "R_1",
                           "R_4" = "R_1",
                           "R_5" = "R_1",
                           "R_6" = "R_1",
                           "R_7" = "R_1",
                           "R_8" = "R_0",
                           "R_9" = "R_0"
                           )) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_R_2)

# combine Recall and Card

mics4.ch_p1 %>% mutate(penta2_RC = coalesce(penta2_R_2, penta2_C)) -> mics4.ch_p1 
mics4.ch_p1 %>% count(penta2_RC)

# Now, all responses should be categorized correctly !!!
# Except for R_8 -> R_0 # and 66 -> which should be categorized as recall, mother reported that there was a vaccination but not sure whether within 24 hours 

mics4.ch_p1 %>% 
  mutate(penta2_R_1 = recode(penta2_RC,
                            "66" = "R_1",
                           "R_0" = "R_0",
                           "R_1" = "R_1",
                           )) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_R_1)

# all outcomes from card RC need to be replaced with NA to only retain recall
mics4.ch_p1 %>% replace_with_na(replace = list(penta2_R_1 = c("0", "1"))) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta2_R_1)

# combination recall and card
mics4.ch_p1 %>%
  mutate(penta2_RC_1 = recode(penta2_RC,
                              "0" = 0,
                              "1" = 1,
                              "66" = 1,
                              "R_0" = 0,
                              "R_1" = 1,
                                             )) -> mics4.ch_p1

mics4.ch_p1 %>% count(penta2_RC_1) # 0: 1360 1: 2954
mics4.ch_p1 %>% count(penta2_R_1) # 0: 1186 1: 1298
mics4.ch_p1 %>% count(penta2_C_1) # 0: 174 1: 1656

```

### Pentavalent 3

```{r pentavalent 3}


# Penta 3 Only Card

mics4.ch_p1 %>% count(IM3H3D)

#change date variables into categorical variables
mics4.ch_p1 %>% mutate(penta3_C = if_else(IM3H3D <= 31 & IM3H3D >=1, 1,
                                        if_else(IM3H3D == 0, 0,
                                        if_else(IM3H3D == 44, 44,   
                                        if_else(IM3H3D == 66, 66, 99))))) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta3_C)

mics4.ch_p1 %>% 
  mutate(penta3_C = recode(penta3_C,
                           "44" = "1",
                           "66" = "66",
                           "99" = "0",
                           "1" = "1",
                           "0" = "0"
                           )) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta3_C)

# 66 needs to be replaced with NA because this is recall info and not card info

mics4.ch_p1$penta3_C_1 <- mics4.ch_p1$penta3_C
mics4.ch_p1 %>% replace_with_na(replace = list(penta3_C_1 = "66")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta3_C_1)


# Penta 2 only recall

mics4.ch_p1 %>% count(IM11, IM12, IM5, IM6)
mics4.ch_p1 %>% count(IM11, IM12, IM6)




# First recode IM12 into penta3_R: recall variable

mics4.ch_p1 %>% count(IM12)
mics4.ch_p1 %>% 
  mutate(penta3_R = recode(IM12,
                           "1" = "R_1",
                           "2" = "R_2",
                           "3" = "R_3",
                           "4" = "R_4",
                           "5" = "R_5",
                           "6" = "R_6",
                           "7" = "R_7",
                           "8" = "R_8",
                           "9" = "R_9")) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta3_R)


mics4.ch_p1 %>% count(penta3_R, IM11, IM5, IM6)

# It is not yet correct
# In IM11 & IM12; if all responses were "NO"; there was no probing for the recall of vaccinations
# Therefore; some of the NAs in the new variable need to be changed to "No" or "DK" #564 no and #11 DK and # 3 missing values. 

mics4.ch_p1 %>% 
  mutate(penta3_R = replace(penta3_R, is.na(penta3_R) & IM6 == 2, "R_0"))  %>%
  mutate(penta3_R = replace(penta3_R, is.na(penta3_R) & IM6 == 8, "R_8")) %>%
  mutate(penta3_R = replace(penta3_R, is.na(penta3_R) & IM6 == 9, "R_9"))-> mics4.ch_p1
 mics4.ch_p1 %>% count(penta3_R)


# make a new variable combining IM11 and IM12. 
# IM 21: 2,3,4,5,6 of 7 means having the second pentavalent vaccine, IM21: 1,8 or 9 had only one or dont know whether they had one pentavalent vaccine or more, therefore do not include them assign to 0 together with IM20 No and DK.
mics4.ch_p1 %>% count(penta3_R, penta1_R)
mics4.ch_p1 %>% mutate(penta3_R_3 = coalesce(penta3_R, penta1_R)) -> mics4.ch_p1 
mics4.ch_p1 %>% count(penta3_R_3)

# Recode recall variable penta3 into yes or no

mics4.ch_p1 %>% 
  mutate(penta3_R_2 = recode(penta3_R_3,
                           "R_0" = "R_0",
                           "R_1" = "R_0",
                           "R_2" = "R_0",
                           "R_3" = "R_1",
                           "R_4" = "R_1",
                           "R_5" = "R_1",
                           "R_6" = "R_1",
                           "R_7" = "R_1",
                           "R_8" = "R_0",
                           "R_9" = "R_0"
                           )) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta3_R_2)


# combine Recall and Card

mics4.ch_p1 %>% mutate(penta3_RC = coalesce(penta3_R_2, penta3_C)) -> mics4.ch_p1 
mics4.ch_p1 %>% count(penta3_RC)

# Now, all responses should be categorized correctly!
# Except for 66 -> which should be categorized as recall (R_1), mother reported that there was a vaccination 

mics4.ch_p1 %>% 
  mutate(penta3_R_1 = recode(penta3_RC,
                            "66" = "R_1",
                           "R_0" = "R_0",
                           "R_1" = "R_1"                                                       )) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta3_R_1)

# all outcomes from card RC need to be replaced with NA to only retain recall
mics4.ch_p1 %>% replace_with_na(replace = list(penta3_R_1 = c("0", "1"))) -> mics4.ch_p1
mics4.ch_p1 %>% count(penta3_R_1)



# categorize combination recall and card into dichotomous variable
mics4.ch_p1 %>%
  mutate(penta3_RC_1 = recode(penta3_RC,
                              "0" = 0,
                              "1" = 1,
                              "66" = 1,
                              "R_0" = 0,
                              "R_1" = 1
                                       )) -> mics4.ch_p1

mics4.ch_p1 %>% count(penta3_RC_1) # 0: 1893 1: 2421
mics4.ch_p1 %>% count(penta3_R_1) # 0: 1552 1: 955
mics4.ch_p1 %>% count(penta3_C_1) # 0: 341  1: 1466


```

## Survey design

### strata

```{r strata}

# strata
# New variable combining HH6 and HH7
mics4.ch_b1 %>% unite(strata, c(HH7, HH6), sep = "_", remove = FALSE, na.rm = FALSE) -> mics4.ch_b1
mics4.ch_b1 %>% count(strata)

# New variable combining HH6 and HH7
mics4.ch_p1 %>% unite(strata, c(HH7, HH6), sep = "_", remove = FALSE, na.rm = FALSE) -> mics4.ch_p1
mics4.ch_p1 %>% count(strata)

# New variable combining HH6 and HH7
mics4.ch %>% unite(strata, c(HH7, HH6), sep = "_", remove = FALSE, na.rm = FALSE) -> mics4.ch
mics4.ch %>% count(strata)

```

### design

```{r survey design}

# Understanding the sample design
mics4.ch %>% count(HH1) # enumeration areas; 20 hh were drawn for each enumeration area
mics4.ch %>% count(HH6)
mics4.ch %>% tabyl(HH7, HH6)

mics4.ch %>% count(strata) # 49 rows

# How many clusters:

# Provinces are strata
mics4.ch %>% summarize(n_clusters = n_distinct(HH7, HH1))
# 998

mics4.ch %>% summarize(n_clusters = n_distinct(strata, HH1))
# 998 # same


# Make design for hepb0 with selected children aged under 3: n = 6573

mics_design_b1 <- svydesign(data = mics4.ch_b1, 
                         weights = ~chweight, 
                         id = ~strata+HH1)


# Make design for pentavalent with selected children aged under 3 and older than 1 year: n = 4314

mics_design_p1 <- svydesign(data = mics4.ch_p1, 
                         weights = ~chweight, 
                         id = ~strata+HH1)



```

## Descriptives weighted
### independent variables

```{r descriptive}


# taking survey design into account 

# What are interesting things to explore in the dataset?

# Province
# Area
# Direction?
# Wealth score
# melevel education mother
# Age
# Ethnicity

tab_ethnicity <- svytable(~ethnicity, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_ethnicity

tab_melevel <- svytable(~melevel, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_melevel 
  
tab_HL4 <- svytable(~HL4, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_HL4 

tab_windex5 <- svytable(~windex5, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_windex5 

tab_HH6 <- svytable(~HH6, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_HH6 

tab_HH7R <- svytable(~HH7R, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_HH7R 

 
# combination of independent variables in graphs

svytable(~ethnicity + HH7R, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=ethnicity, y=Freq, fill = HH7R)) +
  geom_col(position = "fill") +
  coord_flip()


svytable(~ethnicity + windex5, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=ethnicity, y=Freq, fill = windex5)) +
  geom_col(position = "fill") +
  coord_flip()


svytable(~melevel + HH6, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=melevel, y=Freq, fill = HH6)) +
  geom_col(position = "fill") +
  coord_flip()


svytable(~melevel + HH7R, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=melevel, y=Freq, fill = HH7R)) +
  geom_col(position = "fill") +
  coord_flip()


svytable(~melevel + windex5, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=melevel, y=Freq, fill = windex5)) +
  geom_col(position = "fill") +
  coord_flip()

# Pretty much all looks like you would expect



# Age should not give too many surprises?
svytable(~AG2 + HH7R, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=AG2, y=Freq, fill = HH7R)) +
  geom_col(position = "fill") +
  coord_flip()

svytable(~ethnicity + AG2, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=ethnicity, y=Freq, fill = AG2)) +
  geom_col(position = "fill") +
  coord_flip()

svytable(~HL4 + AG2, design = mics_design_b1) -> tab
tab <- as.data.frame(tab)
ggplot(data = tab, mapping = aes(x=HL4, y=Freq, fill = AG2)) +
  geom_col(position = "fill") +
  coord_flip()


# Vaccination documents


```

### dependent variables

```{r descriptives dependent variables}

tab_hepb0_RC_2 <- svytable(~hepb0_RC_2, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_hepb0_RC_2 

tab_hepb0_RC_24 <- svytable(~hepb0_RC_24, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_hepb0_RC_24 

tab_hepb0_C_2 <- svytable(~hepb0_C_2, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_hepb0_C_2 

tab_hepb0_C_24 <- svytable(~hepb0_C_24, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_hepb0_C_24 

tab_hepb0_R_2 <- svytable(~hepb0_R_2, design = mics_design_b1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_hepb0_R_2 

tab_hepb0_R_24 <- svytable(~hepb0_R_24, design = mics_design_b1) %>%
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_hepb0_R_24 

tab_penta1_RC_1 <- svytable(~penta1_RC_1, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_penta1_RC_1 

tab_penta1_R_1 <- svytable(~penta1_R_1, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_penta1_R_1 

tab_penta1_C_1 <- svytable(~penta1_C_1, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_penta1_C_1 

tab_penta2_RC_1 <- svytable(~penta2_RC_1, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_penta2_RC_1 

tab_penta2_R_1 <- svytable(~penta2_R_1, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_penta2_R_1 

tab_penta2_C_1 <- svytable(~penta2_C_1, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_penta2_C_1 

tab_penta3_RC_1 <- svytable(~penta3_RC_1, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_penta3_RC_1 

tab_penta3_R_1 <- svytable(~penta3_R_1, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_penta3_R_1 

tab_penta3_C_1 <- svytable(~penta3_C_1, design = mics_design_p1) %>% 
  as.data.frame() %>% 
  mutate(Prop = round(Freq / sum(Freq)*100, 2)) %>%
  mutate(Total = sum(Freq)) 
tab_penta3_C_1 


```